src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID Field</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Reference data for Organization Type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider;Service Provider</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_at_Risk__c.object
<CustomObject>
    <description>This object will contain information to help manage business at risk.</description>
    <fields>
        <fullName>Expected_Loss_Date__c</fullName>
        <inlineHelpText>If Assets were to leave, this is the expected redemption date</inlineHelpText>
        <label>Potential Loss Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business at Risk</relationshipLabel>
        <relationshipName>Business_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_at_Risk__c</fullName>
        <inlineHelpText>Probability of losing the business
High - 75 - 100%
Medium - 50 - 74.99%
Low - 25 - 49.99%
Redeeming - 0 - 24.99%</inlineHelpText>
        <label>Probability of Loss</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeeming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_at_Risk__c</fullName>
        <inlineHelpText>This will contain the reason the business is at risk.</inlineHelpText>
        <label>Reason at Risk</label>
        <picklist>
            <picklistValues>
                <fullName>De-risking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In House Management/ OCIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Client Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebalance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business at Risk</label>
    <nameField>
        <label>Business at Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_BusinessAtRiskRedirectControllerTest.cls
@isTest(seeAllData=false)
public class MFS_BusinessAtRiskRedirectControllerTest {
    static testMethod void redirectionTestInstitutional() {
        Account acc = MFS_TestDataUtility.createAccount();
        acc.MDM_ID__c = '1234567890';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Institutional Client').getRecordtypeId();
        insert acc;
        Business_At_Risk__c br = new Business_At_Risk__c();
        br.Organization__c = acc.Id;
        br.Expected_Loss_Date__c = System.Today();
        br.Percentage_at_Risk__c = 'Low';
        br.Expected_Loss_Date__c = System.Today()+1;
        br.Reason_at_Risk__c = 'Regulatory';
        br.Status__c = 'Open';
        insert br;
        PageReference pr =  new PageReference('/'+br.id);
        pr.getParameters().put('id',br.id);
        //pr.getParameters().put('retURL',br.id);
        Test.setCurrentPage(pr);
        MFS_BusinessAtRiskRedirectController BAR = new MFS_BusinessAtRiskRedirectController(new ApexPages.StandardController(br));
        Pagereference redirect = BAR.redirect();
        Pagereference redirectDetail = BAR.redirectDetail();
        
        PageReference pr1 =  new PageReference('/'+br.id);
        pr1.getParameters().put('id',br.id);
        pr1.getParameters().put('retURL',br.id);
        Test.setCurrentPage(pr1);
        MFS_BusinessAtRiskRedirectController BAR1 = new MFS_BusinessAtRiskRedirectController(new ApexPages.StandardController(br));
        Pagereference redirect1 = BAR1.redirect();
        Pagereference redirectDetail1 = BAR1.redirectDetail();
        
        br.type__c = 'Institutional';
        update br;
        PageReference pr2 =  new PageReference('/'+br.id);
        pr2.getParameters().put('id',br.id);
        pr2.getParameters().put('retURL',br.id);
        Test.setCurrentPage(pr2);
        MFS_BusinessAtRiskRedirectController BAR2 = new MFS_BusinessAtRiskRedirectController(new ApexPages.StandardController(br));
        Pagereference redirect2 = BAR1.redirect();
        Pagereference redirectDetail2 = BAR1.redirectDetail();
        //SONAR FIX
        system.assertNotEquals(null, redirectDetail2.getUrl());
        
    }
    
    static testMethod void redirectionTestRetail() {
        Account acc = MFS_TestDataUtility.createAccount();
        acc.MDM_ID__c = '1234567890';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Retail').getRecordtypeId();
        insert acc;
        Business_At_Risk__c br = new Business_At_Risk__c();
        br.Organization__c = acc.Id;
        br.Expected_Loss_Date__c = System.Today();
        br.Percentage_at_Risk__c = 'Low';
        br.Expected_Loss_Date__c = System.Today()+1;
        br.Reason_at_Risk__c = 'Regulatory';
        br.Status__c = 'Open';
        insert br;
        PageReference pr =  new PageReference('/'+br.id);
        pr.getParameters().put('id',br.id);
        //pr.getParameters().put('retURL',br.id);
        Test.setCurrentPage(pr);
        MFS_BusinessAtRiskRedirectController BAR = new MFS_BusinessAtRiskRedirectController(new ApexPages.StandardController(br));
        Pagereference redirect = BAR.redirect();
        Pagereference redirectDetail = BAR.redirectDetail();
        //SONAR FIX
        system.assertNotEquals(null, redirectDetail.getUrl());
    }
    
    static testMethod void redirectionTestInvstConsul() {
        Account acc = MFS_TestDataUtility.createAccount();
        acc.MDM_ID__c = '1234567890';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Investment Consultant').getRecordtypeId();
        insert acc;
        Business_At_Risk__c br = new Business_At_Risk__c();
        br.Organization__c = acc.Id;
        br.Expected_Loss_Date__c = System.Today();
        br.Percentage_at_Risk__c = 'Low';
        br.Expected_Loss_Date__c = System.Today()+1;
        br.Reason_at_Risk__c = 'Regulatory';
        br.Status__c = 'Open';
        insert br;
        PageReference pr =  new PageReference('/'+br.id);
        pr.getParameters().put('id',br.id);
        //pr.getParameters().put('retURL',br.id);
        Test.setCurrentPage(pr);
        MFS_BusinessAtRiskRedirectController BAR = new MFS_BusinessAtRiskRedirectController(new ApexPages.StandardController(br));
        Pagereference redirect = BAR.redirect();
        Pagereference redirectDetail = BAR.redirectDetail();
        //SONAR FIX
        system.assertNotEquals(null, redirectDetail.getUrl());
    }
}