src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Account ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Start_Date__c</fullName>
        <label>Account Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Termination_Date__c</fullName>
        <label>Account Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Code__c</fullName>
        <formula>Portfolio__r.Portfolio_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Investments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <formula>TEXT(Portfolio__r.Vehicle__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Portfolio_Code__c</fullName>
        <formula>Client_Investment__r.Portfolio__r.Portfolio_Code__c</formula>
        <label>Portfolio Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Investments_Needing_Service__c.object
<CustomObject>
    <description>Junction obj so users can access Investments  from Case</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <formula>Investment__r.Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Client Investments Needing Services</relationshipLabel>
        <relationshipName>Investments_Needing_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investment</label>
        <referenceTo>Account__c</referenceTo>
        <relationshipLabel>Client Investments Needing Services</relationshipLabel>
        <relationshipName>Investments_Needing_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Client Investments Needing Services</relationshipLabel>
        <relationshipName>Client_Investments_Needing_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Code__c</fullName>
        <formula>IF(ISBLANK(Investment__r.Portfolio__r.Portfolio_Code__c ), &apos;&apos;,Investment__r.Portfolio__r.Portfolio_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolios__c</fullName>
        <formula>Investment__r.Portfolio__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <formula>IF(ISBLANK(TEXT(Investment__r.Portfolio__r.Vehicle__c) ), &apos;&apos;, TEXT(Investment__r.Portfolio__r.Vehicle__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <label>Client Investments Needing Service</label>
    <nameField>
        <displayFormat>InS{0000}</displayFormat>
        <label>Investments Needing Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments Needing Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <fields>
        <fullName>Plan_ID__c</fullName>
        <description>Data pulled from Maverick (Plan ID)</description>
        <externalId>true</externalId>
        <label>Plan ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Plan_Start_Date__c</fullName>
        <label>Plan Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Termination_Date__c</fullName>
        <description>Data pulled from Maverick</description>
        <label>Plan Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>data Pulled from Maverick</description>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>401(k) Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Allocation Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Benefit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Contribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Contribution (covers deferred Compensation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund of Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HSA - Health Savings Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual/Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Retirement Account (IRA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance General Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Unit Linked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Variable Annuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Variable Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Seed Money</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monetary Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuclear Decommission Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Retail Account</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PMAPS__c.object
<CustomObject>
    <description>Used to track and manage external correspondences including, but not limited to: RFP, RFI, 15C.  Integrates with PMAPS WebPro.</description>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deferred Compensation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Benefit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Contribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance - General Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuclear Decommissioning Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised (40 Act)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit Linked Insurance Plan (ULIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEBA</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RFPs</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFP</label>
    <nameField>
        <displayFormat>RFP-{0000}</displayFormat>
        <label>RFP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Portfolio_Code__c</fullName>
        <description>The unique three character acronym assigned to the portfolio.</description>
        <externalId>true</externalId>
        <inlineHelpText>This will field will contain unique three character acronym assigned to the portfolio.</inlineHelpText>
        <label>Portfolio Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman CFC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Portfolio</fullName>
        <active>true</active>
        <label>Portfolio</label>
    </recordTypes>
</CustomObject>

src/classes/MFS_ServiceRequestRelatedListController.cls
public class MFS_ServiceRequestRelatedListController {
    private Case cse;
    private Id caseId;
    private id accountId;
    public List<PlanWrapper> planList{get;set;}
    public List<InvestmentWrapper> investmentList{get;set;}
    public Map<String, List<InvestmentWrapper>> investmentMap { get; set; }
    private Set<Id> selectedIds;
    public MFS_ServiceRequestRelatedListController(ApexPages.StandardController controller){
        
        Id recId = ApexPages.currentPage().getParameters().get('id');
        if(recId != null && recId.getSobjectType().getDescribe().getName() == 'Case'){
            caseId = recId;
        }
        else{
            PMAPS__c pmaps = [select id, service_request__c from PMAPS__C where id = :recId];
            if(pmaps.service_request__c != null){
                caseId = pmaps.service_request__c;
            }
        }
        Case[] caseList = [select id, accountId from Case where id = :caseId];
        if(caseList != null && caseList.size() > 0){
            accountId = caseList[0].accountId;
        }
        getRelatedRecords();
    }
    
    
	public void getRelatedRecords(){
        try{
            selectedIds = new Set<Id>();
            planList = new List<PlanWrapper>();
            investmentList = new List<InvestmentWrapper>();
            List<InvestmentWrapper> invList;
            investmentMap = new Map<String, List<InvestmentWrapper>>();
            List<Investments_Needing_Service__c> plnList = [select id, Plan__c, Plan__r.Name, Plan__r.Plan_ID__c, Plan__r.Plan_Start_Date__c, Plan__r.Plan_Type__c, Plan__r.Plan_Termination_Date__c 
                                                            from Investments_Needing_Service__c where Case__c = :caseId AND Investment__c = null];
            for(Investments_Needing_Service__c ins : plnList){
                //selectedIds.add(ins.Plan__c);
                planList.add(new PlanWrapper(ins.Plan__r.Name, ins.Plan__c, ins.Plan__r.Plan_Id__c, ins.Plan__r.Plan_Start_Date__c, ins.Plan__r.Plan_Type__c,
                                             ins.Plan__r.Plan_Termination_Date__c, true, ins.Id));
                if(!investmentMap.containsKey(ins.Plan__c)){
                    investmentMap.put(ins.Plan__c, new List<InvestmentWrapper>());
                    system.debug('added from plan=====');
                }
            }
            
            List<Investments_Needing_Service__c> clList = [select id, name, Investment__c, Investment__r.Plan__c, Investment__r.Name, Investment__r.Portfolio__c,Portfolios__c, Portfolio_Code__c, Vehicle__c, Account_Number__c, Investment__r.Account_Start_Date__c, 
                                                           Investment__r.Account_Termination_Date__c from Investments_Needing_Service__c where Case__c = :caseId AND Plan__c = null];
            List<InvestmentWrapper> tempInvestmentList;
            tempInvestmentList = new List<InvestmentWrapper>();
            for(Investments_Needing_Service__c inv : clList){
                if(!investmentMap.containsKey(inv.Investment__r.Plan__c)){
                    investmentMap.put(inv.Investment__r.Plan__c, new List<InvestmentWrapper>());
                    selectedIds.add(inv.Investment__r.Plan__c);
                }
                
                //System.debug(pw.recId+'==='+inv.Investment__r.Plan__c);
                investmentMap.get(inv.Investment__r.Plan__c).add(new InvestmentWrapper(inv.Investment__r.Name, inv.Investment__c, inv.Portfolios__c, inv.Investment__r.Portfolio__c, inv.Portfolio_Code__c, inv.vehicle__c,
                                                                                       inv.Account_Number__c, true, inv.Id));
            }
            //investmentMap.put(pw.recId, tempInvestmentList);
            System.debug('investmentMap before==>'+investmentMap.keySet());
            
            
            List<Plan__c> plansList = [select id, Name, Plan_ID__c, Plan_Start_Date__c, Plan_Type__c, Plan_Termination_Date__c, 
                                       (select id, name, Portfolio__c, Portfolio__r.Name, Portfolio_Code__c, Vehicle__c, Account_ID__c, Account_Start_Date__c, Account_Termination_Date__c from Portfolios__r)
                                       from Plan__c where Organization__c = :accountId ];
            for(Plan__c pln : plansList){
                if(investmentMap.containskey(pln.id) && selectedIds.contains(pln.Id))
                    planList.add(new PlanWrapper(pln.Name, pln.Id, pln.Plan_id__c, pln.Plan_Start_Date__c, pln.Plan_Type__c, pln.Plan_Termination_Date__c, false, null));
            }
            
            
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error while saving the case '+ex.getMessage()+ex.getLineNumber() ));
        }        
    }
    
    public class PlanWrapper{
        //public Plan__c plan { get; set; }
        public String PlanLegalName { get; set; }
        public ID recId { get; set; }
        public String PlanId { get; set; }
        public Date PlanStartDate { get; set; }
        public String PlanType { get; set; }
        public Date PlanTerminationDate { get; set; }
        public Boolean selected { get; set; }
        public Id insId { get; set; }
        public PlanWrapper(String PlanLegalName, ID recId, String planId, Date planStartDate, String planType, Date planTerminationDate, Boolean selected, Id insId ){
            this.planLegalName = planLegalName;
            this.recId = recId;
            this.planId = planId;
            this.planStartDate = planStartDate;
            this.planType = planType;
            this.planTerminationDate = planTerminationDate;
            this.selected = selected;
            this.insId = insId;
        }
    }
    public class InvestmentWrapper{
        //public Account__c investment { get; set; }
        public String investmentName { get; set; }
        public Id recId { get; set; }
        public String portfolio { get; set; }
        public Id portfolioId { get; set; }
        public String portfolioCode { get; set; }
        public String vehicle { get; set; }
        public String accountNumber { get; set; }
        
        public Boolean selected { get; set; }
        public Id insId { get; set; }
        public InvestmentWrapper(String investmentName, Id recId, String portfolio, Id portfolioId, String portfolioCode, String vehicle, String accountNumber, Boolean selected, Id insId){
            this.investmentName = investmentName;
            this.recId = recId;
            this.portfolio = portfolio;
            this.portfolioId = portfolioId;
            this.portfolioCode = portfolioCode;
            this.vehicle = vehicle;
            this.accountNumber = accountNumber;
            this.selected = selected;
            this.insId = insId;
        }
    }
}