src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investments_Needing_Service__c.object
<CustomObject>
    <description>Junction obj so users can access Investments  from Case</description>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investment</label>
        <referenceTo>Account__c</referenceTo>
        <relationshipLabel>Client Investments Needing Services</relationshipLabel>
        <relationshipName>Investments_Needing_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Client Investments Needing Services</relationshipLabel>
        <relationshipName>Client_Investments_Needing_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investments Needing Service</label>
    <nameField>
        <displayFormat>InS{0000}</displayFormat>
        <label>Investments Needing Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments Needing Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PMAPS__c.object
<CustomObject>
    <description>Used to track and manage external correspondences including, but not limited to: RFP, RFI, 15C.  Integrates with PMAPS WebPro.</description>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RFPs</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFP</label>
    <nameField>
        <displayFormat>RFP-{0000}</displayFormat>
        <label>RFP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_ServiceRequestCaseControllerTest.cls
@isTest(seeAllData=false)
public class MFS_ServiceRequestCaseControllerTest {
    public static testMethod void testController(){
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Plan__c plan = MFS_TestDataUtility.createPlan(acc.Id);
        insert plan;
        Plan__c plan2 = MFS_TestDataUtility.createPlan(acc.Id);
        insert plan2;
        List<Product2> prodList = MFS_testDataUtility.createBulkProduct();
        insert prodList;
        List<Account__c> clInvList =  MFS_testDataUtility.createBulkClientInvestment(acc.Id, plan.Id, prodList);
        insert clInvList;
        List<Account__c> clInvList1 =  MFS_testDataUtility.createBulkClientInvestment(acc.Id, plan2.Id, prodList);
        insert clInvList1;
        Contact cont = MFS_testDataUtility.createContact(acc.Id);
        insert cont;
        Case cse = MFS_testDataUtility.createCase(cont);
        insert cse;
        Investments_Needing_Service__c inv = MFS_testDataUtility.createInvestments(cse.Id);
        inv.Investment__c = clInvList[0].Id;
        insert inv;
        Investments_Needing_Service__c pln = MFS_testDataUtility.createInvestments(cse.Id);
        pln.Plan__c = plan.Id;
        insert pln;
        
        Pagereference prf = Page.MFS_ServiceRequestCase;
        Test.setCurrentPage(prf);
        ApexPages.currentPage().getParameters().put('Id', cse.id);
        MFS_ServiceRequestCaseController ctrl = new MFS_ServiceRequestCaseController(new ApexPages.StandardController(cse));
        System.assertEquals(2, ctrl.planList.size());
        System.assertEquals(2, ctrl.investmentMap.size());
        ctrl.closePopup();
        ctrl.save();
        
        ctrl.planList[1].selected = true;
        ctrl.investmentMap.get(plan2.id)[0].selected = true;
        ctrl.save();
        
        PMAPS__c pmap = new PMAPS__c(Service_Request__c=cse.Id, Date_Received__c = System.TODAY(), Date_Due__c = System.TODAY().addDays(10));
        insert pmap;
        
        //Test Case related List
        Pagereference prf1 = Page.MFS_ServiceRequestRelatedList;
        Test.setCurrentPage(prf1);
        ApexPages.currentPage().getParameters().put('Id', cse.id);
        
        //Test Pmaps related List
        MFS_ServiceRequestRelatedListController relatedCtrl = new MFS_ServiceRequestRelatedListController(new ApexPages.StandardController(cse));
        Pagereference prf2 = Page.MFS_ServiceRequestRelatedList;
        Test.setCurrentPage(prf2);
        ApexPages.currentPage().getParameters().put('Id', pmap.id);
        relatedCtrl = new MFS_ServiceRequestRelatedListController(new ApexPages.StandardController(pmap));
    }
}