src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Investments</relationshipLabel>
        <relationshipName>Portfolio2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Distribution_List__c.object
<CustomObject>
    <description>This object captures distribution lists, e.g. email distribution lists.</description>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distribution List</relationshipLabel>
        <relationshipName>Distribution_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Distribution List</label>
    <nameField>
        <label>Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Related Organization</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Portfolios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>NOT( Contact_Relationship_End_Date__c &lt;=  TODAY()) || ISBLANK(Contact_Relationship_End_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>All_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Plans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship_End_Date__c</fullName>
        <label>Relationship End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship_Start_Date__c</fullName>
        <label>Relationship Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related third party primary contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Plan_Account_Relationships_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical_Org_Name__c</fullName>
        <label>Historical Org Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Investment if the plan is unknown</inlineHelpText>
        <label>Client Investment</label>
        <referenceTo>Account__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Relate an Organization to this Plan or Investment if a Contact is unknown.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>$Organization.Country</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Plan_Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Organization Role</label>
        <picklist>
            <picklistValues>
                <fullName>Investment_Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clearing Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custody Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Dilligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_AssociationUtilities.cls
/**
Apex Class Name    : MFS_AssociationUtilities
Version            : 1.0 
Created Date       : Dec. 13 2016
Function           : Utility class that gets called by Plan Association Triggers 
when Associations are created and updated
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Christine Cui             12/13/2016              Original Version
**/

public class MFS_AssociationUtilities {
 
    // Clone the association if the Plan has 3 investments, 2 association records will be created to associate the plan with 2 investments 
    public static List<Plan_Association__c> CloneAssociation(List<Plan_Association__c> newAssocList, Set<Id> AssocId){
        
        // Get the list from trigger parameter
        List<Plan_Association__c> associationsList = new List<Plan_Association__c>([Select 
                                                                                    Active__c,Contact_Relationship_End_Date__c,Contact_Relationship_Start_Date__c,Contact__c,CreatedById,CreatedDate,Contact_Role__c, All_Plans__c,
                                                                                    CRT__c,Distribution_List__c,Historical_Org_Name__c,Investment__c,LastModifiedById,LastModifiedDate,Name,Organization1__c,Organization__c,OwnerId,Plan__c,Role__c FROM Plan_Association__c where Id = :AssocId]);
        List<Plan_Association__c> newassociationsList = new List<Plan_Association__c>();                                                                            
        Set<Id> PlanId = new Set<Id>();
        Set<Id> InvestId = new Set<Id>();   
        List<Account__c> accList = new List<Account__C>();
        
        // Get PlanID and InvestmentID from the list
        try{ 
            if(!newAssocList.isEmpty() && AssocId.size()>0){
                for(Plan_Association__c pac: associationsList) {
                    PlanId.add(pac.Plan__c);
                    InvestId.add(pac.Investment__c);
                }
                
                //Make sure to only get PlanId and Investment not equal to the investment of the original association ID
                If(!associationsList.isEmpty()) {
                    accList=[Select Id, name from Account__c where Plan__c in : PlanId and Id <> :InvestId]; 
 
                    for (Plan_Association__c passo: associationsList){
                        for (Account__c ac: accList){
                            Plan_Association__c pa = passo.clone(false, true);
                            pa.Investment__c = ac.id;
                            newassociationsList.add (pa);
                        }
                    }
                }
            }
        } catch(Exception ex){
            System.debug('Exception occurred '+ex.getMessage());
        }
        return newassociationsList;
    }
    
    // When the association is created, immediately associate the 1st investment id of this plan, in this case, we need to update the the 1st investmentID
    public static List<Plan_Association__c> updateInvestmentId(Map<Id,Plan_Association__c> newAssocList){   
        List<Plan_Association__c> lstAssoUpdate = new List<Plan_Association__c>();
        Set<Id> PlanId = new set<Id>();
        
        List<Plan_Association__c> associationsList = new List<Plan_Association__c>([Select 
                                                                                    Active__c,Contact_Relationship_End_Date__c,Contact_Relationship_Start_Date__c,Contact__c,CreatedById,CreatedDate,
                                                                                    CRT__c,Distribution_List__c,Historical_Org_Name__c,Investment__c,LastModifiedById,LastModifiedDate,Name,
                                                                                    Organization1__c,Organization__c,OwnerId,Plan__c,Role__c FROM Plan_Association__c where Id IN :newAssocList.keyset()]);
        for(Plan_Association__c pa: associationsList){
            //make sure plan is filled in and investment is left blank
            if (pa.Investment__c ==null && pa.plan__c !=null){ 
                PlanId.add(pa.Plan__c);
            }
        }
         //update the 1st investment id of this plan to the association record we just created
        List<Account__c> acList = new List<Account__c>([Select Id from Account__c where Plan__c =: PlanId Order By Id LIMIT 1]);
        for(Account__c a: acList){
            for(Plan_Association__c pa: associationsList) {
                pa.Investment__c = a.Id;
                lstAssoUpdate.add(pa);   
            }
        }
        //return the list to update
        return lstAssoUpdate;
    }
}