src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <description>Reference data field to track contact Role</description>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beneficial Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related third party primary contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Plan_Account_Relationships_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Investment if the plan is unknown</inlineHelpText>
        <label>Client Investment</label>
        <referenceTo>Account__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Relate an Organization to this Plan or Investment if a Contact is unknown.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Plan_Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_AssociationUtilitiesTest.cls
@isTest
public class MFS_AssociationUtilitiesTest {

    public static testMethod void insertupdatePlanAssociationTest()
    {
        List<Account> accts = new List<Account>();
        List<Contact> conts = new List<Contact>();
        List<Product2> pd = new List<Product2>();
        List<Plan__c> pls = new List<Plan__c>();
        List<Account__c> acList = new List<Account__c>();
        List<Plan_Association__c> planAsscn = new List<Plan_Association__c>();
        Account acc1 = MFS_TestDataUtility.createAccount();
        insert acc1;
        accts.add (acc1);
        Contact cont1 = MFS_TestDataUtility.createContact(acc1.id);       
        insert cont1;
        conts.add(cont1);
        Plan__c pl = MFS_TestDataUtility.createPlan(acc1.id); 
        insert pl;
        pd = MFS_TestDataUtility.createBulkPortfolioProduct();
        insert pd;
        List<Product2> prod = [Select Id from Product2 where name like 'testPortfolio%' order by CreatedDate desc LIMIT 3];
        acList = MFS_TestDataUtility.createBulkClientInvestment(acc1.Id, pl.Id, prod);
        insert acList;
        Plan_Association__c planAsscn1 = MFS_TestDataUtility.createPlanAsscnwithPlan(cont1.id, pl.Id);
        planAsscn1.Contact_Role__c='Accounting';
        MFS_Utilities.runReset();
        try{
        insert planAsscn1;
        }catch(Exception e){
           system.debug(e.getMessage()); 
        }
        System.debug('planAsscn1:'+planAsscn1);
        List<Plan_Association__c> pac = [Select Id, name, investment__c from Plan_Association__c where Plan__c =: pl.Id and Contact__c =: cont1.id and 
                                         Organization1__c = : acc1.Id order by CreatedDate desc];
        System.debug('pac:'+pac);
        integer i=0;
        for(Plan_Association__c pa: pac)
        {  i++;
            }
        system.assertEquals(3, i);
}
}