src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID Field</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BAR_Org_Retail_Sales__c.object
<CustomObject>
    <fields>
        <fullName>AUM_AUD__c</fullName>
        <label>AUM - AUD</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_CAD__c</fullName>
        <label>AUM - CAD</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_EUR__c</fullName>
        <label>AUM - EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_GBP__c</fullName>
        <label>AUM_GBP</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_JPY__c</fullName>
        <label>AUM_JPY</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_SGD__c</fullName>
        <label>AUM SGD</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_USD__c</fullName>
        <label>AUM_USD</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_at_Risk__c</fullName>
        <label>Business at Risk</label>
        <referenceTo>Business_at_Risk__c</referenceTo>
        <relationshipLabel>BAR Org Retail Sales</relationshipLabel>
        <relationshipName>BAR_Org_Retail_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <label>MDM_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentage_At_Risk__c</fullName>
        <label>Percentage At Risk</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>BAR Org Retail Sales</label>
    <nameField>
        <displayFormat>BORS-{00000000}</displayFormat>
        <label>BAR Org Retail Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BAR Org Retail Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Business_at_Risk__c.object
<CustomObject>
    <description>This object will contain information to help manage business at risk.</description>
    <fields>
        <fullName>Expected_Loss_Date__c</fullName>
        <inlineHelpText>If Assets were to leave, this is the expected redemption date</inlineHelpText>
        <label>Potential Loss Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business at Risk</relationshipLabel>
        <relationshipName>Business_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_at_Risk__c</fullName>
        <inlineHelpText>Probability of losing the business
High - 75 - 100%
Medium - 50 - 74.99%
Low - 25 - 49.99%
Redeeming - 0 - 24.99%</inlineHelpText>
        <label>Probability of Loss</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeeming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_at_Risk__c</fullName>
        <inlineHelpText>This will contain the reason the business is at risk.</inlineHelpText>
        <label>Reason at Risk</label>
        <picklist>
            <picklistValues>
                <fullName>De-risking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In House Management/ OCIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Client Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebalance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_at_Risk_Date__c</fullName>
        <label>Relationship at Risk Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business at Risk</label>
    <nameField>
        <label>Business at Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Organization_Retail_Sales__x.object
<CustomObject>
    <description>Organization_Retail_Sales</description>
    <externalDataSource>SalesAndAssets</externalDataSource>
    <externalName>Organization_Retail_Sales</externalName>
    <fields>
        <fullName>AUM_AUD__c</fullName>
        <description>AUM_AUD</description>
        <externalDeveloperName>AUM_AUD</externalDeveloperName>
        <label>AUM_AUD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_CAD__c</fullName>
        <description>AUM_CAD</description>
        <externalDeveloperName>AUM_CAD</externalDeveloperName>
        <label>AUM_CAD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_EUR__c</fullName>
        <description>AUM_EUR</description>
        <externalDeveloperName>AUM_EUR</externalDeveloperName>
        <label>AUM_EUR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_GBP__c</fullName>
        <description>AUM_GBP</description>
        <externalDeveloperName>AUM_GBP</externalDeveloperName>
        <label>AUM_GBP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_JPY__c</fullName>
        <description>AUM_JPY</description>
        <externalDeveloperName>AUM_JPY</externalDeveloperName>
        <label>AUM_JPY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_SGD__c</fullName>
        <description>AUM_SGD</description>
        <externalDeveloperName>AUM_SGD</externalDeveloperName>
        <label>AUM_SGD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUM_USD__c</fullName>
        <description>AUM_USD</description>
        <externalDeveloperName>AUM_USD</externalDeveloperName>
        <label>AUM_USD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Level</description>
        <externalDeveloperName>Level</externalDeveloperName>
        <label>Level</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Organization_Retail_Sales</label>
    <pluralLabel>Organization_Retail_Sales</pluralLabel>
</CustomObject>

src/classes/MFS_BusinessAtRiskRetailControllerTest.cls
@isTest(seeAllData=false)
public class MFS_BusinessAtRiskRetailControllerTest {
    static testMethod void fetchBARTest() {
        Business_At_Risk__c br = utility();
        Test.StartTest();
        br.id=null;
        Pagereference prf = Page.MFS_BusinessAtRiskRetail;
        Test.setCurrentPage(prf);
        ApexPages.currentPage().getParameters().put('account', br.Organization__c);
        MFS_BusinessAtRiskRetailController BAR= new MFS_BusinessAtRiskRetailController(new ApexPages.StandardController(br));
        for(Integer i=0; i<3; i++)
        {
            Organization_Retail_Sales__x x = new Organization_Retail_Sales__x(AUM_AUD__c=10.00, Level__c='Product', AUM_CAD__c=10.00, AUM_EUR__c=10.00, AUM_JPY__c=10.00, 
                                                                              AUM_SGD__c=10.00, AUM_USD__c=10.00, AUM_GBP__c=10.00 );
            BAR.portfList.add(x);
        }
        BAR.fetchRelatedLists();
        Test.StopTest();
        BAR.PortFolioLst[0].selected=true;
        Pagereference pr = BAR.save();
        String retUrl = '/apex/mfs_businessatriskretailupdate?id='+br.id+'&type=edit';
        
        system.assertEquals(retUrl.contains('/apex/mfs_businessatriskretailupdate'), pr.getUrl().contains('/apex/mfs_businessatriskretailupdate'));
        System.assertEquals(BAR.isDetail, true);
        
        BAR.selectAll=true;
        BAR.selectAll();
        BAR.selectAll=false;
        BAR.selectAll();
        BAR.changedRow = '1';
        BAR.selectRow();
        BAR.calculateTotalAUMs();
        
        List<Account> accSrchList = MFS_BusinessAtRiskRetailController.queryAccounts('Morgan');
        
        //Test Validation handling
        br.Expected_Loss_Date__c = System.Today()-1;
        update br;
        BAR.save();
        br.Relationship_at_Risk_Date__c = System.today()-1;
        update br;
        BAR.save();
        br.Percentage_at_Risk__c = '';
        update br;
        BAR.save();
        //Test exception blocks
        BAR.bar = null;
        BAR.fetchTotalCurrency();
        BAR.fetchRelatedLists();
        BAR.fetchBARRelatedLists();
        
        //system.assertNotEquals(accSrchList, null);
    }
    
    static testMethod void editBARTest() {
        Business_At_Risk__c br = utility();
        Test.StartTest();
       	Pagereference prf = Page.MFS_BusinessAtRiskRetailUpdate;
        Test.setCurrentPage(prf);
        ApexPages.currentPage().getParameters().put('type', 'edit');
        MFS_BusinessAtRiskRetailController BAR= new MFS_BusinessAtRiskRetailController(new ApexPages.StandardController(br));
        BAR.fetchBARRelatedLists();
        BAR.PortFolioLst[0].selected = true;
        BAR.portfolioLst[0].PercAtRisk = 25;
        br.Expected_Loss_Date__c = System.Today()+1;
        br.Relationship_at_Risk_Date__c = System.today()+1;
        update br;
        Pagereference pr = BAR.updateBAR();
        System.assert(pr!=null);
        BAR.calculateBARTotalAUMs();
        
        List<Account> accSrchList = MFS_BusinessAtRiskRetailController.queryAccounts('Morgan');
        BAR.edit();
        //Test Validation handling
        br.Expected_Loss_Date__c = System.Today()-1;
        update br;
        BAR.updateBAR();
        br.Relationship_at_Risk_Date__c = System.today()-1;
        update br;
        BAR.updateBAR();
        br.Percentage_at_Risk__c = '';
        update br;
        BAR.updateBAR();
        BAR.getFAR();
        BAR.newFAR();
        BAR.getOpenActivities();
        BAR.newTask();
        BAR.newMeeting();
        BAR.getActivityHistories();
        
        BAR.portfolioLst[0].PercAtRisk = null;
        BAR.calculateTotalAUMs();
        BAR.calculateBARTotalAUMs();
        Test.stopTest();
        //system.assertNotEquals(accSrchList, null);
    }
    //create plan portfolio and BAR
    @isTest public static Business_At_Risk__c utility()
    {
        Account acc = MFS_TestDataUtility.createAccount();
        acc.MDM_ID__c = '1234567890';
        
        insert acc;
        User usr = MFS_TestDataUtility.createUser('System Administrator');
        insert usr;
        //SONAR Fix
        System.assertNotEquals(null,usr.Id);
        
        Business_At_Risk__c br = new Business_At_Risk__c();
        br.Organization__c = acc.Id;
        br.Expected_Loss_Date__c = System.Today();
        br.Percentage_at_Risk__c = 'Low';
        br.Expected_Loss_Date__c = System.Today()+1;
        br.Reason_at_Risk__c = 'Regulatory';
        br.Status__c = 'Open';
        insert br;
        List<BAR_Org_Retail_Sales__c> oisLst = new List<BAR_Org_Retail_Sales__c>();
        for(Integer i=1 ; i<4; i++)
        {
            BAR_Org_Retail_Sales__c ois = new BAR_Org_Retail_Sales__c();
            ois.Business_At_Risk__c = br.id;
            ois.AUM_AUD__c = 20.00;
            ois.AUM_CAD__c = 10.00;
            ois.AUM_EUR__c = 5.00;
            ois.AUM_GBP__c = 5.00;
            ois.AUM_JPY__c = 5.00;
            ois.AUM_SGD__c = 5.00;
            ois.AUM_USD__c = 5.00;
            ois.Level__c = 'Product';
            ois.MDM_ID__c = '1234567890';
            oisLst.add(ois); 
            
        }
        insert oisLst;
        return br;
    }
}