src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID Field</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Investments</relationshipLabel>
        <relationshipName>Portfolio2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Investments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Application Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Used for Retail Contacts</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Related Organization</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Portfolios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>All_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Plans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>$Organization.Country</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Plan_Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_ClientInvestmentTriggerTest.cls
@isTest(seeAllData = false)
public class MFS_ClientInvestmentTriggerTest {
    @testSetup
    static void setup(){
        RecordType accRetailRT=[select id, name from RecordType where SObjectType='Account' AND Name = 'Global Retail' LIMIT 1];
        //Custom settings Entries
        List<Application_Settings__c> appSettingsList = MFS_TestDataUtility.getappSettingsList();
        insert appSettingsList;
        Account accRet = MFS_TestDataUtility.createAccount();
        accRet.RecordtypeId = accRetailRT.Id;
        accRet.MDM_ID__c = 'RET12345678';
        insert accRet;
        Contact con = MFS_TestDataUtility.createContact(accRet.Id);
        insert con;
        Plan__c plan = MFS_TestDataUtility.createPlan(accRet.Id);
        insert plan;
        Plan_Association__c planAsso = MFS_TestDataUtility.createPlanAsscnwithPlan(con.Id, plan.Id);
        planAsso.All_Plans__c = true;
        insert planAsso;
        List<Product2> prodList = MFS_TestDataUtility.createBulkProduct();
        insert prodList;
        List<Account__c> clInvList = MFS_TestDataUtility.createBulkClientInvestment(accRet.Id, plan.Id,prodList);
        MFS_Utilities.runReset();
        insert clInvList;
    }
    static testmethod void testClientInvestmentTrigger(){
        Account acc = [select Id from Account where Name = 'TestAccount' and MDM_ID__c = 'RET12345678'];
        List<Account__c> clInvstList = [select Id, Name, Organization__c, Portfolio__c from Account__c where organization__c =: acc.Id ];
        MFS_Utilities.runReset();
        delete clInvstList;
        clInvstList = [select Id, Name, Organization__c, Portfolio__c from Account__c where organization__c =: acc.Id ];
        //SONAR Fix
        system.assert(clInvstList.size() == 0 );
        
    }
    
}