src/objects/Account__c.object
<CustomObject>
    <description>Investment is used to manage how clients invest with MFS, which links to Portfolios, Organizations, and Plans.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Plan/Portfolio</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Investment</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Distribution_List__c.object
<CustomObject>
    <description>This object captures distribution lists, e.g. email distribution lists.</description>
    <label>Distribution List</label>
    <nameField>
        <label>Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Provides structure for displaying Plan Data as related to Organizations</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>All_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Plans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related third party primary contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Plan_Account_Relationships_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Historical_Org_Name__c</fullName>
        <label>Historical Org Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Investment if the plan is unknown</inlineHelpText>
        <label>Client Investment</label>
        <referenceTo>Account__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Relate an Organization to this Plan or Investment if a Contact is unknown.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipName>Plan_Account_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Organization Role</label>
        <picklist>
            <picklistValues>
                <fullName>Investment_Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clearing Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custody Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Dilligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_ClientInvestmentHandler.cls
/**
Apex Class Name    : MFS_ClientInvestmentHandler
Version            : 1.0 
Created Date       : Feb. 17, 2017
Function           : Handler class that gets called by Client Investment Triggers 
Modification Log   :
-----------------------------------------------------------------------------
* Developer	Date		Description
* ----------------------------------------------------------------------------                 
* Alex Gomez	02/17/2017	Original Version
**/

public class MFS_ClientInvestmentHandler
{
    public static void afterInsertClientInvestmentHandler(List<Account__c> accountList, Map<id,Account__c> mapNewAccount)
    {
      // Get a list of all of the plan ID's in the new client investments
      List<id> planIds = new List<id>();
      for (Account__c a: accountList)
      {
          if (a.Plan__c != null)
          {
              planIds.add(a.Plan__c);
          }
      }

      // Now select the associations and put in a map keyed by plan
      Map<id, List<Plan_Association__c>> allAssociationsByPlanID = new Map<id, List<Plan_Association__c>>();
      for (Plan_Association__c pa : [select id, All_Plans__c, Investment__c, Contact__c, Contact_Role__c, CRT__c, 
                                                  		 Distribution_List__c, Historical_Org_Name__c, Organization1__c, Role__c, Plan__c 
                                                  from Plan_Association__c 
                                                  where Plan__c IN :planIds and All_Plans__c = true])
      {
          if (!allAssociationsByPlanID.containsKey(pa.Plan__c))
          {
              allAssociationsByPlanID.put(pa.Plan__c, new List<Plan_Association__C>());
          }
          
          allAssociationsByPlanID.get(pa.Plan__c).add(pa);
      }

	  // If there are no new plan associations then just return
	  if (allAssociationsByPlanID.isEmpty())
	  {
		return;
	  }
	  
      List<Plan_Association__c> newAssocs = new List<Plan_Association__c>();
      //Loop through all of the newly added client investments:
      for (Account__c a: accountList)
      {
          if (null == a.Plan__c)
          {
              continue;
          }
          
          List<Plan_Association__c> acctAssociations = allAssociationsByPlanID.get(a.Plan__c);
          for (Plan_Association__c assoc: acctAssociations)
          {
              Plan_Association__c planAssociation = new Plan_Association__c();
              planAssociation.Investment__c = a.Id;
              planAssociation.Plan__c = a.Plan__c;
              planAssociation.All_Plans__c = assoc.All_Plans__c;
              planAssociation.Contact__c = assoc.Contact__c;
              planAssociation.Contact_Role__c = assoc.Contact_Role__c;
              planAssociation.CRT__c = assoc.CRT__c;
              planAssociation.Distribution_List__c = assoc.Distribution_List__c;
              planAssociation.Historical_Org_Name__c = assoc.Historical_Org_Name__c;
              planAssociation.Organization1__c = assoc.Organization1__c;
              planAssociation.Role__c = assoc.Role__c;
              newAssocs.add(planAssociation);
          }
      }
      
      if (newAssocs.size() > 0)
      {
          database.saveResult[] sr = database.insert(newAssocs,false);
      }
  	}
    
	public static void afterDeleteClientInvestmentHandler(List<Account__c> accountListOld, Map<id,Account__c> accountListDelete)
    {
		//if a client investment gets deleted, delete all of the associations with that investment
        try{
		map<id,Account__c> oldAccountMap=accountListDelete;
		list<Plan_Association__c> associationsToDelete = [select id from Plan_Association__c where Investment__c in : oldAccountMap.keyset()];
		delete associationsToDelete; 
        }catch(Exception e){
            system.debug('Exception in afterDeleteClientInvestmentHandler : '+ e.getStackTraceString());
        }
    }
}