src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Reference data for Organization Type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider;Service Provider</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Related_To_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to opportunity</description>
        <label>Related To Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Non-US Retail Onboarding</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Domestic Retail Onboarding</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact_Role__c.object
<CustomObject>
    <description>Custom object for contact role on case, required to bring in Authorized Signer data</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Related Contact</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <description>Reference data field to track contact Role</description>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beneficial Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Institutional</fullName>
        <active>true</active>
        <description>Used for Institutional Contacts</description>
        <label>Institutional</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>For Org to Org relationships</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Providers</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type__c</field>
                <operation>equals</operation>
                <value>Service Provider, Investment Consultant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Mutual Clients</relationshipLabel>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date for the Relationship</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clearing Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Dilligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Asset Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law Firm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Provider</label>
    <nameField>
        <displayFormat>RN-{00000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_NewAccSummary_Test.cls
@isTest
public class MFS_NewAccSummary_Test {
    
    static testmethod void testEmailtemplate()
    {
        Account acct = new Account();
        acct = MFS_TestDataUtility.createAccount();
        Test.StartTest();
        insert acct;
        System.assert(acct != null);
        List<User> userList = new List<User>();
        User demo1 = MFS_TestDataUtility.createUser('Global Institutional Sales');
        userList.add(demo1);
        User demo2 = MFS_TestDataUtility.createUser('System Administrator');
        demo2.UserName = 'unique_test@mfstest.com1';
        userList.add(demo2);
        User demo3 = MFS_TestDataUtility.createUser('Standard User');
        demo3.UserName = 'unique_test@mfstest.com2';
        userList.add(demo3);
        User demo4 = MFS_TestDataUtility.createUser('Global Institutional Sales');
        demo4.UserName = 'unique_test@mfstest.com3';
        userList.add(demo4);
        User demo5 = MFS_TestDataUtility.createUser('Standard User');
        demo5.UserName = 'unique_test@mfstest.com4';
        userList.add(demo5);
        User demo6 = MFS_TestDataUtility.createUser('Standard User');
        demo6.UserName = 'unique_test@mfstest.com5';
        userList.add(demo6);
        User demo7 = MFS_TestDataUtility.createUser('Standard User');
        demo7.UserName = 'unique_test@mfstest.com6';
        userList.add(demo7);
        insert userList;
        
        List<Relationship__c> relationshipList = new List<Relationship__c>();
        Relationship__c rltn1 = new Relationship__c(Type__c='Record Keeper',Relationship__c=acct.Id,Organization__c=acct.Id,Start_Date__c=System.Today());
        relationshipList.add(rltn1);
        Relationship__c rltn2 = new Relationship__c(Type__c='Custody Bank',Relationship__c=acct.Id,Organization__c=acct.Id,Start_Date__c=System.Today());
        relationshipList.add(rltn2);
        Relationship__c rltn3 = new Relationship__c(Type__c='Record Keeper',Relationship__c=acct.Id,Organization__c=acct.Id,Start_Date__c=System.Today());
        relationshipList.add(rltn3);
        insert relationshipList;
        
        Opportunity opp = MFS_TestDataUtility.createOpportunity(acct.Id);
        insert opp;
        System.assert(opp != null);
        List<Contact> contactList = new List<Contact>();
        Contact cont1 = MFS_TestDataUtility.createContact(acct.id);
        cont1.Contact_role__c = 'Transition Manager';
        contactList.add(cont1);
        Contact cont2 = MFS_TestDataUtility.createContact(acct.id);
        cont2.Contact_role__c = 'ACS Distributor';  
        contactList.add(cont2);
        Contact cont3 = MFS_TestDataUtility.createContact(acct.id);
        cont3.Contact_role__c = 'Sales Person';  
        contactList.add(cont3);
        Contact cont4 = MFS_TestDataUtility.createContact(acct.id);
        cont4.Contact_role__c = 'Transition Manager';
        contactList.add(cont4);
        Contact cont5 = MFS_TestDataUtility.createContact(acct.id);
        cont5.Contact_role__c = 'ACS Distributor'; 
        contactList.add(cont5);
        Contact cont6 = MFS_TestDataUtility.createContact(acct.id);
        cont6.Contact_role__c = 'Sales Person';  
        contactList.add(cont6);
        insert contactList;
        
        Case cse = MFS_TestDataUtility.createCase(cont1);
        cse.Related_To_Opportunity__c = opp.Id;
        insert cse;
        System.assert(cse != null);
        
        List<CaseTeamMember> caseTeamMemList = new List<CaseTeamMember>();
        CaseTeamMember atm1 = new CaseTeamMember(memberId = demo1.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_PM);
        caseTeamMemList.add(atm1);
        CaseTeamMember atm2 = new CaseTeamMember(memberId = demo2.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_RM);
        caseTeamMemList.add(atm2);
        CaseTeamMember atm3 = new CaseTeamMember(memberId = demo3.Id,parentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_IS);
        caseTeamMemList.add(atm3);
        CaseTeamMember atm4 = new CaseTeamMember(memberId = demo4.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_CSM);
        caseTeamMemList.add(atm4);
        CaseTeamMember atm5 = new CaseTeamMember(memberId = userinfo.getuserId(),ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_IS);
        caseTeamMemList.add(atm5);
        CaseTeamMember atm6 = new CaseTeamMember(memberId = demo5.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_PM);
        caseTeamMemList.add(atm6);
        CaseTeamMember atm7 = new CaseTeamMember(memberId = demo6.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_RM);
        caseTeamMemList.add(atm7);
        CaseTeamMember atm8 = new CaseTeamMember(memberId = demo7.Id,ParentId=cse.Id,teamRoleId=System.Label.Case_Team_Role_CSM);
        caseTeamMemList.add(atm8);
        insert caseTeamMemList;
        
        List<Case_Contact_Role__c> caseContRoleList = new List<Case_Contact_Role__c>();
        Case_Contact_Role__c ccr1 = new Case_Contact_role__c(Contact__c=cont1.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr1);
        Case_Contact_Role__c ccr2 = new Case_Contact_role__c(Contact__c=cont2.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr2);
        Case_Contact_Role__c ccr3 = new Case_Contact_role__c(Contact__c=cont3.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr3);
        Case_Contact_Role__c ccr4 = new Case_Contact_role__c(Contact__c=cont4.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr4);
        Case_Contact_Role__c ccr5 = new Case_Contact_role__c(Contact__c=cont5.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr5);
        Case_Contact_Role__c ccr6 = new Case_Contact_role__c(Contact__c=cont6.Id,Case__c=cse.Id);
        caseContRoleList.add(ccr6);
        insert caseContRoleList;
        
        Test.StopTest();
        
        MFS_NewAccSummary eTemplate = new MFS_NewAccSummary();
        eTemplate.CaseId = cse.Id;
        eTemplate.getCaseRec();
        
        Relationship__c rlc = [Select Relationship__r.Name from Relationship__c where Id =: rltn2.Id];
        //System.assertEquals(rlc.Relationship__r.Name, eTemplate.custodyBank);
        
        //exception Coverage
        eTemplate.CaseId = null;
        eTemplate.getCaseRec();
    }
    
    
}