src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Reference data for Organization Type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider;Service Provider</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type1__c</fullName>
        <description>This field is used in User Support Cases</description>
        <inlineHelpText>Depends on &quot;Type&quot;</inlineHelpText>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Service_Request_Type__c</controllingField>
            <picklistValues>
                <fullName>Activities/Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Payee on Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coverage Team Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhance Existing Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhance Existing Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Existing Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Existing Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Audience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge/Unmerge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Report/List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization/Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform Win/Loss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reports and Dashboards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Rule Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Reassignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Update</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Non-US Retail Onboarding</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Domestic Retail Onboarding</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_SubmitHelpTicketExt.cls
/***************************************************************************************************
Apex Class Name    : MFS_SubmitHelpTicketExt
Version            : 1.0 
Created Date       : 7 Oct 2016
Function           : Controller for custom button to create help ticket
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Jata Dubey            10/7/2016              Original Version
***************************************************************************************************/
public with sharing class MFS_SubmitHelpTicketExt {
    Private Account acnt;
    //Constructor
    public MFS_SubmitHelpTicketExt(ApexPages.StandardController controller){
        try{
            acnt = [Select Id,Name from Account where Id =: controller.getRecord().Id];
        } catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
        }
    }
    
    /**
    * @Description : Method used to redirect user to apporipate page based on Account record
    * @Param : N/A
    * @return: Pagereference
    **/  
    public pagereference redirect(){
        List<String> listOfFields=new List<String>{'Requester__c','Account','Type__c','Sub_Type1__c'};
        Pagereference url=new pageReference('/500/e?');
        try{
            Map<String,String> fieldMap=MFS_Utilities.getFieldId('Case',listOfFields);   
            Id caseRecordType=Schema.SObjectType.Case.getRecordTypeInfosByName().get(MFS_AllConstants.Case_TM_RECTYPE).getRecordTypeId();
            url.getParameters().put('returl','/'+acnt.Id);            
           /// url.getParameters().put('recordType','/'+acnt.Id);
            url.getParameters().put(MFS_AllConstants.RECORD_TYPE,caseRecordType);
            url.getParameters().put(fieldMap.get(listOfFields.get(0))+MFS_AllConstants.LK_ID,UserInfo.getUserId());
            url.getParameters().put(fieldMap.get(listOfFields.get(0)),UserInfo.getName());
            url.getParameters().put((fieldMap.get(listOfFields.get(1)))+MFS_AllConstants.LK_ID,acnt.Id);
            url.getParameters().put((fieldMap.get(listOfFields.get(1))),acnt.Name);
            
        } catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
        }
        System.debug('url:'+url);
        return url;
    }
    
}