src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Reference data for Organization Type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect;Client/Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Service Provider;Service Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client/Prospect;Special Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider;Service Provider</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_at_Risk__c.object
<CustomObject>
    <description>This object will contain information to help manage business at risk.</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business at Risk</relationshipLabel>
        <relationshipName>Business_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business at Risk</label>
    <nameField>
        <label>Business at Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_BusinessAtRiskRedirectController.cls
/***************************************************************************************************
Apex Class Name    : MFS_BusinessAtRiskRedirectController
Version            : 1.0 
Created Date       : 12 AUG 2016
Function           : This is a Controller for MFS_BusinessAtRiskRedirect Page
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Ganesh Hegde            08/12/2016              Original Version
***************************************************************************************************/
public with sharing class MFS_BusinessAtRiskRedirectController {
    private static String INSTITUTIONAL = 'Institutional';
    private static String RETAIL = 'Retail';
    private static String RETURL = 'retURL';
    Id accId;
    String url;
    private Business_At_Risk__c bar;
    public MFS_BusinessAtRiskRedirectController(ApexPages.StandardController controller) {
        bar = (Business_at_Risk__c)controller.getRecord();
        url = ApexPages.currentPage().getURL();
    }
    
    //Open Institutional/retail page depending on record type
    public PageReference redirect() {
        try{
            accId=bar.Organization__c;
            
            if(accId==null) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, Label.BAR_Info_Message));
                return null;
            }
            else {
                Account acc = [select recordtypeId from account where id =:accId];
                //Get the current user's profile name
                String profileName=[Select Id,Name from Profile where Id=:userinfo.getProfileId()].Name;
                String currentRecType = [select Name from RecordType where id = :acc.RecordTypeId].Name;
                if(currentRecType.Contains(INSTITUTIONAL)) {
                    return new PageReference( '/apex/MFS_BusinessAtRisk?account='+accId);
                }
                else if(currentRecType.Contains(RETAIL)) {
                    return new PageReference( '/apex/MFS_BusinessAtRiskRetail?account='+accId);
                }
                else{
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, Label.BAR_Info_Message2));
                    return null;
                }
            }
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.Generic_Error));
            return null; 
        }
    }
    
    //Redirect to correct page when detail link is clicked
    public PageReference redirectDetail() {
        //Get the record type
        try{
            Business_At_Risk__c barType = [select type__c from Business_At_Risk__c where id=:bar.id];
            if(barType!=null && barType.type__c==INSTITUTIONAL) {
                if(url.containsIgnoreCase(RETURL))
                    return new PageReference( '/apex/MFS_BusinessAtRiskUpdate?id='+bar.id+'&type=edit');
                else
                    return new PageReference( '/apex/MFS_BusinessAtRiskUpdate?id='+bar.id);
            }
            else {
                if(url.containsIgnoreCase(RETURL))
                    return new PageReference( '/apex/MFS_BusinessAtRiskRetailUpdate?id='+bar.id+'&type=edit');
                else
                    return new PageReference( '/apex/MFS_BusinessAtRiskRetailUpdate?id='+bar.id);
            }
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.Generic_Error));
            return null;
        }
    }
}