src/objects/AcctTeamAppCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains AccountTeamApproval field Ids</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>AccountName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin_Profile_Id__c</fullName>
        <label>Admin Profile Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Approval__c</fullName>
        <label>RecordType_Approval</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Removal__c</fullName>
        <label>RecordType_Removal</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <label>Team Member</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member_lkid__c</fullName>
        <label>Team Member_lkid</label>
        <length>23</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>editUrl__c</fullName>
        <label>editUrl</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AcctTeamAppCustomSettings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Coverage_Team__c.object
<CustomObject>
    <description>Contact Coverage Team is used to track the team that manages the Contact</description>
    <label>Contact Coverage Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Coverage Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Coverage Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <description>This will serve as the junction object to tie Contacts with Teams.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_RequestToJoinMFSTeam_Test.cls
@isTest(SeeAllData=false)
public class MFS_RequestToJoinMFSTeam_Test {

     static testmethod void testRedirect()
    {
        Test.startTest();
       
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Contact contactRec=MFS_TestDataUtility.createContact(accRec.Id);
        insert contactRec;
         List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Case','Contact','Contact'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Case','Subject','Subject'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Case','Organization','Account'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Case','Team Member','Team_Member__c'));
        //fieldIds.add(MFS_TestDataUtility.createFieldIDData('Case','Organization','Account'));
        insert fieldIds;
        
        AcctTeamAppCustomSettings__c accSettings  = new AcctTeamAppCustomSettings__c(name='Default',AccountId__c='',AccountName__c='',Admin_Profile_Id__c='',
                                                                                    editUrl__c='',RecordType_Approval__c='',RecordType_Removal__c='',
                                                                                    Requester__c='',Team_Member__c='',Team_Member_lkid__c='');
        insert accSettings;
        
        List<Coverage_Team__c> coverageList = new List<Coverage_Team__c>{new Coverage_Team__c()};
        PageReference pageRef = Page.MFS_RequestToJoinMFSTeam;
        pageRef.getParameters().put('Id',contactRec.Id);
        Test.setCurrentPage(pageRef);
        MFS_RequestToJoinMFSTeam coverageRequest=new MFS_RequestToJoinMFSTeam(new ApexPages.StandardSetController(coverageList));   
        PageReference pageURL=coverageRequest.redirect();    
        System.assert(pageURL!=null);             
        Test.stopTest();
    }
    
    
}