src/objects/AcctTeamAppCustomSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains AccountTeamApproval field Ids</description>
    <fields>
        <fullName>RecordType_Approval__c</fullName>
        <label>RecordType_Approval</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <label>Team Member</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AcctTeamAppCustomSettings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account Setup Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Allocation Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benchmark Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian/Record Keeper Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Diligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IMA Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow/Outflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inv. Strategy Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inv. Strategy Guideline Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Entity Name Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issue/Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group/List Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Enhancement Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>How-to/Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type1__c</fullName>
        <description>This field is used in User Support Cases</description>
        <inlineHelpText>Depends on &quot;Type&quot;</inlineHelpText>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Service_Request_Type__c</controllingField>
            <picklistValues>
                <fullName>Activities/Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Payee on Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coverage Team Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhance Existing Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhance Existing Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Existing Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Existing Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Audience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge/Unmerge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Report/List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization/Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform Win/Loss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reports and Dashboards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Rule Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Reassignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Update</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <description>This will serve as the junction object to tie Contacts with Teams.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_RequestToJoinMFSTeam.cls
/***************************************************************************************************
Apex Class Name    : MFS_RequestToJoinMFSTeam 
Version            : 1.0 
Created Date       : 10 August 2016
Function           : Class is used to prepopulate fields click of 'Request to Join MFS Team' button from contact related list
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Priya Gupta               10/08/2016              Original Version
***************************************************************************************************/

public with sharing class MFS_RequestToJoinMFSTeam {
    //Constructor
    public MFS_RequestToJoinMFSTeam(ApexPages.StandardSetController stdCtrl){
        
    }
    
    /**
    * @Description : Method is used to construct URL for redirection
    * @Param : N/A
    * @return: PageReference
    **/     
    public PageReference redirect(){
        PageReference pageRef=new PageReference('/500/e');
        try {
            AcctTeamAppCustomSettings__c settings = AcctTeamAppCustomSettings__c.getinstance('Default');    
            Contact contactRec=[Select id,Name,Account.Id,Account.Name from Contact where id=:ApexPages.currentPage().getParameters().get('id')];          
            Id caseRecordType=Schema.SObjectType.Case.getRecordTypeInfosByName().get(MFS_AllConstants.Case_TM_RECTYPE).getRecordTypeId();
            List<String> listOfFields=new List<String>{'Contact','Subject','Account','Team_Member__c','Requester__c','Service_Request_Type__c','Sub_Type1__c'};
                Map<String,String> fieldMap=MFS_Utilities.getFieldId('Case',listOfFields);           
            pageRef.getParameters().put(MFS_AllConstants.RETURN_URL,contactRec.Id);
            pageRef.getParameters().put(MFS_AllConstants.RECORD_TYPE,string.valueof(settings.RecordType_Approval__c));
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(0)),contactRec.Name);
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(0))+MFS_AllConstants.LK_ID,contactRec.Id);
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(1)),Label.Territory_Management_Request);
            pageRef.getParameters().put((fieldMap.get(listOfFields.get(2)))+MFS_AllConstants.LK_ID,contactRec.Account.Id);
            pageRef.getParameters().put((fieldMap.get(listOfFields.get(2))),contactRec.Account.Name);
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(3))+MFS_AllConstants.LK_ID,UserInfo.getUserId());
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(3)),UserInfo.getName());
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(4))+MFS_AllConstants.LK_ID,UserInfo.getUserId());
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(4)),UserInfo.getName());
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(5)),System.Label.CT_Choose_Type);
            pageRef.getParameters().put(fieldMap.get(listOfFields.get(6)),System.Label.CT_Choose_Sub_Type);
        } catch(Exception exe) {
            system.debug('exe:'+exe.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,exe.getmessage()));
        }
        return pageRef;
    }
    
    
}