src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <fields>
        <fullName>Event_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Activity Details</relationshipLabel>
        <relationshipName>Activity_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_An_Orphan_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not An Orphan Record?</label>
        <type>Checkbox</type>
    </fields>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Application Settings</label>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_ActivityDetailBatchTest.cls
@isTest
public class MFS_ActivityDetailBatchTest {
    static testmethod void activityBatchTest()
    {
        
        List<Account> accList = new List<Account>();
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        accList.add(acc);
        Account acc1 = MFS_TestDataUtility.createAccount();
        insert acc1;
        accList.add(acc1);
        User demo = MFS_TestDataUtility.createUser('System Administrator');
        insert demo;
        Activity_Detail__c actDetail = MFS_TestDataUtility.createCallNote(acc.Id);
        actDetail.Not_An_Orphan_Record__c = false;
        insert actDetail;
        DateTime yesterday = DateTime.Now().addDays(-1);
        Test.setCreatedDate(actDetail.Id,yesterday); 
        System.assert(actDetail != null);
        Task tsk = MFS_TestDataUtility.createTask(acc.Id);
        tsk.Activity_Detail__c = actDetail.Id;
        insert tsk;
        Task tsk1 = MFS_TestDataUtility.createTask(acc.Id);
        tsk1.Activity_Detail__c = actDetail.Id;
        insert tsk1;
        Test.startTest();
        List<Event> evntList = new List<Event>();
        List<Event> evnt = MFS_TestDataUtility.createBulkEvents(accList,10);
        insert evnt;
        for(Event event : evnt)
        {
            event.Activity_Detail__c = actDetail.Id;  
            evntList.add(event);
        }
        update evntList;
        List<Event_Request__c> evReqList = new List<Event_Request__c>();
        List<Event_Request__c> evReq = MFS_TestDataUtility.createBulkEventReq(demo.Id);
        insert evReq;
        for(Event_request__c er : evReq)
        {
            er.Call_Note__c = actDetail.Id;
            evReqList.add(er);
        }
        update evReqList;
        System.assert(evReqList != null);
        MFS_ActivityDetailBatch batch = new MFS_ActivityDetailBatch();
        batch.query ='Select id,CreatedDate from Activity_Detail__c where Not_An_Orphan_Record__c = false';
        Id batchProcessId = Database.executeBatch(batch);
        System.assert(batchProcessId != null);
        MFS_ActivityDetailBatchSchedule sh = new MFS_ActivityDetailBatchSchedule();
        string sch = '0 0 23 * * ?';
        system.schedule('Test Recurring Schedule',sch,sh);
        Test.stopTest();
        System.assertEquals(database.countquery('select count() from Activity_Detail__c where Not_An_Orphan_Record__c =false'), 0);
    }
    @testSetup
    public static void dataSetup(){
        List<Application_Settings__c> customSettings = MFS_TestDataUtility.getappSettingsList();
        insert customSettings;
    }
}