src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Used for Retail Contacts</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <description>Do not delete..Used for Product search</description>
        <label>Asset Class-Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global ex US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Country - Non US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Fixed Income</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to track unknown strategy</description>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the product can be seen but cannot be sold yet.

OLD: &quot;Portfolio Active Status: Indicates whether a portfolio is Active or Inactive. The status of the portfolio is Active when the fund has assets or is being prepared for funding. The status of the portfolio is Inactive after the termination date. and/or
Portfolio Open Ended Flag: A flag on the portfolio that indicates if it is open or closed ended. When the fund is open ended, shares are created for investor purchase and taken out of circulation for redemption. When the fund is closed ended, a specified number of shares are available for investor purchase.&quot;</description>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman CFC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MFS_RelatedActivitiesControllerTest.cls
@isTest 
public class MFS_RelatedActivitiesControllerTest {
    private static FINAL String RET_EVENT =  'Enhanced Event (Retail)';
    private static FINAL String RET_TASK = 'Log a Call (Retail)';
    static testmethod void RelatedActivitiesInitialLoad(){
        
        //Create account
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        
        //Create Contact
        Contact cont = MFS_TestDataUtility.createContact(acc.id);
        insert cont;
        
        //Create Product
        Product2 prod = MFS_TestDataUtility.createProduct();
        prod.IsActive = true;
        prod.Is_Unknown__c =false;
        prod.Restricted__c=false;
        insert prod;
        
        //Create callNote
        Activity_Detail__c cNote = MFS_TestDataUtility.createCallNote(acc.Id);
        insert cNote;
        //Create Activity360
        Event e = new Event ();
        e.Activity_Detail__c = cNote.id;
        //e.StartDateTime = datetime.NOW();
        //e.EndDateTime = datetime.NOW().addMinutes(30);
        e.ActivityDate = system.Today();
        e.IsAllDayEvent = true;
        e.Method__c = 'In Person Meeting';
        e.Activity_Type_for_Instit__c = 'Finals';
        e.Type = 'Meeting';
        e.whoid = cont.id;
        e.whatid = acc.id;
        e.recordtypeid= Schema.SObjectType.Event.getRecordTypeInfosByName().get(RET_EVENT).getRecordtypeId();
        insert e;
		system.debug('event e='+e);
        //Create callNote
        Activity_Detail__c cNote1 = MFS_TestDataUtility.createCallNote(acc.Id);
        insert cNote1;
        //Create Activity360
        Event e1 = new Event ();
        e1.Activity_Detail__c = cNote1.id;
        e1.StartDateTime = datetime.NOW().addDays(-2);
        e1.EndDateTime = e1.StartDateTime.addMinutes(30);
        e1.Method__c = 'In Person Meeting';
        e1.Activity_Type_for_Instit__c = 'Finals';
        e1.Type = 'Meeting';
        e1.whoid = cont.id;
        e1.whatid = acc.id;
        e1.recordtypeid= Schema.SObjectType.Event.getRecordTypeInfosByName().get(RET_EVENT).getRecordtypeId();
        insert e1;
        
        List<OpenActivity> lstOA = new List<OpenActivity>();
List<ActivityHistory> lstAH = new List<ActivityHistory>();

OpenActivity oa1 = new OpenActivity();
//oa1.ActivityDate = system.Today().addDays(-2);
lstOA.add(oa1);

ActivityHistory ah1 = new ActivityHistory();
//ah1.ActivityDate = system.Today().addDays(-1);
lstAH.add(ah1);
        
Set<Id> setSelectedAttendee = new Set<Id>();
setSelectedAttendee.add(cont.id);
        Set<Id> setSelectedProduct = new Set<Id>();
setSelectedProduct.add(prod.id);
        
        system.debug('select id, (select id from OpenActivities), (select id from ActivityHistories) from Account where id = acc.id'+ [select id, (select id from OpenActivities), (select id from ActivityHistories) from Account where id =: acc.id]);
        
        PageReference pg = Page.MFS_RelatedActivities;
        Test.setCurrentPage(pg);
        ApexPages.currentPage().getParameters().put('id',acc.id);
        Test.startTest();
	MFS_RelatedActivitiesController rac = new MFS_RelatedActivitiesController();
	
        
        
        rac.wSearchKey.timeframe = 'Upcoming 3 Months'; 
        rac.wSearchKey.selectedmethods = '\'In Person Meeting\'';
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '1 Month'; 
        rac.wSearchKey.selectedmethods = '\'Virtual Meeting\'';
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '3 Months'; 
        rac.wSearchKey.selectedmethods = '\'Phone Call\'';
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '6 Months'; 
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '1 Year'; 
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '2 Years'; 
        rac.FilterActivity();
        rac.wSearchKey.timeframe = '3 Years'; rac.FilterActivity();
   	     rac.wSearchKey.timeframe = 'All Time'; 
        rac.wSearchKey.selectedmethods = '';
        rac.FilterActivity();
        rac.init();
        
        //Testing Assigned to selection
        rac.wSearchKey.idAssignedTo = UserInfo.getUserId();
		rac.FilterActivity();
        //Attendee selection test
        rac.OpenAttendeeSearchModal();
        rac.wSearchKey.wAttendees.SearchText = 'test';
        rac.getInviteeSearchObjects();
        rac.SearchObjects = 'Users & Contacts';
        rac.wSearchKey.selectedAttendee = String.valueOf(cont.id);
        rac.wSearchKey.sAttendeeIds.add(cont.id);
        rac.selectedAttendeeHidden = cont.Id;
        rac.searchInvitee();
        rac.reset();
        rac.wSearchKey.selectedAttendee = String.valueOf(cont.id);
        rac.addSeletedAttendees();
        rac.wSearchKey.selectedAttendee = String.valueOf(cont.id);
        rac.wSearchKey.sAttendeeIds.add(cont.id);
        rac.FilterActivity();
        
        
        //Product selection tests
        rac.OpenProductSearchModal();
        rac.wSearchKey.product.Name='testProduct';
		rac.wSearchKey.product.Vehicle__c = 'Domestic Mutual Fund'; 
		rac.wSearchKey.product.Asset_Class_Geography__c='Emerging Markets (diversified) Equity';
    	rac.searchProduct();
        rac.addSeletedProduct();
        rac.wSearchKey.selectedProduct = prod.id;
        rac.FilterActivity();
        
		rac.mergeSortActivities(lstOA, lstAH, TRUE);
        rac.checkIfSelectedAttendeeMatching(setSelectedAttendee, cNote );
        rac.checkIfSelectedProductMatching(setSelectedProduct, cNote );
        
        MFS_RelatedActivitiesController.queryPortfolios('keyword');
            MFS_RelatedActivitiesController.queryContacts('keyword');
            MFS_RelatedActivitiesController.queryUsers('keyword');
        
        //Exception tests
        rac.wlSearchedProducts = NULL;
        rac.searchProduct();
        rac.wSearchKey.sProductIds = NULL;
        rac.addSeletedProduct();
        rac.wSearchKey.sAttendeeIds = NULL;
		rac.addSeletedAttendees();
        Test.stopTest();
    }
}