src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Meeting_Material_Request__c.object
<CustomObject>
    <description>Used to track &amp; manage distribution lists</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <label>Activity Detail</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipLabel>Meeting Material Requests</relationshipLabel>
        <relationshipName>Meeting_Material_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Prospect_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Material Requests</relationshipLabel>
        <relationshipName>Meeting_Material_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Due_to_Client__c</fullName>
        <label>Date Due to Client</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Material_Type__c</fullName>
        <label>Material Type</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client - CRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client - PRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introductory Transition Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRP Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRP Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic/Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinar</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Material Request</label>
    <nameField>
        <label>Meeting Material Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Material Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_MMRTriggerHandlerTest.cls
@isTest(seeAllData = false)
public class MFS_MMRTriggerHandlerTest {
    public static testMethod void testMeetingMaterialRequest(){
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Activity_Detail__c cNote = MFS_TestDataUtility.createCallNote(acc.Id);
        insert cNote;
        AccountTeamMember atm = new AccountTeamMember(userId = UserInfo.getUserId(), accountId = acc.id, teamMemberRole = 'Client Service Coordinator');
        insert atm;
        //SONAR Fix
        system.assertNotEquals(null,atm.Id);
        //Test exception block and delete the MMR
        Meeting_Material_Request__c MMR = new Meeting_Material_Request__c(Name = 'MMRTest',Call_Note__c = cNote.Id, Client_Prospect_Name__c = acc.Id, Date_Due_to_Client__c = System.TODAY(), Material_Type__c = 'Client');
        insert MMR;
        delete MMR;
        Contact cont = MFS_TestDataUtility.createContact(acc.id);
        insert cont;
        MMR = new Meeting_Material_Request__c(Name = 'MMRTest',Call_Note__c = cNote.Id, Client_Prospect_Name__c = acc.Id, Date_Due_to_Client__c = System.TODAY(), Material_Type__c = 'Client');
        insert MMR;
    }
}