src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <fields>
        <fullName>Event_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Activity Details</relationshipLabel>
        <relationshipName>Activity_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Types__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dealer Conference - National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Conference - Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Diligence Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Introduction/Strategy Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media / PR Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-firm Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio/Strategy Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roadshow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner Event/Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Due Diligence</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Overall_Approval_Status__c</fullName>
        <label>Overall Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Floor visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Request</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_Name__c</fullName>
        <label>Speaker Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeZone__c</fullName>
        <label>Timezone</label>
        <picklist>
            <picklistValues>
                <fullName>(UTC-06:00) Central time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-05:00) Eastern time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+00:00) Dublin, Edinburgh, Lisbon, London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+08:00) Kuala Lumpur, Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+10:00) Canberra, Melbourne, Sydney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Mountain Time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-08:00) Pacific Time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-12:00) International Date Line West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-11:00) Coordinated Universal Time-11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-10:00) Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-09:00) Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-04:00) Atlantic Time (Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-03:30) Newfoundland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-03:00) Brasilia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-01:00) Azores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+02:00) Athens, Bucharest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:00) Minsk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:30) Tehran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:00) Moscow, St. Petersburg, Volgograd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+04:30) Kabul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:00) Islamabad, Karachi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:45) Kathmandu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+06:00) Dhaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-08:00) Baja California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Chihuahua, La Paz, Mazatlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-06:00) Central America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-06:00) Guadalajara, Mexico City, Monterrey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_SpeakerRequestUtility.cls
/*
Apex class           :  MFS_SpeakerRequestUtility
Version               :  1.0
Created Date          :  16 SEP 2016
Function              :  This Utility class contains all methods related to Speaker Request Related List in Activity360

Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                
* GYANENDRA SINGH          16 SEP 2016              Initial Version
*/

public class MFS_SpeakerRequestUtility {
    
    /*
    ** Method Name     : goToSpeakerRequest
    ** Description     : Method to get all the related Speaker Request records
    ** Used in         : Speaker Request related list (Activity360 page)
    */
    public static List<MFS_Activity360GeneralUtility.wrapperClass> goToSpeakerRequest(id cId, List<MFS_Activity360GeneralUtility.wrapperClass> SpeakerWrapperList){
        List<Event_Request__c> eventRequestList = new List<Event_Request__c>();
        try{
            eventRequestList = new List<Event_Request__c>([select id,Name,Call_Note__c, Overall_Approval_Status__c, Event_Title__c,Event_Types__c,Requester__c,Request_Type__c,TimeZone__c,Speaker_Name__c,Visit_Date__c
                                                           from Event_Request__c where id = :cId]);
            SpeakerWrapperList.clear();
            for(Event_Request__c ev : eventRequestList ){
                SpeakerWrapperList.add(new MFS_Activity360GeneralUtility.wrapperClass(ev,false));
            } 
        } catch(Exception ex){
            system.debug('Exception in goToSpeakerRequest : '+ex.getStackTraceString());
            throw ex;
        }
        return SpeakerWrapperList;
    }
    
    /*
    ** Method Name     : updateSpeakerRequest
    ** Description     :  Method to update the Speaker Request 
    ** Used in         : Save button in Speaker Request PopUp screen after clicking Global Save (Activity360 page)
    */
    public static void updateSpeakerRequest(Event_Request__c speakerRequest,List<MFS_Activity360GeneralUtility.wrapperClass> SpeakerWrapperList){
        MFS_Activity360GeneralUtility.wrapperClass srwc = new MFS_Activity360GeneralUtility.wrapperClass(speakerRequest,false);
        SpeakerWrapperList.add(srwc);
    }
    
    
    /*
    ** Method Name     : deleteSpeakerRequestRecord
    ** Description     :  Method to remove the Speaker Request 
    ** Used in         :  remove hyperlink in Speaker Request Related List (Activity360 page)
    */    
    public static void deleteSpeakerRequestRecord( string individualChildRecordId, List<MFS_Activity360GeneralUtility.wrapperClass> SpeakerWrapperList,Activity_Detail__c callNote){
        List<MFS_Activity360GeneralUtility.wrapperClass> tempSpkrReqstTokeepList = new List<MFS_Activity360GeneralUtility.wrapperClass>();
        List<Event_Request__c> tempSpkrReqstToDeleteList = new List<Event_Request__c>();
        try{
            if(SpeakerWrapperList.size()>0 && individualChildRecordId!=null && !string.isBlank(individualChildRecordId)){
                for(MFS_Activity360GeneralUtility.wrapperClass wc:SpeakerWrapperList){
                    if(wc.wSpeakerReq.Id != individualChildRecordId){ tempSpkrReqstTokeepList.add(wc); }
                    if(wc.wSpeakerReq.Id == individualChildRecordId){ tempSpkrReqstToDeleteList.add(wc.wSpeakerReq); }
                }
                
                /* delete only if already the parent event exsists as there is need to add the speaker request in just the memory 
				for the first time when we are creating the parent event which is not saved until global save is hit */
                if(callNote.Id!=null){
                    if(tempSpkrReqstToDeleteList.size()>0){ delete tempSpkrReqstToDeleteList; }
                }
                SpeakerWrapperList.clear();
                SpeakerWrapperList.addAll(tempSpkrReqstTokeepList);
            }
        } catch(Exception ex){
            system.debug('Exception in deleteSpeakerRequestRecord : '+ex.getStackTraceString());
            throw ex;
        }
    }
}