src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <fields>
        <fullName>Event_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Activity Details</relationshipLabel>
        <relationshipName>Activity_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translator_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Translator Required?</label>
        <type>Checkbox</type>
    </fields>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_SendTFTEventToOutlookCtrlTest.cls
@isTest(seeAllData = false)
private class MFS_SendTFTEventToOutlookCtrlTest{
    static testmethod void MFS_SendTFTEventToOutlookCtrlTest(){
        Test.startTest();
        Account acc1 = MFS_TestDataUtility.createAccount();
        insert acc1;
        System.assert(acc1 != null);
        Contact cont1 = MFS_TestDataUtility.createContact(acc1.Id);
        insert cont1;
        Activity_Detail__c actDetail = MFS_TestDataUtility.createCallNote(acc1.Id);
        insert actDetail;
        Event evnt = MFS_TestDataUtility.createEventWithContact(cont1.Id);
        evnt.Activity_Detail__c = actDetail.Id;
        insert evnt;
        Event_Request__c eventReq = new Event_Request__c();
        eventReq.Call_Note__c = actDetail.Id;
        Insert eventReq;
        System.assert(eventReq != null);
                   
        PageReference pref = Page.MFS_SendTFTEventToOutlook;
        test.setCurrentPage(pref);
        MFS_SendTFTEventToOutlookCtrl ctrl = new MFS_SendTFTEventToOutlookCtrl(new ApexPages.StandardController(eventReq));
        eventReq.Translator_Required__c = true;
        update eventReq;
        ctrl = new MFS_SendTFTEventToOutlookCtrl(new ApexPages.StandardController(eventReq));
        Test.stopTest();
    }
}