src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Activity_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Detail</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Call_Note_Competitor_Product__c.object
<CustomObject>
    <description>Junction Object between Competitor Products and Activities</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <label>Call Note</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Competitor_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor Product</label>
        <referenceTo>Competitor_Product__c</referenceTo>
        <relationshipLabel>Competitor Products</relationshipLabel>
        <relationshipName>Call_Note_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor Product and Activity Junction</label>
    <nameField>
        <displayFormat>CNCP-{0000}</displayFormat>
        <label>Competitor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product and Activity Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Competitor_Product__c.object
<CustomObject>
    <description>Competitor Products object will contain competitor product from Morningstar and Evestment.</description>
    <fields>
        <fullName>Firm_Name__c</fullName>
        <label>Firm Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitor Product</relationshipLabel>
        <relationshipName>Competitor_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_High_Interest_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is High Interest Product</label>
        <type>Checkbox</type>
    </fields>
    <label>Competitor Product</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Product</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_CompProductActivityUtility.cls
/*
Apex class           :  MFS_CompProductActivityUtility
Version               :  1.0
Created Date          :  16 SEP 2016
Function              :  This Utility class contains all methods related to MFS Competitor Portfolios Related List in Activity360
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                
* Maheshkumar            16 SEP 2016              Initial Version
*/
public with sharing class MFS_CompProductActivityUtility {
    
    /*
    ** Method Name     : addingCompetitorProduct
    ** Description     :  Method to link the Products to Activity. 
    ** Used in         : search box in MFS Competitor Portfolio related section (Activity360 page)
    */
    public static void addingCompetitorProduct (Set<Id> selectedProductIds, List<MFS_Activity360GeneralUtility.wrapperClass> competitorProdWrapperList, Activity_Detail__c callNote)
    {
        try{
        for (MFS_Activity360GeneralUtility.wrapperClass wExisting:competitorProdWrapperList)
        {   
            if(selectedProductIds!=null && selectedProductIds.contains(wExisting.wCompProduct.id))
                selectedProductIds.remove(wExisting.wCompProduct.id);
        }
        List<Competitor_Product__c> prodList = new List<Competitor_Product__c> ([select id,Name,Firm__c,Firm_Name__c,Is_High_Interest_Product__c from Competitor_Product__c where id In : selectedProductIds]); // Firm__r.Name is replaced with Firm_Name__c on 08/Feb/2017 for UAT Defect
        List<Call_Note_Competitor_Product__c> ProdListToInsert = new List<Call_Note_Competitor_Product__c>();
        for(Competitor_Product__c prd : prodList)
        {
            Call_Note_Competitor_Product__c cnp = new Call_Note_Competitor_Product__c(Call_Note__c = callNote.Id, Competitor_Product__c = prd.Id);
            ProdListToInsert.add(cnp);
        }
        insert ProdListToInsert;
        for(Integer i= 0; i< ProdListToInsert.size(); i++)
        {
            competitorProdWrapperList.add(new MFS_Activity360GeneralUtility.wrapperClass(prodList[i],false));
        }
        }catch(Exception ex){
            system.debug('Exception in addingCompetitorProduct : '+ex.getStackTraceString());
            throw ex;
        }
    }

    /*
    ** Method Name     : removingCompetitorProduct
    ** Description     :  Method to delink the products from Activity.
    ** Used in         : 'remove'hyperlink in MFS Competitor Portfolio related section (Activity360 page)
    */
    public static void removingCompetitorProduct(string individualChildRecordId, Call_Note_Competitor_Product__c oCompProductJN, List<MFS_Activity360GeneralUtility.wrapperClass> competitorProdWrapperList, Activity_Detail__c callNote)
    {
        try{
        if(competitorProdWrapperList != null)
        {
            List<MFS_Activity360GeneralUtility.wrapperClass> lstNotToRemove = new List<MFS_Activity360GeneralUtility.wrapperClass>();
            List<Call_Note_Competitor_Product__c> junObjects;
            if(individualChildRecordId!=null && !string.isBlank(individualChildRecordId)){
                for(MFS_Activity360GeneralUtility.wrapperClass wc:competitorProdWrapperList)
                {
                    if(wc.wCompProduct.id != individualChildRecordId){ lstNotToRemove.add(wc); }   
                }
                junObjects =  new List<Call_Note_Competitor_Product__c>([select id from Call_Note_Competitor_Product__c where Call_Note__c =:callNote.id AND Competitor_Product__r.Id =:individualChildRecordId]);
                delete junObjects;
            }
            competitorProdWrapperList.clear();
            competitorProdWrapperList.addAll(lstNotToRemove);
        } 
        oCompProductJN = new Call_Note_Competitor_Product__c();
        individualChildRecordId = null;
        }  catch(Exception ex){
            system.debug('Exception in removingCompetitorProduct : '+ex.getStackTraceString());
            throw ex;
        }
    }
}