src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Details</relationshipLabel>
        <relationshipName>Activity_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_An_Orphan_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not An Orphan Record?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Call_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Call_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Competitor_Product__c.object
<CustomObject>
    <description>Competitor Products object will contain competitor product from Morningstar and Evestment.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Competitor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Competitor Product</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Product</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Competitor_Product_Opp_Association__c.object
<CustomObject>
    <description>Junction Object between Competitor Products and Opportunities</description>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor Product</label>
        <referenceTo>Competitor_Product__c</referenceTo>
        <relationshipName>Competitor_Product_Opp_Associatis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitor Products</relationshipLabel>
        <relationshipName>Competitor_Product_Opp_Associatis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Competitor_Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Competitor Product to Oppty Junction</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product to Oppty Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Coverage_Team__c.object
<CustomObject>
    <description>Contact Coverage Team is used to track the team that manages the Contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Coverage Team</relationshipLabel>
        <relationshipName>Coverage_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coverage_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coverage Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Coverage_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Coverage Team</relationshipLabel>
        <relationshipName>Contact_Coverage_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Coverage Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Coverage Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Coverage Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DCI_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DCI Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Date__c</fullName>
        <label>Notification Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <label>Asset Class-Geography</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee_Structure__c</fullName>
        <description>If Fee Structure = &apos;Custom&apos; an approval will be required when added</description>
        <label>Fee Structure</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>To show the Asset Name for RBO Opportunity product selection</description>
        <label>Strategy Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Record_Type__c</fullName>
        <label>Product Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Vehicle__c</fullName>
        <label>Vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seperate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <formula>(TEXT((Product2.Geography__c)))&amp;&quot; &quot;&amp;(TEXT(Product2.Asset_Class__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Class-Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <formula>Product2.Is_Unknown__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <formula>if( Product2.RecordType.DeveloperName =&apos;Strategy&apos;, &apos;&apos;,Product2.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Record_Type__c</fullName>
        <formula>IF( Product2.RecordType.DeveloperName =&apos;Portfolio&apos;, &apos;2.Portfolio&apos;,&apos;1.Strategy&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Vehicle__c</fullName>
        <formula>TEXT( Product2.Vehicle__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <formula>Product2.Restricted__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strategy_Name__c</fullName>
        <formula>IF( Product2.RecordType.DeveloperName =&apos;Portfolio&apos;, Product2.Strategy__r.Name, Product2.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strategy Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <description>Do not delete..Used for Product search</description>
        <label>Asset Class-Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global ex US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Country - Non US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Fixed Income</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to track unknown strategy</description>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Record_Type__c</fullName>
        <formula>IF(  RecordType.DeveloperName =&apos;Portfolio&apos;, &apos;2.Portfolio&apos;,&apos;1.Strategy&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the product can be seen but cannot be sold yet.

OLD: &quot;Portfolio Active Status: Indicates whether a portfolio is Active or Inactive. The status of the portfolio is Active when the fund has assets or is being prepared for funding. The status of the portfolio is Inactive after the termination date. and/or
Portfolio Open Ended Flag: A flag on the portfolio that indicates if it is open or closed ended. When the fund is open ended, shares are created for investor purchase and taken out of circulation for redemption. When the fund is closed ended, a specified number of shares are available for investor purchase.&quot;</description>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/MFS_RESUtility.cls
/*
Apex class           :  MFS_RESUtility
Version               :  1.0
Created Date          :  10 NOV 2016
Function              :  This Utility class contains all methods related to RES opportunity
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                
* GYANENDRA SINGH        10 NOV 2016              Initial Version
*/
public with sharing class MFS_RESUtility {
    private static final String TEAM_ROLE_DEFAULT ='Internal Wholesaler';
    private static final String ACCESS_LEVEL = 'Edit';
    //Code to save the RES record
    public static boolean saveRESRecord(Opportunity op, string selectedCoverageTeamMembers, Task parentTask, Event parentEvent, Boolean taskCallNote, Boolean eventCallNote, List<MFS_Activity360GeneralUtility.wrapperClass> taskWrapperList,
                                        Activity_Detail__c callNote, List<MFS_Activity360GeneralUtility.wrapperClass> ProductWrapperList, List<MFS_Activity360GeneralUtility.wrapperClass> competitorProdWrapperList)
    {
        boolean flag = true;  
        Contact con = new Contact();
        try{
            if(op!=null){
                try{
                    insert op;
                    flag = false;
                }
                catch(DMLException e){
                    //return the falg as true if opportunity does not get inserted
                    flag = true;
                }
                if(op.id!=null){
                    
                    Boolean isOpptyProdCreateEnabled = MFS_Utilities.GetAppSettingValue('EnableOpportunityLineItem', 'Yes') == 'Yes' ? true : false;
                    if(isOpptyProdCreateEnabled){
                        //Add all products to opportunity
                        Set<Id> prodIds = new Set<Id>();
                        for(MFS_Activity360GeneralUtility.WrapperClass prdWc : ProductWrapperList)
                        {
                            prodIds.add(prdWc.wProduct.Id);
                        }
                        //Get the pricebook entries where Opportunity currency == pricebook entry currency
                        List<PriceBookEntry> priceBooks = new List<PriceBookEntry>([select id, UnitPrice, isActive, Strategy_Name__c, Portfolio_Name__c,Product_Record_Type__c,
                                                                                    Asset_Class_Geography__c, Product_Vehicle__c, Restricted__c from PricebookEntry where product2.id IN :prodIds and currencyisocode = :op.currencyisocode and Pricebook2.isStandard = true and isActive = true]);
                        List<OpportunityLineItem> oppProdList = new List<OpportunityLineItem>();
                        OpportunityLineItem oppProd;
                        for(PriceBookEntry pbe : priceBooks)
                        {
                            oppProd = new OpportunityLineItem(OpportunityId= op.Id, Product_Name__c=pbe.Strategy_Name__c, Portfolio_Name__c=pbe.Portfolio_Name__c, PriceBookEntryId=pbe.ID, Product_Record_Type__c=pbe.Product_Record_Type__c, Quantity = 1, Asset_Class_Geography__c = pbe.Asset_Class_Geography__c, Restricted__c=pbe.Restricted__c, Fee_Structure__c= MFS_AllConstants.FEE_TYPE_STD, Is_Unknown__c=false, UnitPrice=0);
                            oppProdList.add(oppProd);
                        }
                        if(oppProdList.size() > 0)
                            database.insert (oppProdList,false);
                        
                        //Add all competitor products to opportunity
                        Set<Id> comProdIds = new Set<Id>();
                        List<Competitor_Product_Opp_Association__c> comProdOpptyList = new List<Competitor_Product_Opp_Association__c>();
                        Competitor_Product_Opp_Association__c comProdOpptyJn;
                        for(MFS_Activity360GeneralUtility.WrapperClass comPrdWc : competitorProdWrapperList)
                        {
                            comProdOpptyJn = new Competitor_Product_Opp_Association__c(Competitor_Product__c = comPrdWc.wCompProduct.Id, Opportunity__c = op.Id);
                            comProdOpptyList.add(comProdOpptyJn);
                        }
                        if(comProdOpptyList.size() > 0)
                            insert comProdOpptyList;
                        
                    }
                    if(taskCallNote){
                        if(!String.isEmpty(parentTask.WhoId))
                            con = [Select Id, Name from Contact where Id =:parentTask.WhoId];
                        parentTask.WhatId = op.Id; 
                        upsert parentTask;   
                    }
                    if(eventCallNote){
                        if(!String.isEmpty(parentEvent.WhoId))
                            con = [Select Id, Name from Contact where Id =:parentEvent.WhoId];
                        parentEvent.WhatId = op.Id; 
                        upsert parentEvent;   
                    }
                    if(!string.isEmpty(selectedCoverageTeamMembers)){
                        
                        String sChatterText = System.Label.A360_RES_Chatter_Feed+'';
                        sChatterText = (con.id!=null) ? '@'+con.Name+' '+sChatterText : sChatterText;
                        List<Id> coverageTeamMemberIds = new List<Id>();
                        
                        if(selectedCoverageTeamMembers.contains(',')){
                            List<Id> parts = selectedCoverageTeamMembers.split(',');
                            if(parts.size() > 0){
                                for(Id s : parts){
                                    coverageTeamMemberIds.add(s);
                                }
                            }
                        }
                        else{
                            coverageTeamMemberIds.add(selectedCoverageTeamMembers);  
                        }
                        if(!coverageTeamMemberIds.isEmpty() && coverageTeamMemberIds.size() > 0){
                            boolean success = MFS_ChatterApiUtility.postChatterWithSingleTextMultiMentionAndSingleLink(coverageTeamMemberIds, op.Id, sChatterText, op.Id);
                            addToOpportunityTeam(op, coverageTeamMemberIds);
                        } 
                    }
                    createRESFollowUpTask(op, taskWrapperList, callNote);
                }
            }  
        }
        catch(Exception ex){
            system.debug('Exception in saveRESRecord : '+ex.getStackTraceString());
            throw ex;
        }
        return flag; 
    }
    //Add the Contact's coverage team members to the opportunity team
    public static void addToOpportunityTeam(Opportunity op, List<Id> memberIds){
        List<OpportunityTeamMember> listOfMembers = new List<OpportunityTeamMember>();
        try{
            if(memberIds.size() > 0){
                for(Id mId : memberIds){
                    OpportunityTeamMember otm = new OpportunityTeamMember();
                    otm.OpportunityId = op.Id;
                    otm.OpportunityAccessLevel = ACCESS_LEVEL;
                    otm.TeamMemberRole = TEAM_ROLE_DEFAULT;
                    otm.UserId = mId;
                    
                    listOfMembers.add(otm);
                }
                insert listOfMembers;
            }  
        }
        catch(Exception ex){
            system.debug('Exception in addToOpportunityTeam : '+ex.getStackTraceString());
            throw ex;
        }
    }
    
    //Creates a follow up task if the RES Opportunity record is saved successfully
    public static void createRESFollowUpTask(Opportunity op, List<MFS_Activity360GeneralUtility.wrapperClass> taskWrapperList, Activity_Detail__c callNote){
        try{
           	String oppUpdatedName = [select Name from Opportunity where id = :op.Id].Name;
            Task t = new Task();
            t.OwnerId = op.OwnerId;
            t.Status = MFS_AllConstants.RES_FOLLOW_UP_TASK_DEFAULT_STATUS;
            t.Subject = Label.A360_FOLLOWUP_TASK_SUBJECT_FIELD_DEFAULTVALUE + oppUpdatedName;//op.Name;
            t.ActivityDate = op.Notification_Date__c;
            t.WhatId = op.Id;
            t.recordTypeId =  [select id from RecordType where DeveloperName = 'Log_a_Call_Retail' LIMIT 1].Id;
            if(op.DCI_Lead__c){
                t.Follow_up_Type__c = MFS_AllConstants.FOLLOWUP_TASK_TYPE_FOR_DCILead; 
            }else{
                t.Follow_up_Type__c = MFS_AllConstants.FOLLOWUP_TASK_TYPE_FOR_MIM; 
            }
            Activity_Detail__c ad = new Activity_Detail__c();
            
            ad.Subject__c = t.Subject;
            if(ad.Organization__c == null){ 
                ad.Organization__c= ( !string.isEmpty(t.WhatId) && t.WhatId!=null && (String)((t.WhatId).getSobjectType().getdescribe().getName()) =='Account') ? t.WhatId : Null;
            }
            ad.Contact__c= (!string.isEmpty(t.WhoId) && t.WhoId!=null && (String)((t.WhoId).getSobjectType().getdescribe().getName()) =='Contact') ? t.WhoId : Null;
            ad.Not_An_Orphan_Record__c = true;
            
            upsert ad;
            if(ad.Id!=null){
                t.Activity_Detail__c = ad.Id;
                t.Parent_Activity_Detail_Id__c = callNote.Id;
                t.priority = 'Normal';
                insert t;
                
                if(t.Id!=null){
                    taskWrapperList.add(new MFS_Activity360GeneralUtility.wrapperClass(t, false));  
                }
            }  
        }
        catch(Exception ex){
            system.debug('Exception in createRESFollowUpTask : '+ex.getStackTraceString());
            throw ex;
        }
    }
    
    //Change the Notification Date if the Close Date is changed
    public static void changeDates(Opportunity op){
        try{
            if(op.CloseDate!=null){
                BusinessHours defHours = [select Id,Name from BusinessHours where isDefault =: true];
                
                Long bDiff;
                Long tempDiff;
                Date notificationDate = op.CloseDate - 5;
                op.Notification_Date__c = notificationDate;
                
                DateTime startDate = datetime.newInstance(notificationDate.year(), notificationDate.month(),notificationDate.day());
                DateTime endDate = datetime.newInstance(op.CloseDate.year(), op.CloseDate.month(),op.CloseDate.day());
                
                do{
                    bDiff = BusinessHours.diff(defHours.Id, startDate, endDate);
                    tempDiff = 5 - bDiff;
                    
                    if(tempDiff == 0){
                        op.Notification_Date__c = date.newInstance(startDate.year(),startDate.month(),startDate.day());  
                    }
                    else{
                        startDate = startDate - (Integer)tempDiff;
                    }
                }
                while(tempDiff == 0);
            }
        }
        catch(Exception ex){
            system.debug('Exception in changeDates : '+ex.getStackTraceString());
            throw ex;
        }
        
    }
    
    //This method returns all the values for the Contact's coverage team in JSON format
    public static String getContactCoverageTeamMembers(Task parentTask, Event parentEvent, Boolean taskCallNote, Boolean eventCallNote){
        
        String jSONString;
        JSONGenerator gen = JSON.createGenerator(false);
        
        try{
            gen.writeStartArray();
            
            if(jSONString == null){
                
                if(taskCallNote){
                    if(!String.IsEmpty(parentTask.WhoId) && parentTask.WhoId!=null && ((String)(parentTask.WhoId.getSobjectType().getdescribe().getName()) == 'Contact')){
                        for(Coverage_Team__c ct : [Select Id,Coverage_Owner__r.Name,Coverage_Owner__r.Id,Coverage_Role__c from Coverage_Team__c where Contact__c =: parentTask.WhoId LIMIT 999]){
                            if(ct.Coverage_Owner__r.Id != null){
                                gen.writeStartObject();
                                gen.writeStringField('id', ct.Coverage_Owner__r.Id);
                                gen.writeStringField('label', ct.Coverage_Role__c+': '+ct.Coverage_Owner__r.Name);
                                gen.writeEndObject();
                            }
                        }
                    }
                } 
                
                if(eventCallNote){
                    if(!String.IsEmpty(parentEvent.WhoId) && parentEvent.WhoId!=null && ((String)(parentEvent.WhoId.getSobjectType().getdescribe().getName()) == 'Contact')){
                        for(Coverage_Team__c ct : [Select Id,Coverage_Owner__r.Name,Coverage_Owner__r.Id,Coverage_Role__c from Coverage_Team__c where Contact__c =: parentEvent.WhoId LIMIT 999]){
                            if(ct.Coverage_Owner__r.Id != null){
                                gen.writeStartObject();
                                gen.writeStringField('id', ct.Coverage_Owner__r.Id);
                                gen.writeStringField('label', ct.Coverage_Role__c+': '+ct.Coverage_Owner__r.Name);
                                gen.writeEndObject();
                            }
                        }
                    }
                } 
            }
            
            gen.writeEndArray();
            jSONString = gen.getAsString();  
        }
        catch(Exception ex){
            system.debug('Exception in getContactCoverageTeamMembers : '+ex.getStackTraceString());
            throw ex;
        }
        return jSONString;
    }
    
     public static void removeProductFromRES(string individualChildRecordId, List<MFS_Activity360GeneralUtility.wrapperClass> ProductWrapperListForRES)
    {
        //try{
            if(!ProductWrapperListForRES.isEmpty())
            {
                List<MFS_Activity360GeneralUtility.wrapperClass> lstNotToRemove = new List<MFS_Activity360GeneralUtility.wrapperClass>();
                if(individualChildRecordId!=null && !string.isBlank(individualChildRecordId)){
                    for(MFS_Activity360GeneralUtility.wrapperClass wc: ProductWrapperListForRES)
                    {
                        //create a list of products which are not getting removed
                        if(wc.wProduct.id != individualChildRecordId){ 
                            lstNotToRemove.add(wc); 
                        }   
                    }
                    }
                ProductWrapperListForRES.clear();
                //recreate the product list
                ProductWrapperListForRES.addAll(lstNotToRemove);
            }
        //}catch(Exception ex){
        //    throw ex;
        //}
    }
    
    public static void removeCompProductFromRES(string individualChildRecordId, List<MFS_Activity360GeneralUtility.wrapperClass> compProdWrapperListForRES)
    {
        try{
            if(!compProdWrapperListForRES.isEmpty())
            {
                List<MFS_Activity360GeneralUtility.wrapperClass> lstNotToRemove = new List<MFS_Activity360GeneralUtility.wrapperClass>();
                if(individualChildRecordId!=null && !string.isBlank(individualChildRecordId)){
                    for(MFS_Activity360GeneralUtility.wrapperClass wc: compProdWrapperListForRES)
                    {
                        //create a list of products which are not getting removed
                        if(wc.wCompProduct.id != individualChildRecordId){ 
                            lstNotToRemove.add(wc); 
                        }   
                    }
                    }
                compProdWrapperListForRES.clear();
                //recreate the product list
                compProdWrapperListForRES.addAll(lstNotToRemove);
            }
        }catch(Exception ex){
            system.debug('Exception in removeCompProductFromRES : '+ex.getStackTraceString());
            throw ex;
        }
    }
    
}