src/objects/Activity_Detail__c.object
<CustomObject>
    <description>Junction object to associate child records to an Activity</description>
    <fields>
        <fullName>Event_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Activity Details</relationshipLabel>
        <relationshipName>Activity_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Detail</label>
    <nameField>
        <label>Activity Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

src/objects/Event_Relation__c.object
<CustomObject>
    <description>Junction object between Event Requests and requested speakers.</description>
    <fields>
        <fullName>Activity_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Detail</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipLabel>Event Relations</relationshipLabel>
        <relationshipName>Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Requested Speaker</relationshipLabel>
        <relationshipName>Event_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Slot_End__c</fullName>
        <label>Time Slot End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Slot_Start__c</fullName>
        <label>Time Slot Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event Relation</label>
    <nameField>
        <displayFormat>Speaker-{00000}</displayFormat>
        <label>Requested Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Relation_Portfolio_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Event_Relation__c</fullName>
        <label>Requested Speaker</label>
        <referenceTo>Event_Relation__c</referenceTo>
        <relationshipLabel>Related Portfolios</relationshipLabel>
        <relationshipName>Event_Relation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Event_Relation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Portfolio</label>
    <nameField>
        <label>Related Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_SendEventToOutlookCtrlTest.cls
@isTest
private class MFS_SendEventToOutlookCtrlTest{
    static testmethod void MFS_SendEventToOutlookCtrlTest(){
         Application_Settings__c appSetting= new Application_Settings__c();
        appSetting.Name='EnableDataLoad';
        appSetting.Value__c='Yes';
        insert appSetting;
         Application_Settings__c appSetting1= new Application_Settings__c();
        appSetting1.Name='IntegrationProfileId';
        appSetting1.Value__c=UserInfo.getProfileId();
        insert appSetting1;
       
        Account acc1 = MFS_TestDataUtility.createAccount();
        insert acc1;
        System.assert(acc1 != null);
        Contact cont1 = MFS_TestDataUtility.createContact(acc1.Id);
        insert cont1;
        
        Activity_Detail__c actDetail = MFS_TestDataUtility.createCallNote(acc1.Id);
        insert actDetail;
        Event evnt = MFS_TestDataUtility.createEventWithContact(cont1.Id);
        evnt.Activity_Detail__c = actDetail.Id;
        insert evnt;
        Event_Request__c eventReq = new Event_Request__c();
        eventReq.Call_Note__c = actDetail.Id;
        Insert eventReq;
        System.assert(eventReq != null);
        Event_Relation__c eventRel = new Event_Relation__c();
        eventRel.Speaker_Request__c = eventReq.Id;
        eventRel.Time_Slot_Start__c = DateTime.now();
        eventRel.Time_Slot_End__c = DateTime.now();
        Insert eventRel;
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec;
        System.assert(prodRec != null);
        Event_Relation_Portfolio_Junction__c  junc = new Event_Relation_Portfolio_Junction__c(Portfolio__c=prodRec.Id,Event_Relation__c=eventRel.Id);
        insert junc;
        Test.startTest();           
        PageReference pref = Page.MFS_SendEventToOutlook;
        test.setCurrentPage(pref);
        ApexPages.currentPage().getParameters().put('eventId',eventRel.Id);
        MFS_SendEventToOutlookCtrl ctrl = new MFS_SendEventToOutlookCtrl();
        Test.stopTest();
    }
}