src/objects/Approval_Request__c.object
<CustomObject>
    <description>Object to capture the product and Onboarding  records which requires approval</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportuinty_ProductId__c</fullName>
        <label>Opportuinty ProductId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>Approval Request - {000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MFS_ProductApproval_Test.cls
@isTest
public class MFS_ProductApproval_Test {

    static testmethod void testProductApproval(){
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec; 
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry;  
        OpportunityLineItem oppLI=MFS_TestDataUtility.createOpportunityLineItem(oppRec,pbEntry.Id);
        insert oppLI;
        Test.setCurrentPage(Page.MFS_ProductApprovalPage);
        MFS_ProductApproval prdACtrl = new MFS_ProductApproval(new ApexPages.StandardController(oppRec)); 
        prdACtrl.refreshPage();
        System.assert(prdACtrl.feeAppRec!=null);        
        prdACtrl.toSelect=oppLI.Id;
        prdACtrl.submitForApproval();
        Approval_Request__c feeApprRec=[Select id,Approval_Status__c,RecordTypeId from Approval_Request__c where Opportuinty_ProductId__c=:oppLI.Id];
        Id recordTypeId=Schema.SObjectType.Approval_Request__c.getRecordTypeInfosByName().get('Fee Approval Request').getRecordTypeId();
        System.assert(feeApprRec.RecordTypeId==recordTypeId);
        System.assert(feeApprRec.Approval_Status__c=='Pending');   
        PageReference pageRef=prdACtrl.goBack();
        System.assert(pageRef!=null);  
        Test.stopTest();
    }
}