src/objects/Approval_Request__c.object
<CustomObject>
    <description>Object to capture the product and Onboarding  records which requires approval</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <label>Approver Group</label>
        <picklist>
            <picklistValues>
                <fullName>Client Service Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - AML/KYC Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - Code of Ethics Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Risk Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Transition Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Compliance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFSI - Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-US Questionnaire Approver Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance / Information Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Compliance (Back End) Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Alliance Department Heads Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Equity Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Fixed Income Group</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Follow_ups_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Follow ups Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onboarding_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Onboarding Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>Approval Request - {000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_OnBoardingSendEmail.cls
/***************************************************************************************************
Apex Class Name    : MFS_OnBoardingSendEmail 
Version            : 1.0 
Created Date       : 15 MAY 2016
Function           : Class is Used send Reminder Email to approver.
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Priya Gupta               03/05/2016              Original Version
***************************************************************************************************/

public with sharing class MFS_OnBoardingSendEmail {
    
    public Approval_Request__c appRequest;
    
    //Constructor     
    public MFS_OnBoardingSendEmail(ApexPages.StandardController stdCtrl){
        try {
            appRequest=[Select id,Approval_Status__c,Number_of_Follow_ups_Sent__c,Approver_Group__c,Due_Date__c,Onboarding_Case__r.Id,Owner.FirstName,Owner.LastName
                        from Approval_Request__c where id=:String.escapeSingleQuotes(stdCtrl.getRecord().Id) limit 1];            
        } catch(Exception exe) {
            System.debug('Exception occured:'+exe.getMessage()+exe.getLineNumber());
        }
    }
    
    /**
    * @Description : Method is used to send email to actual approver
    * @Param : N/A
    * @return: PageReference
    **/       
    public PageReference sendReminder(){
        
        PageReference pageRef;
        try {
            if(MFS_AllConstants.APPROVAL_STATUS_PENDING==appRequest.Approval_Status__c){
                ProcessInstanceWorkItem approvalHis=[Select OriginalActorId from ProcessInstanceWorkItem where ProcessInstance.TargetObjectId=:String.escapeSingleQuotes(appRequest.Id)];
                Messaging.SingleEmailMessage email=new Messaging.SingleEmailMessage();
                String[] toAddresses=new String[]{};
                    //Check if approver is a user
                    if(String.valueOf(approvalHis.OriginalActorId).startsWith('005')){
                        toAddresses.add(approvalHis.OriginalActorId);
                    } 
                //Check if approver is a queue
                else if(String.valueOf(approvalHis.OriginalActorId).startsWith('00G')){
                    GroupMember queueMem=[Select UserOrGroupId From GroupMember where GroupId =:approvalHis.OriginalActorId limit 1];
                    //Assuming Queue will always have one public group
                    for(GroupMember groupMem:[Select UserOrGroupId From GroupMember where GroupId =:String.escapeSingleQuotes(queueMem.UserOrGroupId)]){
                        toAddresses.add(groupMem.UserOrGroupId);
                    }                    
                }  
                email.setTargetObjectId(toAddresses[0]);
                email.setSubject(System.Label.OB_ReminderEmailSubject);
                email.setHTMLBody(createEmailBody());
                email.setToAddresses(toAddresses);
                email.setSaveAsActivity(false);
                List<Messaging.SendEmailResult> results= Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
                for(Messaging.SendEmailResult result:results){
                    if(result.isSuccess()){
                        appRequest.Number_of_Follow_ups_Sent__c= appRequest.Number_of_Follow_ups_Sent__c+1;
                    }
                }
                update  appRequest;                
                pageRef= new PageReference(MFS_AllConstants.SLASH + appRequest.ID);
            } else {
                appRequest.addError(System.Label.OB_ApprovalError);
            }
        } catch(Exception exe) {
            System.debug('Exception occured:'+exe.getMessage()+exe.getLineNumber());
            pageRef= new PageReference(MFS_AllConstants.SLASH + appRequest.ID);
        }
        return pageRef;
    }
    
    /**
    * @Description : Method is used to create email boday
    * @Param : N/A
    * @return: String
    **/        
    public String createEmailBody(){
        String detailURL=URL.getSalesforceBaseUrl().toExternalForm()+'/';
        String emailBoday=System.Label.OB_ReminderEmailBody1+' '+appRequest.Approver_Group__c+',<br>';
        emailBoday=emailBoday+System.Label.OB_ReminderEmailBody2+' '+'<a href='+detailURL+appRequest.ID+'>'+System.Label.OB_ReminderEmailBody3+'</a> .';
        emailBoday=emailBoday+System.Label.OB_ReminderEmailBody4+' '+'<a href='+detailURL+appRequest.Onboarding_Case__r.Id+'>'+System.Label.OB_ReminderEmailBody5+'</a>.'+'<br>';
        emailBoday=emailBoday+System.Label.OB_ReminderEmailBody6+appRequest.Due_Date__c+'<br>';
        emailBoday=emailBoday+System.Label.OB_ReminderEmailBody7+'<br><br>';
        emailBoday=emailBoday+System.Label.OB_ReminderEmailBody8+'<br>'+appRequest.Owner.FirstName+' '+appRequest.Owner.LastName;
        System.debug('emailBody:'+emailBoday);
        return emailBoday;
    }
}