src/objects/Approval_Request__c.object
<CustomObject>
    <description>Object to capture the product and Onboarding  records which requires approval</description>
    <fields>
        <fullName>Business_at_Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business At-Risk</label>
        <referenceTo>Business_at_Risk__c</referenceTo>
        <relationshipName>Fee_Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approval Requests</relationshipLabel>
        <relationshipName>Fee_Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>Approval Request - {000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_at_Risk__c.object
<CustomObject>
    <description>This object will contain information to help manage business at risk.</description>
    <label>Business at Risk</label>
    <nameField>
        <label>Business at Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Id__c</fullName>
        <label>Field Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>StoreFieldIds</label>
</CustomObject>

src/classes/MFS_NewFeeApprovalRequestExtnTest.cls
@isTest(seeAllData = false)
public class MFS_NewFeeApprovalRequestExtnTest {
    
    static testMethod void testRedirect(){
        Test.startTest();
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Opportunity opp = MFS_TestDataUtility.createOpportunity(acc.Id);
        insert opp;
        Approval_Request__c appReq = new Approval_Request__c(Opportunity__c=opp.Id);
        List<Approval_Request__c> appReqList = new List<Approval_Request__c>();
        appReqList.add(appReq);
        Business_At_Risk__c bar = MFS_testDataUtility.createBAR(acc.id);
        insert bar;
        StoreFieldIds__c sfId = new StoreFieldIds__c(name='-1914A728127',Field_API_Name__c='Business_At_Risk__c',Field_Id__c='CF00NP0000000smyR',Object_Name__c='Approval_Request__c',Field_Label__c='Business_At_Risk__c');
        insert sfId;
        MFS_NewFeeApprovalRequestExtn hhExtn = new MFS_NewFeeApprovalRequestExtn(new ApexPages.StandardSetController(appReqList));   
        PageReference pr =  new PageReference('/'+bar.id);
        pr.getParameters().put('Id',bar.id); 
        test.setCurrentPage(pr);
        PageReference result = hhExtn.redirect();
        //SONAR Fix
        System.assertNotEquals(null,result.getUrl());
        Test.stopTest();
        
    }
    
}