src/objects/Approval_Request__c.object
<CustomObject>
    <description>Object to capture the product and Onboarding  records which requires approval</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Opportunity__r.Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <label>Approver Group</label>
        <picklist>
            <picklistValues>
                <fullName>Client Service Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - AML/KYC Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - Code of Ethics Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Risk Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Transition Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Compliance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFSI - Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-US Questionnaire Approver Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance / Information Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Compliance (Back End) Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Alliance Department Heads Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Equity Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Fixed Income Group</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Last_Approver_Id__c</fullName>
        <label>Last Approver Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fee_Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onboarding_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Onboarding Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportuinty_ProductId__c</fullName>
        <label>Opportuinty ProductId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>Approval Request - {000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount ($)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>URF_Fee__r.Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Number_of_Approvals_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Approvals Received</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Used to manage the Institutional onboarding process.</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Discount % tbd</description>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/classes/MFS_ApprovalRequestHandler.cls
/***************************************************************************************************
Apex Class Name    : MFS_FeeApprovalRequestHandler
Version            : 1.0 
Created Date       : 6 JUN 2016
Function           : This is a Handler class for FreeApprovalRequestTrigger
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Ganesh Hegde            06/06/2016              Original Version
* Priya Gupta			  15/09/2016			 Updated with 'beforeTriggerEventHandler'
***************************************************************************************************/
public class MFS_ApprovalRequestHandler {
    
    /**
    * @Description :Method is used to calcualte number of approval obtain for an onboarding case
    * @Param : List of Approval_Request__c
    * @return: N/A
    **/
    public static void beforeTriggerEventHandler(List<Approval_Request__c> newList){
        
        Id recordTypeId=Schema.SObjectType.Approval_Request__c.getRecordTypeInfosByName().get(MFS_AllConstants.APPROVAL_ONBOARDING_RT).getRecordTypeId(); 
        Map<Id,Integer> caseDetails =new Map<Id,Integer>();
        for(Approval_Request__c far: newList){
            if(far.RecordTypeId==recordTypeId && far.Approval_Status__c == MFS_AllConstants.APPROVAL_STATUS_APPROVED){
                if(null!=caseDetails.get(far.Onboarding_Case__c)) {
                    caseDetails.put(far.Onboarding_Case__c,caseDetails.get(far.Onboarding_Case__c)+1);
                } else {
                    caseDetails.put(far.Onboarding_Case__c,1);
                }
            }
        }
        
        List<Case> caseToUpdate=[Select Id,Number_of_Approvals_Received__c from Case where Id in : caseDetails.KeySet()];
        for(Case caseRec:caseToUpdate) {
            if(null!=caseRec.Number_of_Approvals_Received__c) {
                caseRec.Number_of_Approvals_Received__c= caseRec.Number_of_Approvals_Received__c+caseDetails.get(caseRec.Id); 
            } else {
                caseRec.Number_of_Approvals_Received__c= caseDetails.get(caseRec.Id);
            }
        }
        
        if(!caseToUpdate.isEmpty()){ 
            Database.Saveresult[] srList = Database.update(caseToUpdate);
            for(Database.SaveResult sr : srList ){
                if(!sr.isSuccess()){
                    for(Database.Error err : sr.getErrors()){
                        system.debug(System.Label.OB_AP_Req_MSG1+err.getMessage());
                    }
                }
            }
        } 
    }
    
    //This method will handle after update events. The method is bulkified.   
    public static void afterTriggerEventHandler(Map<Id, Approval_Request__c> newMap, Map<Id, Approval_Request__c> oldMap ){
        
        List<OpportunityLineItem> oppLinItemsToUpdate = new List<OpportunityLineItem>();
        Map<String, String> oppProdMap = new Map<String, String>();
        Map<String, String> caseProdMap = new Map<String, String>();
        Set<Id> caseId = new Set<Id>();
        //Get the Approval Status and Opportunity Line Item Id from Fee Approval request
        List<Approval_Request__c> feeAppReqLst = new List<Approval_Request__c>([select id, Approver_Group__c, RecordType.DeveloperName, Onboarding_Case__r.RecordType.DeveloperName, Approval_Status__c, Onboarding_Case__c, Amount__c, Discount__c, Last_Approver_Id__c, next_Approver__c, Opportuinty_ProductId__c from Approval_Request__c
                                                                                where Id IN :newMap.keySet()]);	
        //If the approval sttaus is changed, then add the values into a Map
        for(Approval_Request__c far : feeAppReqLst){
            Approval_Request__c newFar = newMap.get(far.id); 
            Approval_Request__c oldFar = oldMap.get(far.id);
            
            if(newFar.Approval_Status__c != oldFar.Approval_Status__c){              

                //Storing the values in a map as there is no relationship between objects
                oppProdMap.put(far.Opportuinty_ProductId__c , newFar.Approval_Status__c );
                if(newFar.Approval_Status__c == MFS_AllConstants.STATUS_APPROVED && newFar.Approver_Group__c == System.Label.OB_Non_US_QAG)
                    caseProdMap.put(newfar.Onboarding_Case__c,newFar.Id);
                if(newFar.Approval_Status__c == MFS_AllConstants.STATUS_APPROVED && Far.Onboarding_Case__r.RecordType.DeveloperName == System.Label.OB_AMM_URF)
                    caseId.add(newfar.Onboarding_Case__c);
            }
            //MFS_ApprovalRequestUtilities.approvalProcessDomestic(caseProdMap);
            //MFS_ApprovalRequestUtilities.approvalProcessAmendment(caseId);
            //Criteria to decide whether the Strategy required Level 2 approval
            if((( newFar.Amount__c >=MFS_AllConstants.APPROVAL_AMT_ZERO && newFar.Amount__c <=MFS_AllConstants.APPROVAL_AMT_50M && newFar.Discount__c >MFS_AllConstants.APPROVAL_AMT_FIVE ) || 
                ( newFar.Amount__c >MFS_AllConstants.APPROVAL_AMT_50M && newFar.Amount__c <=MFS_AllConstants.APPROVAL_AMT_100M && newFar.Discount__c >MFS_AllConstants.APPROVAL_AMT_TEN ) || 
                ( newFar.Amount__c >MFS_AllConstants.APPROVAL_AMT_100M && newFar.Amount__c <=MFS_AllConstants.APPROVAL_AMT_200M && newFar.Discount__c >MFS_AllConstants.APPROVAL_AMT_FIFTEEN ) ||
                (newFar.Amount__c >MFS_AllConstants.APPROVAL_AMT_200M && newFar.Discount__c >MFS_AllConstants.APPROVAL_AMT_TWENTY )) ){
                    /* if(newFar.discount__c != oldFar.discount__c)
                    {
                    far.Approval_status__c = 'Pending';
                    if(oldFar.discount__c!=null)
                    {
                    far.Next_Approver__c=null;
                    
                    }
                    update far;
                    } */
                    if(String.isEmpty(newFar.next_Approver__c)){
                        newFar.addError(System.Label.OB_AP_Req_MSG2);
                    }
                    else if(!String.isEmpty(newFar.next_Approver__c) && (newFar.next_Approver__c!=oldFar.next_Approver__c)){
                        if(far.Last_Approver_Id__c!=null && UserInfo.getUserId().contains(far.Last_Approver_Id__c) ){
                            MFS_ApprovalRequestUtilities.submitForApproval(newFar);
                        } else {
                            newFar.addError(System.Label.OB_AP_Req_MSG3);
                        }
                    }
                }
        }
        MFS_ApprovalRequestUtilities.approvalProcessDomestic(caseProdMap);
            MFS_ApprovalRequestUtilities.approvalProcessAmendment(caseId);
        //Get all Opportunity Line Items which requires status update.
        List<OpportunityLineItem> oppLinItemsLst = new List<OpportunityLineItem> ([select id, Approval_Status__c from OpportunityLineItem
                                                                                   where Id IN : oppProdMap.keySet() ]);
        //Prepare a list of Opportunity Line Items with new status.
        oppLinItemsToUpdate = MFS_ApprovalRequestUtilities.updateLineItemStatus(oppLinItemsLst, oppProdMap);
        Database.Saveresult[] srList = Database.update(oppLinItemsToUpdate,false);
        
        for(Database.SaveResult sr : srList ){
            if(!sr.isSuccess()){
                for(Database.Error err : sr.getErrors()){
                    //we should not through error(object.addError()) here because it will prevent user from approving the record. Hence printing it in debug logs
                    system.debug(System.Label.OB_AP_Req_MSG4+err.getMessage());
                }
            }
        }
    }
}