src/objects/Approval_Request__c.object
<CustomObject>
    <description>Object to capture the product and Onboarding  records which requires approval</description>
    <fields>
        <fullName>AML_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AML Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <label>Approver Group</label>
        <picklist>
            <picklistValues>
                <fullName>Client Service Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - AML/KYC Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance - Code of Ethics Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance - Billing Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Risk Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIS - Transition Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Compliance Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFSI - Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-US Questionnaire Approver Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance / Information Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Compliance (Back End) Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Management Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Alliance Department Heads Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Equity Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading - Fixed Income Group</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Co_Heads_of_Global_Distribution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Heads of Global Distribution</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance - AML/KYC Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_AML_KYC_app_req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance - AML/KYC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance_Billing_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Finance - Billing Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Corporate_Finance_Billing_Approver_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Distribution_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FATCA_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FATCA Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funds_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funds Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GDS_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDS Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fee_Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onboarding_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Onboarding Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>Approval Request - {000000}</displayFormat>
        <label>Approval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AML_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AML Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CFO_Onboarding_Retail_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field used for approval process on a retail onboarding case.</description>
        <label>CFO Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW47t</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Heads_of_Global_Distribution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Retail Onboarding approval process (Amendments)</description>
        <label>Co-Heads of Global Distribution</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW48D</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance - AML/KYC Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_AML_KYC_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliance - AML/KYC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance_Billing_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corp Finance - Billing Group</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Corporate_Finance_Billing_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate Finance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>URF_Fee__r.Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Distribution_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FATCA_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FATCA Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases51</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funds_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funds Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GDS_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approval field for Amendment Process for Retail Onboarding.</description>
        <label>GDS Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW4Bb</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_US_Questionnaire_Approval_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-US Questionnaire Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strategic_Alliance_Department_Heads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strategic Alliance Department Heads</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Retail_Amendment</fullName>
        <active>true</active>
        <businessProcess>Amendment %28URF%29</businessProcess>
        <description>Used to manage the Amendment (URF) process</description>
        <label>Retail Amendment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Discount % tbd</description>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Discount based on set values</description>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/classes/MFS_FeeApprovalRequestUtilitiesTest.cls
/***************************************************************************************************
Apex Class Name    : MFS_FeeApprovalRequestUtilitiesTest
Version            : 1.0 
Created Date       : 16 JUN 2016
Function           : This is a Test class for FreeApprovalRequestTrigger and dependent classes(Handler and Utility)
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Ganesh Hegde            06/16/2016              Original Version
***************************************************************************************************/
@isTest
public class MFS_FeeApprovalRequestUtilitiesTest {
    //Bulk Testing is not required because VF page will insert only one record at a time.
    static testmethod void changStatusTest()
    {
        Test.StartTest();
        try{
            User usr = MFS_TestdataUtility.createUser('System Administrator');
            insert usr;
            
            Account acc = MFS_TestDataUtility.createAccount();
            insert acc;
            Opportunity opp = MFS_TestDataUtility.createOpportunity(acc.Id);
            insert opp;
            Product2 prodRec=MFS_TestDataUtility.createProduct();
            insert prodRec; 
            PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
            insert pbEntry;
            OpportunityLineItem oppLinItem = MFS_TestDataUtility.createOpportunityLineItem(opp.id, pbEntry.id);
            insert oppLinItem;
            Approval_Request__c far = MFS_TestDataUtility.createFeeApprovalRequest(opp.id, oppLinItem.id, usr.Id);
            insert far;
            System.runAs(usr)
            {
                
                Approval_Request__c fee = [select Id,Approval_Status__c,Discount__c,Next_Approver__c from Approval_Request__c where id=:far.id ];
                fee.Approval_Status__c = 'Approved';
                update fee;
                fee.Discount__c=5.00;
                update fee;
                
                OpportunityLineItem oppLI = [select Approval_Status__c from OpportunityLineItem where id= :oppLinItem.id];
                system.assertEquals('Approved', oppLI.Approval_Status__c);
                fee.Next_Approver__c=usr.Id;
                fee.Discount__c=25.00;
                update fee;
                
                
            }
            far.Approval_Status__c = 'Approved';
            far.Approver_Group__c = 'Non-US Questionnaire Approver Group';
            update far;
            
            
        }
        catch(DmlException e)
        {
            String message = e.getMessage();
            
        }
        Test.stopTest();
       }
    
    static testmethod void ApprovalRequestTest(){
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec; 
        Contact cont = MFS_TestDataUtility.createContact(accRec.id);
        insert cont;
        Case caseRec1 = MFS_TestDataUtility.createCase(cont);
        caseRec1.recordtypeid= Schema.SObjectType.Case.getRecordTypeInfosByName().get(MFS_AllConstants.APPROVAL_DOMESTIC_RT).getRecordtypeId();
        caseRec1.Non_US_Questionnaire_Approval_Group__c = true;
        caseRec1.Compliance_AML_KYC__c = true;
        caseRec1.Corporate_Finance__c = true;
        caseRec1.GDS_Acknowledgement__c = userinfo.getUserId();
        caseRec1.Funds_Lawyer__c = userinfo.getUserId(); 
        caseRec1.FATCA_Lawyer__c = userinfo.getUserId();
        caseRec1.Final_Acknowledgement__c = userinfo.getUserId(); 
        caseRec1.Distribution_Lawyer__c = userinfo.getUserId();
        caseRec1.AML_Lawyer__c = userinfo.getUserId();
        insert caseRec1;
        MFS_DomesticCaseApprovalCtrl caseCtrl=new MFS_DomesticCaseApprovalCtrl(new ApexPages.StandardController(caseRec1));  
        PageReference pageRef=caseCtrl.submitForApproval();
        System.assert(pageRef!=null);
        Approval_Request__c appr = [Select Approval_status__c from Approval_Request__c where Onboarding_case__c =: caseRec1.Id];
        appr.Approval_Status__c = 'Approved';
        update appr;
        
        Case caseRec = MFS_TestDataUtility.createCase(cont);
        RecordType rt = [select id from RecordType where DeveloperName='Retail_Amendment' and SobjectType='Case' LIMIT 1];
        caseRec.recordtypeid= rt.Id;//Schema.SObjectType.Case.getRecordTypeInfosByName().get('Amendment (URF)').getRecordtypeId();
        caseRec.AccountId = accRec.Id;
        caseRec.Strategic_Alliance_Department_Heads__c = true;
        caseRec.Corporate_Finance_Billing_Approver__c = userinfo.getUserId();
        caseRec.GDS_Acknowledgement__c = userinfo.getUserId();
        caseRec.Compliance_AML_KYC_Approver__c = userinfo.getUserId();
        caseRec.CFO_Onboarding_Retail_Lookup__c = userinfo.getUserId();
        caseRec.Co_Heads_of_Global_Distribution__c = userinfo.getUserId();
        insert caseRec;
        MFS_DomesticCaseApprovalCtrl caseCtrl1=new MFS_DomesticCaseApprovalCtrl(new ApexPages.StandardController(caseRec));  
        PageReference pageRef1=caseCtrl1.submitForApproval();
        System.assert(pageRef1!=null);
        List<Approval_Request__c> apprList = [Select Approval_status__c from Approval_Request__c where Onboarding_case__c =: caseRec.Id];
        List<Approval_Request__c> apprListToUpdate =  new List<Approval_Request__c>();
        for(Approval_Request__c app : apprList)
        {
           app.Approval_Status__c = 'Approved'; 
           apprListToUpdate.add(app); 
        }
        update apprListToUpdate;
    }
 }