src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Other_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for the &quot;My Contacts&quot; development.</description>
        <label>Other Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <description>Reference data field to track contact Role</description>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beneficial Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select the option that best represents the status of the contact.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Institutional</fullName>
        <active>true</active>
        <description>Used for Institutional Contacts</description>
        <label>Institutional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Used for Retail Contacts</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Coverage_Team__c.object
<CustomObject>
    <description>Contact Coverage Team is used to track the team that manages the Contact</description>
    <label>Contact Coverage Team</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Coverage Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Coverage Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_MyCampContactsTest.cls
@isTest
public class MFS_MyCampContactsTest {
    static testmethod void myCampTest(){
        List<Account> accList = MFS_TestDataUtility.createBulkAccounts(10);
        insert accList;
        List<Contact> tempConList = MFS_TestDataUtility.createBulkContacts(accList, 10);
        List<Contact> conList = new List<Contact>();
        for(Contact c : tempConList)
        {
            c.Status__c = 'Active';
            c.Contact_Role__c = 'Competitor';
            conList.add(c);
        }
        insert conList;
        Campaign campRec=MFS_TestDataUtility.createCampaign();
        campRec.Other_Contact__c = UserInfo.getUserId();
        insert campRec;
        List<CampaignMember> campMem = new List<CampaignMember>();
        for(Contact con : conList)
        {
            CampaignMember camp = new CampaignMember();
            camp.CampaignId=campRec.Id;
            camp.ContactId=con.Id;
            Camp.Status='Sent';
            campMem.add(camp);
        }
        insert campMem;
        List<AccountTeamMember> atmList = MFS_TestDataUtility.createBulkATM(accList, 10, UserInfo.getUserId()) ;
        insert atmList;
        List<Coverage_Team__c> cctList = MFS_TestDataUtility.createBulkCCT(conList, 10, UserInfo.getUserId());
        insert cctList;
        Test.startTest();
        //set SOSL results
        Id [] fixedSearchResults= new Id[10];
        for(Integer i=0;i<10;i++)
        {
            fixedSearchResults[i] = conList[i].Id; 
        }
        Test.setFixedSearchResults(fixedSearchResults);
        //Set page for controller
        Test.setCurrentPageReference(new Pagereference('Page.MFS_MyCampContacts'));
        System.currentPageReference().getParameters().put('isdtp', 'true');
        System.currentPageReference().getParameters().put('selectedTab1', 'true');
        
        MFS_MyCampContacts myContacts = new MFS_MyCampContacts(new ApexPages.StandardController(campRec));
        myContacts.oUser = '';
        myContacts.removeMemId = '';
        System.assertEquals(true, myContacts.isInConsole);
        myContacts.noOfExtRecords = 1;
        myContacts.selectedContact = conList[0].Id+','+conList[1].Id;
        myContacts.checkAndAddStatus();
        myContacts.goBack();
        myContacts.getMyContacts();
        myContacts.getNextContacts();
        myContacts.getpreviousContacts();
        myContacts.searchMCName = '******';
        myContacts.searchMCCountry = 'U';
        myContacts.searchInMyContacts();
        myContacts.searchMCName = 'Test';
        myContacts.searchMCCountry = 'United';
        myContacts.searchMCOrg = 'Test';
        myContacts.searchMCZone = 'Z000';
        myContacts.searchMCContRole = 'Competitor';
        myContacts.searchInMyContacts();
        myContacts.searchMCOrgType = 'Retail';
        myContacts.searchMCRegion = 'North America';
        myContacts.searchInMyContacts();
        myContacts.refreshMyContacts();
        //myContacts.nameSearchSOSL();
        myContacts.size = 2;
        myContacts.getMyContacts();
        
        myContacts.getOtherContact();
        myContacts.campaignRec = campRec;
        //myContacts.Other_Contact__c = UserInfo.getUserId();
        myContacts.getOtherContact();
        
        //myContacts.addAllContacts();
        //myContacts.addAllContactsSF1();
        myContacts.addCampMember();
        myContacts.addCampMemberSF1();
        myContacts.getExistingMember1();
        myContacts.resetMessages();
        myContacts.updateRemoveMembers();
        myContacts.toggleExistingMembers();
        myContacts.selectedOption = 'ACM';
        myContacts.toggleExistingMembers();
        myContacts.selectedMember = campMem[0].Id+','+campMem[1];
        myContacts.updateRemoveMembers();
        myContacts.selectedMember = 'Remove,'+campMem[0].Id;
        myContacts.updateRemoveMembers();
        myContacts.getItems();
        
         //run as institutional User
        User instUsr = MFS_TestDataUtility.createUser('Global Institutional Sales');
        insert instUsr;
        List<AccountTeamMember> atmInstList = MFS_TestDataUtility.createBulkATM(accList, 10, instUsr.Id) ;
        insert atmInstList;
        system.runAs(instUsr)
        {
            MFS_MyCampContacts myInstContacts = new MFS_MyCampContacts(new ApexPages.StandardController(campRec));
            myInstContacts.searchMCName = 'Test';
            myInstContacts.searchMCName = 'Test';
            myInstContacts.searchMCCountry = 'United';
            myInstContacts.searchMCOrg = 'Test';
            myInstContacts.searchMCZone = 'Z000';
            myInstContacts.searchInMyContacts();
        }
        //run as retail user
        Profile prf = [select id from Profile where name = 'Global Retail External'];
        User retailUsr = new User(UserName = 'unique_test2@mfstest.com', Lastname = 'Last', FirstName = 'First', Email = 'test@mfs.com', ProfileId = prf.id, Alias = 'test', 
                            TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US' );
        insert retailUsr;
        List<Coverage_Team__c> cctRetList = MFS_TestDataUtility.createBulkCCT(conList, 10, retailUsr.Id);
        insert cctRetList;
        system.runAs(retailUsr)
        {
            MFS_MyCampContacts myRetailContacts = new MFS_MyCampContacts(new ApexPages.StandardController(campRec));
            myRetailContacts.searchInMyContacts();
        }
        Test.stopTest();
    }
    
    static testmethod void testExceptionBlock(){
         Test.startTest();
        Campaign camp = MFS_TestDataUtility.createCampaign();
        MFS_MyCampContacts myCampConts = new MFS_MyCampContacts(new ApexPages.StandardController(camp));
        myCampConts.getApplicableContacts(null,null);
        myCampConts.searchInMyContacts();
        myCampConts.nameSearchSOSL(null,null,null);
        myCampConts.getExistingMember1();
        myCampConts.addCampMemberSF1();
        myCampConts.addCampMember();
        //myCampConts.addAllContactsSF1();
        //myCampConts.addAllContacts();
        //SONAR Fix
        System.assert(myCampConts.myContactsList == null);
        //myCampConts.getOtherContact();
        Test.stopTest();
    }

}