src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Delivery__c</fullName>
        <label>Campaign Delivery Platform</label>
        <picklist>
            <picklistValues>
                <fullName>ContactSync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Call List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tagged</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Objective__c</fullName>
        <label>Campaign Objective</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <picklist>
            <picklistValues>
                <fullName>Brand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Added Content</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Audience__c</fullName>
        <label>Target Audience</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <recordTypes>
        <fullName>Business_Driven</fullName>
        <active>true</active>
        <description>Used for Institutional and Retail Sales specific campaigns.</description>
        <label>Business Driven</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_UserTriggerUtilities.cls
public class MFS_UserTriggerUtilities {
    
    public static List<Campaign> getCampaignListForUsers(Map<Id, User> useMap){
        List<Campaign> campList = new List<Campaign>();
        Campaign camp;
        Set<Id> profileIdSet = new Set<Id>();
        for(User user : useMap.values()){
            profileIdSet.add(user.ProfileId);
        }
        RecordType rt = [select id from RecordType where DeveloperName='Business_Driven' and SobjectType='Campaign' LIMIT 1];
        Map<Id,Profile> profileMap = new Map<Id,Profile>([Select Id, Name from Profile where id in : profileIdSet]);
        Profile profile;
        for(User user : useMap.values()){
            profile = profileMap.get(user.ProfileId);
            if(System.Label.Profile_names_for_users_for_campaign.containsIgnoreCase(profile.Name)){
                camp = new Campaign(ownerId=user.Id, Name=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                    recordTypeId=rt.Id,Content_Type__c='Contact',Description__c=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                    Status='In-Progress',StartDate=System.today(),Campaign_Objective__c=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                    Target_Audience__c=System.Label.Default_campaign_name_for_user_for_Linkpoint, Campaign_Delivery__c='ContactSync', EndDate=null);  
                campList.add(camp);   
            }
        }
        system.debug('Size of campaign list in the User utility : '+campList.size());
        return campList;
    }
    
    @future
    public static void insertCampaignListForUsers(Set<Id> userId){
        List<Campaign> campList = new List<Campaign>();
        Campaign camp;
        RecordType rt = [select id from RecordType where DeveloperName='Business_Driven' and SobjectType='Campaign' LIMIT 1];
        for(Id user : userId){
            camp = new Campaign(ownerId=user, Name=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                recordTypeId=rt.Id,Content_Type__c='Contact',Description__c=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                Status='In-Progress',StartDate=System.today(),Campaign_Objective__c=System.Label.Default_campaign_name_for_user_for_Linkpoint,
                                Target_Audience__c=System.Label.Default_campaign_name_for_user_for_Linkpoint, Campaign_Delivery__c='ContactSync', EndDate=null);  
            campList.add(camp);   
        }
        insert campList;
    }
    
    @future
    public static void deleteCampaigns(Set<Id> campList){
        delete [select id from Campaign where id IN :campList];
    }
    
}