src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Due_In__c</fullName>
        <label>Reminder Notification in (days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ends_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Ends On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ends__c</fullName>
        <label>Recurrence Ends</label>
        <picklist>
            <picklistValues>
                <fullName>After</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Excludes_Weekends__c</fullName>
        <label>Business or Calendar Days</label>
        <picklist>
            <picklistValues>
                <fullName>Business Days</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Days</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Case_Number__c</fullName>
        <label>Parent Case Number Recurring</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Case__c</fullName>
        <formula>!ISBLANK(TEXT(Repeats__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Repeat_On_Weekly__c</fullName>
        <label>Repeat On</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeats_On__c</fullName>
        <label>Repeats On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Repeats__c</fullName>
        <label>Repeats</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <picklist>
            <controllingField>Start_Month__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_CaseSchedulerControllerTest.cls
@isTest
public class MFS_CaseSchedulerControllerTest {
   
    @testSetup
    static void dataSetup(){
        
    }
    
    static testmethod void RecurringCaseTest(){
        Account acc = MFS_TestDataUtility.createAccount();
        Test.StartTest();
        insert acc;
        Contact cont = MFS_TestDataUtility.createContact(acc.id);
        insert cont;
        User usr = MFS_TestDataUtility.createUser('System Administrator');
        insert usr;
        Case csRec = MFS_TestDataUtility.createCase(cont);
        csRec.Repeats__c = 'Quarterly';
        csRec.Start_Date__c = System.today();
        csRec.Repeat_On_Weekly__c = 'Tue';
        csRec.Due_In__c = 5;
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2017,9,24);
        csRec.Excludes_Weekends__c = 'Business Days';
        csRec.OwnerId = usr.Id;
        insert csRec;
        
        Case cse = [select Recurring_Case__c from case where Id =: csRec.Id];
        System.assertEquals(true, cse.Recurring_Case__c);
        Case cs = [select Repeats__c,Start_Date__c,Repeat_On_Weekly__c from Case where Id =: csRec.Id];
        MFS_CaseSchedulerController cseSchedule = new MFS_CaseSchedulerController(new ApexPages.StandardController(csRec));
        
        cseSchedule.save();
        cseSchedule.getDays();
        cseSchedule.getsummary();
        cseSchedule.endNow();
        
        csRec.Repeats__c = 'Weekly';
        csRec.start_date__C=Date.today();
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2017,9,24);
        csRec.Repeat_On_Weekly__c='Friday';
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Quarterly';
        csRec.Ends__c = 'On';
        cseSchedule.selectedQuarter='Beginning';
        csRec.Ends_On__c = Date.newInstance(2017,9,24);
        //update csRec;
        cseSchedule.getsummary();
        cseSchedule.save();
        Date tempDate=Date.newInstance(2017,4,4);
        
         csRec.Repeats__c = 'Quarterly';
        csRec.Ends__c = 'On';
        cseSchedule.selectedQuarter='End';
        csRec.Ends_On__c = Date.newInstance(2017,9,24);
       // update csRec;
        cseSchedule.getsummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Annual';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='April';
        csRec.Start_Day__c='20';
        update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='March';
        csRec.Start_Day__c='31';
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='March';
        csRec.Start_Day__c=null;
        //update csRec;
        cseSchedule.getSummary();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='April';
        csRec.Start_Day__c='31';
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c=null;
        csRec.Start_Day__c='31';
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='February';
        csRec.Start_Day__c='30';
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='April';
        csRec.Start_Day__c='30';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='February';
        csRec.Start_Day__c='29';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='February';
        csRec.Start_Day__c='2';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2017,4,24);
        csRec.Start_Month__c='March';
        csRec.Start_Day__c='30';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Quarterly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2017,4,24);
        cseSchedule.selectedQuarter='Beginning';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Annual';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2018,1,24);
        csRec.Start_Month__c='March';
        csRec.Start_Day__c='30';
        csRec.Repeats_on__c=Date.newInstance(2017,5,31);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
         csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='April';
        csRec.Start_Day__c='20;30';
        csRec.Repeats_on__c=Date.newInstance(2017,5,20);
       // update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2019,2,24);
        csRec.Start_Month__c='May';
        csRec.Start_Day__c='20;31';
        csRec.Repeats_on__c=Date.newInstance(2017,6,20);
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        
        csRec.Repeats__c = 'Semi Annual';
        csRec.Ends__c = 'On';
        csRec.Ends_On__c = Date.newInstance(2017,9,24);
         csRec.Start_Month__c='April';
        csRec.Start_Day__c='20;28';
       //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        
        
          csRec.Repeats__c = 'Monthly';
        csRec.Ends__c = 'Never';
         csRec.Start_Month__c='June';
        csRec.Start_Day__c='20;28';
        cseSchedule.getStartDay();
        cseSchedule.getSelectedStartDay();
        //update csRec;
        cseSchedule.getSummary();
        cseSchedule.save();
        Test.StopTest();
       // MFS_CaseSchedulerController cseSchedule1 = new MFS_CaseSchedulerController(new ApexPages.StandardController(csRec1));
        
    }
    
    static testmethod void RecurringCaseTestwithConditions(){
        Account acc = MFS_TestDataUtility.createAccount();
        Test.StartTest();
        insert acc;
        Contact cont = MFS_TestDataUtility.createContact(acc.id);
        insert cont;
        Case csRec = MFS_TestDataUtility.createCase(cont);
        insert csRec;
        
        Case csRec1 = MFS_TestDataUtility.createCase(cont);
        csRec1.Parent_Case_Number__c = csRec.Id;
        csRec1.Start_Date__c = (System.Today() - 5);
        insert csRec1;
        System.assertNotEquals(null, csRec1.Id);
         
        //MFS_CaseSchedulerController cseSchedule2 = new MFS_CaseSchedulerController(new ApexPages.StandardController());
       // cseSchedule1.Save();
        MFS_CaseSchedulerController cseSchedule1 = new MFS_CaseSchedulerController(new ApexPages.StandardController(csRec1));
        cseSchedule1.Save();
        
        MFS_CaseSchedulerController cseSchedule2 = new MFS_CaseSchedulerController(new ApexPages.StandardController(cont));
        
        csRec1.Start_Date__c = System.Today();
        csRec1.Repeats__c = 'Weekly';
        csRec1.Repeat_On_Weekly__c = null;
        update csRec1;
        cseSchedule1.Save();
        
        csRec1.Repeats__c = 'Weekly';
        csRec1.Repeat_On_Weekly__c = 'Tue';
        update csRec1;
        cseSchedule1.Save();
        
        csRec1.Due_In__c = null;
        csRec1.Excludes_Weekends__c = 'Business Days';
        update csRec1;
        cseSchedule1.Save();
        
        csRec1.Due_In__c = 5;
        update csRec1;
        cseSchedule1.Save();
        
        
        csRec1.Ends__c = 'On';
        csRec1.Ends_On__c = (System.Today() - 5);
        update csRec1;
        cseSchedule1.Save();
        
        csRec1.Ends__c = 'After';
        csRec1.Ends_On__c = System.Today();
        update csRec1;
        cseSchedule1.Save();  
        
        //Manoj
        csRec1.Due_In__c = 5;
        csRec1.Excludes_Weekends__c = null;
        update csRec1;
        cseSchedule1.Save();
        
        csRec1.Repeats__c = 'Monthly';
        csRec1.Ends__c = 'On';
        csRec1.Ends_On__c = Date.newInstance(2015,2,24);
        csRec1.Start_Date__c = Date.newInstance(2016,2,24);
        update csRec1;
        cseSchedule1.Save();
		
      	MFS_CaseSchedulerController.calculateNextCaseDate('Weekly', System.Today().addDays(30), 'January', '2;17', System.today().addDays(10));
        MFS_CaseSchedulerController.calculateNextCaseDate('Semi Annual', System.Today().addDays(30), 'January', '2;17', NULL);
        MFS_CaseSchedulerController.calculateNextCaseDate('Semi Annual', System.Today().addDays(30), 'January', '2;17', System.today().addDays(10));
           
        Test.stopTest();
    }
}