src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Due_In__c</fullName>
        <label>Reminder Notification in (days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ends_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Ends On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ends__c</fullName>
        <label>Recurrence Ends</label>
        <picklist>
            <picklistValues>
                <fullName>After</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Excludes_Weekends__c</fullName>
        <label>Business or Calendar Days</label>
        <picklist>
            <picklistValues>
                <fullName>Business Days</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Days</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Case_CreateDate__c</fullName>
        <formula>DATEVALUE(CreatedDate)+ CASE(TEXT(Repeats__c), &apos;Monthly&apos;, 30,&apos;Quarterly&apos;, 90,&apos;Semi Annual&apos;,180,&apos;Annual&apos;,360,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Case CreateDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Occurrence_Number__c</fullName>
        <description>Current Occurrence Number (if Recurring Case)</description>
        <label>Number of Occurrences</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Case__c</fullName>
        <formula>!ISBLANK(TEXT(Repeats__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Repeat_On_Weekly__c</fullName>
        <label>Repeat On</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeat_On__c</fullName>
        <label>Repeat On</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repeats_On__c</fullName>
        <label>Repeats On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Repeats__c</fullName>
        <label>Repeats</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>206(4)7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>408(b)2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5500 Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Addition/Deletion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc Reporting Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV Annual Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate List Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML/KYC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benchmark Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Reply - Inv Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code of Conduct Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code of Ethics Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian/Record Keeper Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Data Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directed Broker Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Fee Arrangement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Reporting Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FATCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HST Look Through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Certification of Coverage</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Occurrences__c</fullName>
        <description>Total No of Occurrences if it is a recurring Case</description>
        <label>Total No of Occurrences</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_RecurringCaseBatchTest.cls
@isTest
public class MFS_RecurringCaseBatchTest {

    static testmethod void recurringBatchTest(){
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Contact cont = MFS_TestDataUtility.createContact(acc.id);
        insert cont;
        List<case> caseRec = MFS_TestDataUtility.createBulkCase(cont,5,'Monthly');
        insert caseRec;
        List<case> caseRec1 = MFS_TestDataUtility.createBulkCase(cont,5,'Weekly');
        insert caseRec1;
        List<case> caseRecList = new List<case>();
        List<Attachment> attchList = new List<Attachment>();
        for(Case cs : caseRec1)
        {
            cs.Total_No_of_Occurrences__c = 1;
            caseRecList.add(cs);
            Attachment at = new Attachment();
            at.Name = 'Test Attachment';
            Blob bodyBlob = Blob.valueOf('Attachment Body');
            at.body = bodyBlob;
            at.parentId = cs.Id;
            attchList.add(at);
        }
        update caseRecList;
        insert attchList;
        Test.StartTest();
        MFS_RecurringCaseBatch recur = new MFS_RecurringCaseBatch();
        recur.query = 'Select id,AccountId,CaseNumber,ContactId,Origin,Type,Sub_Type__c,Priority,OwnerId,Repeats__c,Repeats_On__c,Ends__c,Total_No_of_Occurrences__c,Occurrence_Number__c,Start_Date__c,Repeat_On__c,Repeat_On_Weekly__c,Next_Case_CreateDate__c,Ends_On__c,Due_In__c,Excludes_Weekends__c from case where Recurring_Case__c =true Limit 5';
        Id batchProcessId = Database.executeBatch(recur);
        MFS_RecurringCaseBatchSchedule sh = new MFS_RecurringCaseBatchSchedule();
        string sch = '0 0 23 * * ?';
        system.schedule('Test Recurring Schedule',sch,sh);
        Test.stopTest();
        System.assertEquals(database.countquery('select count() from case where Recurring_Case__c =true'), 10);
    }
    
}