src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Due_In__c</fullName>
        <label>Reminder Notification in (days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ends_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Ends On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ends__c</fullName>
        <label>Recurrence Ends</label>
        <picklist>
            <picklistValues>
                <fullName>After</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Excludes_Weekends__c</fullName>
        <label>Business or Calendar Days</label>
        <picklist>
            <picklistValues>
                <fullName>Business Days</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Days</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Case_CreateDate__c</fullName>
        <formula>DATEVALUE(CreatedDate)+ CASE(TEXT(Repeats__c), &apos;Monthly&apos;, 30,&apos;Quarterly&apos;, 90,&apos;Semi Annual&apos;,180,&apos;Annual&apos;,360,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Case CreateDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Occurrence__c</fullName>
        <label>Number of Occurrence</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occurrence_Number__c</fullName>
        <description>Current Occurrence Number (if Recurring Case)</description>
        <label>Number of Occurrences</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Case_Number__c</fullName>
        <label>Parent Case Number Recurring</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Case__c</fullName>
        <formula>!ISBLANK(TEXT(Repeats__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Repeat_On_Weekly__c</fullName>
        <label>Repeat On</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeat_On__c</fullName>
        <label>Repeat On</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repeats_On__c</fullName>
        <label>Repeats On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Repeats__c</fullName>
        <label>Repeats</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <picklist>
            <controllingField>Start_Month__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>206(4)7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>408(b)2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5500 Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Addition/Deletion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc Reporting Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV Annual Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate List Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML/KYC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benchmark Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Reply - Inv Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code of Conduct Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code of Ethics Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian/Record Keeper Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Data Request (Template)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directed Broker Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Fee Arrangement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Reporting Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FATCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HST Look Through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Certification of Coverage</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Occurrences__c</fullName>
        <description>Total No of Occurrences if it is a recurring Case</description>
        <label>Total No of Occurrences</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_RecurringCaseBatch.cls
/***************************************************************************************************
Apex Class Name    : MFS_RecurringCaseBatch 
Version            : 1.0 
Created Date       : 08 June 2016
Function           : Batch class to insert child case based on the "Repats on" Date of Case object.
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Jata Dubey               08/06/2016              Original Version
***************************************************************************************************/
global with sharing class MFS_RecurringCaseBatch implements Database.Batchable<SObject> , DataBase.Stateful{
    global String query;
    global List<Case> nextCaseList;
    global List<Case> oldCaseList;
    global List<Attachment> insertattList;
    //constructor
    global MFS_RecurringCaseBatch(){
        //String recId='500P0000004avZM';
        this.query='Select id,AccountId,CaseNumber,Number_of_Occurrence__c,Start_month__c,Start_Day__c,ContactId,Origin,Type,Sub_Type__c,Priority,OwnerId,Description,Repeats__c,Repeats_On__c,Ends__c,Total_No_of_Occurrences__c,Occurrence_Number__c,Start_Date__c,Repeat_On__c,Repeat_On_Weekly__c,Next_Case_CreateDate__c,Ends_On__c,Due_In__c,Excludes_Weekends__c from case where Recurring_Case__c =true'; 
        nextCaseList=new List<Case>();
        oldCaseList=new List<Case>(); 
        insertattList=new List<Attachment>();
    }
    
    /**
    * @Description : Method is used to return Parent Case records. 
    * @Param : Database.BatchableContext
    * @return: DataBase.QueryLocator
    **/
    global DataBase.QueryLocator start(Database.BatchableContext batchCon){
        return DataBase.getQueryLocator(query);
    }
    
    /**
    * @Description : Method is used to copy all the details of parent case and calculate next recurring case date.
    * @Param : DataBase.BatchableContext,List<sObject> 
    * @return: N/A
    **/
    global void execute(DataBase.BatchableContext batchCon,List<sObject> caseList){
        try{
             system.debug('date'+System.today().addDays(7));
            for(sObject sObjRec:caseList)  {
                Case caseRec=(Case)sObjRec; 
                if(System.today()==caseRec.Repeats_On__c){
                	//Date dt=Date.newInstance(2017,7,28);
                	//if(dt==caseRec.Repeats_On__c){
                    Case nextCase=new Case();
                    Case oldCase=new Case();
                    nextCase.AccountId=caseRec.AccountId;
                    nextCase.ContactId=caseRec.ContactId; 
                    nextCase.Origin=caseRec.Origin;
                    nextCase.Type=caseRec.Type;
                    nextCase.Sub_Type__c=caseRec.Sub_Type__c; 
                    nextCase.Priority=caseRec.Priority;
                    nextCase.Status=MFS_AllConstants.DEFAULT_CASE_STATUS;
                    nextCase.OwnerID=caseRec.OwnerId;
                    nextCase.Description=caseRec.Description;
                    nextCase.Parent_Case_Number__c=caseRec.CaseNumber;
                    nextCase.Parent_Case_Id__c=caseRec.Id;
                    nextCase.Excludes_Weekends__c=caseRec.Excludes_Weekends__c;
                    nextCase.Due_In__c=caseRec.Due_In__c; 
                    nextCase.Ends__c=caseRec.Ends__c;
                    nextCase.Ends_On__c=caseRec.Ends_On__c;
                    nextCase.Start_Date__c=caseRec.Start_Date__c;  
                    nextCase.Repeat_On_Weekly__c=caseRec.Repeat_On_Weekly__c;
                    nextCase.Occurrence_Number__c=caseRec.Occurrence_Number__c;
                    nextCase.Due_Date__c=MFS_CaseSchedulerController.populateDueDate(caseRec.ownerId,caseRec.Repeats_On__c,Integer.valueOf(caseRec.Due_In__c),caseRec.Excludes_Weekends__c);
                    oldCase.Id=caseRec.Id;
                    if(caseRec.Total_No_of_Occurrences__c == null){
                        nextCase.Total_No_of_Occurrences__c = 1; 
                        oldCase.Total_No_of_Occurrences__c = 1;
                    } else {
                        nextCase.Total_No_of_Occurrences__c = caseRec.Total_No_of_Occurrences__c + 1;
                        oldCase.Total_No_of_Occurrences__c = caseRec.Total_No_of_Occurrences__c + 1;
                    }
                   
                    Date repeatsOnDate;
                    String isCalled = 'Batch';
                    if(caseRec.Repeats__c.equals(MFS_AllConstants.RepeatsWeekly)) {
                        repeatsOnDate = MFS_CaseSchedulerController.calculateNextCaseDateWeekly(caseRec.Start_Date__c,caseRec.Repeat_On_Weekly__c,isCalled);
                    } else {
                       repeatsOnDate = MFS_CaseSchedulerController.calculateNextCaseDate(caseRec.Repeats__c,caseRec.Start_Date__c,caseRec.start_month__c,caseRec.start_day__C,caseRec.repeats_on__c);
                    }
                    nextCase.Number_of_Occurrence__c = MFS_CaseSchedulerController.calculateOccurrence(Integer.valueOf(nextCase.Total_No_of_Occurrences__c),Integer.valueOf(caseRec.Occurrence_Number__c),caseRec.Ends__c,caseRec.Repeats__c,caseRec.Ends_On__c,caseRec.Start_Date__c,repeatsOnDate);
                    oldCase.Number_of_Occurrence__c = MFS_CaseSchedulerController.calculateOccurrence(Integer.valueOf(nextCase.Total_No_of_Occurrences__c),Integer.valueOf(caseRec.Occurrence_Number__c),caseRec.Ends__c,caseRec.Repeats__c,caseRec.Ends_On__c,caseRec.Start_Date__c,repeatsOnDate);
                    //populate repeats on
                    System.debug('repeatsOnDate...'+repeatsOnDate+'caseRec.Ends_on__c...'+caseRec.Ends_on__c);
                    if(caseRec.Ends_on__c !=null && caseRec.Ends_on__c < repeatsOnDate && caseRec.Ends_on__c > caseRec.Start_Date__c) {
                        oldCase.Repeats_On__c = null; 
                    }	
                    else if(caseRec.Occurrence_Number__c!=null && caseRec.Occurrence_Number__c == nextCase.Total_No_of_Occurrences__c  ){
                        oldCase.Repeats_On__c = null;
                    } else {
                        oldCase.Repeats_On__c = repeatsOnDate;
                   }
                   
                    nextCaseList.add(nextCase);
                    oldCaseList.add(oldCase);
                }
            }
        } catch(Exception ex){
            System.debug('Execption occured:'+ex.getMessage());  
        }
        
        
    }
    
    /**
    * @Description : Method is used to Insert child case and copy attachments from parent case.
    * @Param : DataBase.BatchableContext
    * @return: N/A
    **/
    global void finish(DataBase.BatchableContext batchCon){
        try{
            if(!nextCaseList.isEmpty()){
                insert nextCaseList;
                Set<Id> oldCaseParentId = new Set<Id>();
                
                for(Case newCase : nextCaseList){
                    oldCaseParentId.add(newCase.Parent_Case_Id__c);
                }
                List<Attachment> attList = new List<Attachment>([select Id,name,body,ParentId from Attachment where ParentId in : oldCaseParentId]);
                if(!attList.isEmpty()){
                    for(Case newCase : nextCaseList){
                        for(Attachment a : attList){
                            if(newCase.Parent_Case_Id__c == a.ParentId){
                                Attachment attAdd = new Attachment(Name = a.Name,Body = a.Body,ParentId = newCase.Id);
                                insertattList.add(attAdd);
                            }
                        }
                    }
                    if(!insertattList.isEmpty()){
                        insert insertattList;
                    }
                }
            }
            if(!oldCaseList.isEmpty()){
               update oldCaseList; 
            }
        } catch(Exception ex) {
            System.debug('Execption occured:'+ex.getMessage());
        }
        
    }
}