src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AML_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AML Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CFO_Onboarding_Retail_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field used for approval process on a retail onboarding case.</description>
        <label>CFO Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW47t</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Heads_of_Global_Distribution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Retail Onboarding approval process (Amendments)</description>
        <label>Co-Heads of Global Distribution</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW48D</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance - AML/KYC Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_AML_KYC_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliance - AML/KYC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance_Billing_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corp Finance - Billing Group</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Corporate_Finance_Billing_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate Finance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FATCA_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FATCA Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases51</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funds_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funds Lawyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GDS_Acknowledgement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approval field for Amendment Process for Retail Onboarding.</description>
        <label>GDS Acknowledgement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CasesW4Bb</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_US_Questionnaire_Approval_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-US Questionnaire Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strategic_Alliance_Department_Heads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strategic Alliance Department Heads</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Retail_Amendment</fullName>
        <active>true</active>
        <businessProcess>Amendment %28URF%29</businessProcess>
        <description>Used to manage the Amendment (URF) process</description>
        <label>Retail Amendment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_DomesticCaseApprovalCtrlTest.cls
@isTest
public class MFS_DomesticCaseApprovalCtrlTest {
    static testmethod void testDomesticAndAmendmentCase()
    {
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec; 
        Contact cont = MFS_TestDataUtility.createContact(accRec.id);
        insert cont;
        Case caseRec = MFS_TestDataUtility.createCase(cont);
        RecordType rt = [select id from RecordType where DeveloperName='Retail_Amendment' and SobjectType='Case' LIMIT 1];
        caseRec.recordtypeid= rt.Id;//Schema.SObjectType.Case.getRecordTypeInfosByName().get('Amendment (URF)').getRecordtypeId();
        caseRec.AccountId = accRec.Id;
        caseRec.Strategic_Alliance_Department_Heads__c = true;
        caseRec.Corporate_Finance_Billing_Approver__c = userinfo.getUserId();
        caseRec.GDS_Acknowledgement__c = userinfo.getUserId();
        caseRec.Compliance_AML_KYC_Approver__c = userinfo.getUserId();
        caseRec.CFO_Onboarding_Retail_Lookup__c = userinfo.getUserId();
        caseRec.Co_Heads_of_Global_Distribution__c = userinfo.getUserId();
        insert caseRec;
        Case caseRec1 = MFS_TestDataUtility.createCase(cont);
        caseRec1.recordtypeid= Schema.SObjectType.Case.getRecordTypeInfosByName().get(MFS_AllConstants.APPROVAL_DOMESTIC_RT).getRecordtypeId();
        caseRec1.Non_US_Questionnaire_Approval_Group__c = false;
        caseRec1.Compliance_AML_KYC__c = true;
        caseRec1.Corporate_Finance__c = true;
        caseRec1.GDS_Acknowledgement__c = userinfo.getUserId();
        caseRec1.Funds_Lawyer__c = userinfo.getUserId(); 
        caseRec1.FATCA_Lawyer__c = userinfo.getUserId();
        caseRec1.Final_Acknowledgement__c = userinfo.getUserId(); 
        caseRec1.Distribution_Lawyer__c = userinfo.getUserId();
        caseRec1.AML_Lawyer__c = userinfo.getUserId();
        insert caseRec1; 
        Test.setCurrentPage(Page.MFS_AmendmentCaseApprovalPage); 
        MFS_DomesticCaseApprovalCtrl caseCtrl=new MFS_DomesticCaseApprovalCtrl(new ApexPages.StandardController(caseRec));  
        PageReference pageRef=caseCtrl.submitForApproval();
        System.assert(pageRef!=null);
        Test.setCurrentPage(Page.MFS_DomesticCaseApprovalPage); 
        MFS_DomesticCaseApprovalCtrl caseCtrl1=new MFS_DomesticCaseApprovalCtrl(new ApexPages.StandardController(caseRec1));  
        PageReference pageRef1=caseCtrl1.submitForApproval();
        System.assert(pageRef1!=null); 
        PageReference pageRef2=caseCtrl.goBack();
        System.assert(pageRef2!=null);
        Test.stopTest();
    }
    
}