src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with G3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending with G4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Service_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Service Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Service_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_AML_KYC_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance - AML/KYC Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Compliance_AML_KYC_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_Code_of_Ethics_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliance - Code of Ethics Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Finance_Billing_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corp Finance - Billing Group</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Corporate_Finance_Billing_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GIS_Risk_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GIS - Risk Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GIS_Transition_Management_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GIS - Transition Management Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Insurance Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investment_Compliance_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Investment Compliance Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Legal_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MFSI_Management_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MFSI - Management Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_PM_Approvals_Required__c</fullName>
        <label>Number of PM Approvals Required</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Performance_Information_Management_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Performance/Information Management Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Compliance_Back_End_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio Compliance (Back End) Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Management_Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio Management Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortfolioManagementApprover1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trading_Equity_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trading - Equity Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trading_Fixed_Income_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trading - Fixed Income Group</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Used to manage the Institutional onboarding process.</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MFS_OnBoardingCaseApprovalCtrl_Test.cls
/***************************************************************************************************
Apex Class Name    : MFS_OnBoardingCaseApprovalCtrl_Test 
Version            : 1.0 
Created Date       : 06 SEPT 2016
Function           : Test class for MFS_OnBoardingCaseApprovalCtrl
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Priya Gupta               06/09/2016              Original Version
***************************************************************************************************/
@isTest
public class MFS_OnBoardingCaseApprovalCtrl_Test {
    
    static testmethod void testOnBoardingCase()
    {
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec; 
        Contact cont = MFS_TestDataUtility.createContact(accRec.id);
        insert cont;
        User testUser=MFS_TestDataUtility.createUser('Standard User');
        insert testUser;
        Case caseRec = MFS_TestDataUtility.createCase(cont);
        caseRec.recordtypeid= Schema.SObjectType.Case.getRecordTypeInfosByName().get('Onboarding').getRecordtypeId();
        caseRec.AccountId = accRec.Id;
        caseRec.Type = 'Cash';
        caseRec.Priority = 'Low';
        caseRec.Status = 'Service';
        caseRec.Portfolio_Management_Approver1__c = userinfo.getUserId();
        caseRec.Client_Service_Approver__c = userinfo.getUserId();
        caseRec.Corporate_Finance_Billing_Approver__c = userinfo.getUserId();
        caseRec.Compliance_AML_KYC_Approver__c = userinfo.getUserId();
        caseRec.Legal_Approver__c = userinfo.getUserId();
        caseRec.Compliance_Code_of_Ethics_Group__c = true;
       // caseRec.GIS_Risk_Group__c = true;
        caseRec.GIS_Transition_Management_Group__c = true;
        caseRec.Insurance_Group__c = true;
        caseRec.MFSI_Management_Group__c = true;
        caseRec.Performance_Information_Management_Group__c = true;
       // caseRec.Portfolio_Compliance_Back_End_Group__c = true;
        caseRec.Investment_Compliance_Group__c = true;
        caseRec.Reporting__c = true;
        caseRec.Trading_Equity_Group__c = true;
        caseRec.Trading_Fixed_Income_Group__c = true;
        caseRec.Number_of_PM_Approvals_Required__c = '3';
        caseRec.Due_Date__c = System.today();
        insert caseRec;
        Test.setCurrentPage(Page.MFS_OnBoardingCaseApprovalPage); 
        MFS_OnBoardingCaseApprovalCtrl caseCtrl=new MFS_OnBoardingCaseApprovalCtrl(new ApexPages.StandardController(caseRec));
        PageReference pageRef=caseCtrl.submitForApproval();
        System.assert(pageRef!=null);
        caseRec=[Select id,Approval_Status__c from Case where id=:caseRec.Id];
        PageReference pageRef1=caseCtrl.goBack();
        System.assert(pageRef1!=null);
        Test.stopTest();
        
    }
    
}