src/objects/Client_Investment_Objective__c.object
<CustomObject>
    <description>Object tied to Client Strategy Plans, to track Client Investment needs and goal.</description>
    <fields>
        <fullName>Client_Strategy_Plan__c</fullName>
        <label>Client Strategy Plan</label>
        <referenceTo>Strategy_Plan__c</referenceTo>
        <relationshipLabel>Investment Objectives and Insights</relationshipLabel>
        <relationshipName>Client_Investment_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Investment_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investment Objective and Insight</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Objectives and Insights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FieldsUsedInButton__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>FieldsUsedInButton</label>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/objects/Strategy_Plan__c.object
<CustomObject>
    <description>To be used to capture Client and Prospect strategy plans</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategy Plans</relationshipLabel>
        <relationshipName>Strategy_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy Plan</label>
    <nameField>
        <label>Strategy Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_NewClientInvestmentObj_Test.cls
@isTest(SeeAllData=false)
public class MFS_NewClientInvestmentObj_Test {
    
     static testmethod void testRedirect()
    {
        Test.startTest();
        FieldsUsedInButton__c objField=MFS_TestDataUtility.createFieldForButton('Account','Name','Name','Text');
        insert objField;   
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Strategy_Plan__c sPlan = MFS_TestDataUtility.createStrategyPlan(accRec.Id);
        insert sPlan;
        Client_Investment_Objective__c clientObjRec=MFS_TestDataUtility.createClientInverstment(accRec.Id);
        clientObjRec.Client_Strategy_Plan__c = sPlan.Id;
        insert clientObjRec;
        Strategy_Plan__c strategyPlan=MFS_TestDataUtility.createStrategyPlan(accRec.Id);
        insert strategyPlan;
        List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Client_Investment_Objective__c','Client Strategy Plan','Client_Strategy_Plan__c'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Client_Investment_Objective__c','Organization','Organization__c'));
        insert fieldIds;
        List<Client_Investment_Objective__c> clientObjList = new List<Client_Investment_Objective__c>{clientObjRec};
        PageReference pageRef = Page.MFS_NewClientInvestmentObj;
        pageRef.getParameters().put('Id',strategyPlan.Id);
        Test.setCurrentPage(pageRef);
        MFS_NewClientInvestmentObj newClientObj=new MFS_NewClientInvestmentObj(new ApexPages.StandardSetController(clientObjList));   
        PageReference pageURL=newClientObj.redirect();    
        System.assert(pageURL!=null);             
        Test.stopTest();
    }


}