src/objects/Client_Investment_Objective__c.object
<CustomObject>
    <description>Object tied to Client Strategy Plans, to track Client Investment needs and goal.</description>
    <fields>
        <fullName>Client_Strategy_Plan__c</fullName>
        <label>Client Strategy Plan</label>
        <referenceTo>Strategy_Plan__c</referenceTo>
        <relationshipLabel>Investment Objectives and Insights</relationshipLabel>
        <relationshipName>Client_Investment_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Investment_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investment Objective and Insight</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Objectives and Insights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Strategy_Plan__c.object
<CustomObject>
    <description>To be used to capture Client and Prospect strategy plans</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategy Plans</relationshipLabel>
        <relationshipName>Strategy_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy Plan</label>
    <nameField>
        <label>Strategy Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_NewClientInvestmentObj.cls
/***************************************************************************************************
Apex Class Name    : MFS_NewClientInvestmentObj 
Version            : 1.0 
Created Date       : 09 August 2016
Function           : Class is used to prepopulate fields on creation of new client investment record from strategy Plan related list button.
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Priya Gupta               09/08/2016              Original Version
***************************************************************************************************/
public with sharing class MFS_NewClientInvestmentObj {
    
//Constructor 
    public MFS_NewClientInvestmentObj(ApexPages.StandardSetController stdCtrl)
        {
            
        }
  
/**
* @Description : Method is used to construct URL for redirection
* @Param : N/A
* @return: PageReference
**/    
    public PageReference redirect()
        {
            Schema.DescribeSObjectResult r = Client_Investment_Objective__c.sObjectType.getDescribe();
			String keyPrefix = r.getKeyPrefix();	
             PageReference pageRef=new PageReference('/'+keyPrefix+'/e');
            try{
                Strategy_Plan__c strategyPlan=[Select id,Name, Organization__r.Id,Organization__r.Name from Strategy_Plan__c where id=:ApexPages.currentPage().getParameters().get('id')];
                List<String> listOfFields=new List<String>{'Client_Strategy_Plan__c','Organization__c'};
                Map<String,String> fieldMap=MFS_Utilities.getFieldId('Client_Investment_Objective__c',listOfFields);   
                pageRef.getParameters().put('retURL',strategyPlan.id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0)),strategyPlan.Name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0))+MFS_AllConstants.LK_ID,strategyPlan.Id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1)),strategyPlan.Organization__r.Name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1))+MFS_AllConstants.LK_ID,strategyPlan.Organization__r.Id);
                system.debug('pageRef:'+pageRef);
            }
            catch(Exception exe)
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,exe.getmessage()));
            }
            return pageRef;


        }}