src/objects/Competitor_Product__c.object
<CustomObject>
    <description>Competitor Products object will contain competitor product from Morningstar and Evestment.</description>
    <fields>
        <fullName>Firm_Name__c</fullName>
        <label>Firm Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitor Product</relationshipLabel>
        <relationshipName>Competitor_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Competitor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor Product</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Product</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Competitor_Product_Opp_Association__c.object
<CustomObject>
    <description>Junction Object between Competitor Products and Opportunities</description>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor Product</label>
        <referenceTo>Competitor_Product__c</referenceTo>
        <relationshipName>Competitor_Product_Opp_Associatis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitor Products</relationshipLabel>
        <relationshipName>Competitor_Product_Opp_Associatis</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor Product to Oppty Junction</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product to Oppty Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_CompetitorSearchControllerTest.cls
@isTest(seeAllData = false)
public class MFS_CompetitorSearchControllerTest {

    static testMethod void testCompProductController(){   
        Test.startTest();
        Competitor_Product__c compProduct = MFS_TestDataUtility.createComptrProduct();
        Account account = MFS_TestDataUtility.createAccount();
        insert account;
        compProduct.Firm__c = account.Id;        
        compProduct.Firm_Name__c = account.Name;
        insert compProduct;
        Opportunity opp = MFS_TestDataUtility.createOpportunity(account.Id);
        insert opp;
        Competitor_Product_Opp_Association__c compProJunction = new Competitor_Product_Opp_Association__c(Competitor_Product__c=compProduct.Id,Opportunity__c=opp.Id);
        MFS_CompetitorSearchController compPrsearchCtrl = new MFS_CompetitorSearchController(new ApexPages.StandardController(compProJunction));
        compPrsearchCtrl.searchCom='AllianzGI NFJ Mid Cap Value 100';
        compPrsearchCtrl.firm = 'TestAccount';
        compPrsearchCtrl.theOpp = opp;
        compPrsearchCtrl.searchComProduct();
        PageReference addUnknownStrategyPr = compPrsearchCtrl.addUnknownStrategy();
        //SONAR Fix
        system.assert(addUnknownStrategyPr == null );
        compPrsearchCtrl.wraplist[0].isSelected = true;
        compPrsearchCtrl.addUnknownStrategy();
        compPrsearchCtrl.onCancel();
        Test.stopTest();
    }
    
    static testMethod void testCompProductControllerNegetiveScenario(){  
        Test.startTest();
        Competitor_Product__c compProduct = MFS_TestDataUtility.createComptrProduct();
        Account account = MFS_TestDataUtility.createAccount();
        insert account;
        compProduct.Firm__c = account.Id;
        compProduct.Firm_Name__c = account.Name;
        insert compProduct;
        Opportunity opp = MFS_TestDataUtility.createOpportunity(account.Id);
        insert opp;
        Competitor_Product_Opp_Association__c compProJunction = new Competitor_Product_Opp_Association__c(Competitor_Product__c=compProduct.Id,Opportunity__c=opp.Id);
        MFS_CompetitorSearchController compPrsearchCtrl = new MFS_CompetitorSearchController(new ApexPages.StandardController(compProJunction));
        compPrsearchCtrl.wraplist = null;
        compPrsearchCtrl.searchCom=null;
        compPrsearchCtrl.firm = null;
        compPrsearchCtrl.theOpp = opp;
        compPrsearchCtrl.searchComProduct();
        compPrsearchCtrl.wraplist[0].isSelected = false;
        PageReference addUnknownStrategyPr = compPrsearchCtrl.addUnknownStrategy();
        //SONAR Fix
        system.assert(addUnknownStrategyPr == null );
        compPrsearchCtrl.onCancel();
        Test.stopTest();
    }
    
    
}