src/objects/Consultant_Rating__c.object
<CustomObject>
    <description>To be used to rack ratings for a specific consultant</description>
    <label>Consultant Rating</label>
    <nameField>
        <label>Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultant Ratings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Rating_Change__c.object
<CustomObject>
    <description>Consultant strategy rating process, when rating upgraded, downgraded, or maintained.</description>
    <fields>
        <fullName>Consultant_Rating__c</fullName>
        <label>Consultant Rating</label>
        <referenceTo>Consultant_Rating__c</referenceTo>
        <relationshipLabel>Rating Changes</relationshipLabel>
        <relationshipName>Rating_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rating Change</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/classes/MFS_NewRatingChange_Test.cls
@isTest(SeeAllData=false)
public class MFS_NewRatingChange_Test {

     static testmethod void testRedirect()
    {
        Test.startTest();       
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec;
        Consultant_Rating__c ratingRec=MFS_TestDataUtility.createConsRating(accRec.id,prodRec.id);
        insert ratingRec;
        List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Rating_Change__c','Consultant Rating','Consultant_Rating__c'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Rating_Change__c','Name','Name'));
        insert fieldIds;
        List<Rating_Change__c> ratingCList = new List<Rating_Change__c>{new Rating_Change__c()};
        PageReference pageRef = Page.MFS_NewRatingChange;
        pageRef.getParameters().put('Id',ratingRec.Id);
        Test.setCurrentPage(pageRef);
        MFS_NewRatingChange ratingChange=new MFS_NewRatingChange(new ApexPages.StandardSetController(ratingCList));   
        PageReference pageURL=ratingChange.redirect();    
        System.assert(pageURL!=null);             
        Test.stopTest();
    }
    
}