src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MicroStrategy_URLs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QueryString__c</fullName>
        <label>QueryString</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MicroStrategy URLs</label>
</CustomObject>

src/classes/MFS_MSTR_DashboardController.cls
public class MFS_MSTR_DashboardController
{
    public MFS_MSTR_DashboardController() {
        
    }
    
    public string getHomePageURL()
    {
        try
        {
            MicroStrategy_URLs__c ob = MicroStrategy_URLs__c.getInstance('HomeDashboard');
            string url = ob.URL__c;
            if (String.isNotBlank(ob.QueryString__c))
            {
                url += ('?' + ob.QueryString__c);
            }

        	return url;
        }
        catch(Exception ex)
        {
            return '';
        }
    }

	public string getTabURL()
    {
        try
        {
            MicroStrategy_URLs__c ob = MicroStrategy_URLs__c.getInstance('BIDashboardWebTab');
            string url = ob.URL__c;
            if (String.isNotBlank(ob.QueryString__c))
            {
                url += ('?' + ob.QueryString__c);
            }

        	return url;
        }
        catch(Exception ex)
        {
            return '';
        }
    }
    
    public string getRepScorecardURL()
    {
        try
        {
            string mdmId = ApexPages.currentPage().getParameters().get('MDM_Id');
            
            MicroStrategy_URLs__c ob = MicroStrategy_URLs__c.getInstance('RepScorecard');
            string url = ob.URL__c;
            if (String.isNotBlank(ob.QueryString__c))
            {
                url += ('?' + ob.QueryString__c.replace('{!Contact.MDM_ID__c}', mdmId));
            }

        	return url;
        }
        catch(Exception ex)
        {
            return '';
        }
    }
}