src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <description>MDM ID</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MicroStrategy_URLs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QueryString__c</fullName>
        <label>QueryString</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MicroStrategy URLs</label>
</CustomObject>

src/classes/MFS_MSTR_DashboardExtension.cls
public class MFS_MSTR_DashboardExtension {

    Private final Contact c;
    
    public MFS_MSTR_DashboardExtension(ApexPages.StandardController stdController) {
        this.c = (Contact)stdController.getRecord();
    }

         public string getRepScorecardURL() {
       
             try
       		 {
                                 
            string mdmId = c.MDM_ID__c; 
            
            MicroStrategy_URLs__c ob = MicroStrategy_URLs__c.getInstance('RepScorecard');
            string url = ob.URL__c;
            if (String.isNotBlank(ob.QueryString__c))
            {
                url += ('?' + ob.QueryString__c.replace('{!Contact.MDM_ID__c}', mdmId));
            }

        	return url;
        }
        catch(Exception ex)
        {
            return '';
        }
    }

    
}