src/objects/Distribution_List__c.object
<CustomObject>
    <description>This object captures distribution lists, e.g. email distribution lists.</description>
    <label>Distribution List</label>
    <nameField>
        <label>Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>CRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship_End_Date__c</fullName>
        <label>Relationship End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_DistributionListUtilities.cls
/**
Apex Class Name    : MFS_DistributionListUtilities
Version            : 1.0 
Created Date       : Dec. 19, 2016
Function           : Handler class that gets called by Distribution_List__c Triggers 
when Distribution_List__c is updated
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Christine Cui              12/19/2016              Original Version
**/

public class MFS_DistributionListUtilities {
//Method to update Plan Association's "Contact Relationship End Date" to today's date when distribution list changes from Active to Inactive.
    public static List<Plan_Association__c> updatePlanAssociations(List<Plan_Association__c> lstPlanAsscn){
        List<Plan_Association__c> planAsscnToUpdateList = new List<Plan_Association__c>();
        for(Plan_Association__c plnAsscn : lstPlanAsscn ){
            plnAsscn.Contact_Relationship_End_Date__c = system.TODAY();
            plnAsscn.CRT__c = false;
            planAsscnToUpdateList.add(plnAsscn);
        }
        return planAsscnToUpdateList; 
    }
}