src/objects/Distribution_List__c.object
<CustomObject>
    <description>This object captures distribution lists, e.g. email distribution lists.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Distribution List</label>
    <nameField>
        <label>Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>CRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship_End_Date__c</fullName>
        <label>Relationship End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AML Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Signer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member/Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custodian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lending Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_DistributionListUtilitiesTest.cls
@isTest
public class MFS_DistributionListUtilitiesTest {
 public static testMethod void updateDistributionListTest()
 {  List<Distribution_List__c> dlcUpdateList = new List<Distribution_List__c>();
    Account acc1 = MFS_TestDataUtility.createAccount();
    insert acc1;
    Distribution_List__c dlc = MFS_TestDataUtility.createDistributionList(acc1.Id);
    insert dlc;   
    Plan_Association__c pac = MFS_TestDataUtility.createPlanAsscnwithDistList(acc1.Id, dlc.Id);
  	pac.Contact_role__c = 'Auditor';
    insert pac;
    List<Distribution_List__c> dlcList = new List<Distribution_List__c>([Select Id, Status__c from Distribution_List__c where Id =: dlc.Id]);
    for(Distribution_List__c dList: dlcList){
        dList.Status__c = 'Inactive';
        dlcUpdateList.add (dList);
    }    
    MFS_Utilities.runReset();
        try{
        update dlcUpdateList;
        }catch(Exception e){
           system.debug(e.getMessage()); 
        }
    List<Plan_Association__c> pacLst = new List<Plan_Association__c> ([Select Id, CRT__c, Contact_Relationship_End_Date__c from Plan_Association__c where Id =: pac.Id]);
    for(Plan_Association__c pasc: pacLst)
    {
        system.assertEquals(System.TODAY(), pasc.Contact_Relationship_End_Date__c);
        system.assertEquals(false, pasc.CRT__c);
    }
 }
 }