src/objects/Distribution_List__c.object
<CustomObject>
    <description>This object captures distribution lists, e.g. email distribution lists.</description>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distribution List</relationshipLabel>
        <relationshipName>Distribution_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Distribution List</label>
    <nameField>
        <label>Distribution List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>CRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship_End_Date__c</fullName>
        <label>Relationship End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution List</label>
        <referenceTo>Distribution_List__c</referenceTo>
        <relationshipName>Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>$Organization.Country</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_DistributionListHandler.cls
/**
Apex Class Name    : MFS_DistributionListHandler
Version            : 1.0 
Created Date       : Dec 19 2016
Function           : Handler class that gets called by Distribution_List__c Triggers 
when Distribution_List__c are updated
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Christine Cui			   12/19/2016			   Original Version
**/
public class MFS_DistributionListHandler {

    public static void afterUpdateDistListHandler(Map<Id, Distribution_List__c> newMap, Map<id, Distribution_List__c> oldMap)
    {
      List<Plan_Association__c> planAccsnList = new List<Plan_Association__c>(); 
      List<Distribution_List__c> distList = new List<Distribution_List__c>([Select Id, Name, Organization__c, Email_Address__c, Status__c,
                                                                           (Select Id, name, CRT__c, Contact_Relationship_End_Date__c from Distribution_List__c.Plan_Associations__r) from Distribution_List__c 
                                                                           where id in :newMap.keySet()]);
        for(Distribution_List__c dlc: distList)  {
            Distribution_List__c dlcNew = newMap.get(dlc.Id);
            Distribution_List__c dlcOld = oldMap.get(dlc.Id);
            
            if(dlcNew.Id == dlcOld.Id && dlcNew.Status__c != dlcOld.Status__c && dlcNew.Status__c == 'Inactive')
            {
              for(Plan_Association__c pac: dlc.Plan_Associations__r) 
              {
                 planAccsnList.add(pac); 
              }
            }
        } 
       List<Plan_Association__c> planAsscnToUpdateList = new List<Plan_Association__c>();
       if(planAccsnList.size() >0){
            planAsscnToUpdateList = MFS_DistributionListUtilities.updatePlanAssociations(planAccsnList);
        }
        Database.SaveResult[] updPlanAssc = Database.update(planAsscnToUpdateList,false);
        
    }
}