src/objects/Event_Relation__c.object
<CustomObject>
    <description>Junction object between Event Requests and requested speakers.</description>
    <fields>
        <fullName>Activity_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Detail</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipLabel>Event Relations</relationshipLabel>
        <relationshipName>Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Requested Speaker</relationshipLabel>
        <relationshipName>Event_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Speaker_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Slot_End__c</fullName>
        <label>Time Slot End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Slot_Start__c</fullName>
        <label>Time Slot Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <picklist>
            <picklistValues>
                <fullName>Analyst Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Market Views</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client &amp; Industry Insights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Update &amp; Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Income Update &amp; Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Capital Market Expectations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Macro/Market Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Update and Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Investment Functions Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Management overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topic does not exist - please list in the Notes section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Continuity / System Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance System Demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Update &amp; Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal / Regulatory / Litigation Welcome / Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lengthening the Time Horizon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Compliance Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Macroeconomic Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Outlook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Risk Oversight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proxy Voting Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Floor Tour</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Relation</label>
    <nameField>
        <displayFormat>Speaker-{00000}</displayFormat>
        <label>Requested Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Relation_Portfolio_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Event_Relation__c</fullName>
        <label>Requested Speaker</label>
        <referenceTo>Event_Relation__c</referenceTo>
        <relationshipLabel>Related Portfolios</relationshipLabel>
        <relationshipName>Event_Relation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Portfolio</label>
    <nameField>
        <label>Related Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <fields>
        <fullName>Call_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Activity_Detail__c</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call__c</fullName>
        <label>Call &amp; Participant Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Types__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dealer Conference - National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Conference - Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Diligence Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Introduction/Strategy Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media / PR Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-firm Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio/Strategy Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roadshow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner Event/Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Due Diligence</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Request</relationshipLabel>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Speaker_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeZone__c</fullName>
        <label>Timezone</label>
        <picklist>
            <picklistValues>
                <fullName>(UTC-06:00) Central time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-05:00) Eastern time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+00:00) Dublin, Edinburgh, Lisbon, London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+08:00) Kuala Lumpur, Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+10:00) Canberra, Melbourne, Sydney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Mountain Time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-08:00) Pacific Time (US &amp; Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-12:00) International Date Line West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-11:00) Coordinated Universal Time-11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-10:00) Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-09:00) Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-04:00) Atlantic Time (Canada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-03:30) Newfoundland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-03:00) Brasilia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-01:00) Azores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+02:00) Athens, Bucharest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:00) Minsk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:30) Tehran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+03:00) Moscow, St. Petersburg, Volgograd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+04:30) Kabul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:00) Islamabad, Karachi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+05:45) Kathmandu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC+06:00) Dhaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-08:00) Baja California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-07:00) Chihuahua, La Paz, Mazatlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-06:00) Central America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(UTC-06:00) Guadalajara, Mexico City, Monterrey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_SendEventToOutlookCtrl.cls
/***************************************************************************************************
Apex Class Name    : MFS_SendEventToOutlookCtrl
Version            : 1.0 
Created Date       : 3 Nov 2016
Function           : Controller to create outlook ics file 
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Manoj Parida            11/3/2016              Original Version
***************************************************************************************************/
public with sharing class MFS_SendEventToOutlookCtrl{
    public String startDate{get;set;}
    public String endDate{get;set;}
    public String localStartTime{get;set;}
    public String mStartDate{get;set;}
    public String mEndDate{get;set;}
    public String now{get;set;}
    public String rcCode{get;set;}
    public Event event {get;set;}
    public String portfolios{get;set;}
    public String vehicleTypes{get;set;}
    public Event_Relation__c eventRel{get;set;}
    static String formatStr = 'yyyyMMdd\'T\'HHmmss';
    public String detailURL{get;set;}
    public String linkText {get; set; }
    public MFS_SendEventToOutlookCtrl(){
        String baseURl = URL.getSalesforceBaseUrl().toExternalForm();
        Id eventId = ApexPages.currentPage().getParameters().get('eventId');
        linkText = 'N/A';
        try{
            eventRel = [Select Activity_Detail__c,Time_Slot_Start__c, Time_Slot_End__c, Speaker__r.Email, Speaker_Request__r.Call__c, Speaker_Request__r.Location__c,
                        Speaker__r.Employee_ID__c, Topic__c, Speaker_Request__r.TimeZone__c, Speaker_Request__r.Event_Title__c, Speaker_Request__r.Requester__c,
                        Speaker_Request__r.Requester__r.Name, Speaker_Request__r.Event_Types__c, Speaker_Request__r.Audience__c, Speaker_Request__r.Dress_Code__c,
                        Speaker_Request__r.Tier__c, Speaker_Request__r.Asset_Class__c, Speaker_Request__r.Organization__r.Name, Speaker__r.Name,Speaker_Request__r.Organization__r.Type,
                        Speaker_Request__r.MFS_Contact_for_Presentation_Materials__r.Name, Speaker_Request__r.Link_to_presentation_materials__c,
                        Speaker_Request__r.Speaker_Expense_RC_Code__c, Speaker_Request__r.Event_Instructions__c, Speaker_Request__r.Call_Note__c, CreatedBy.Name
                        from Event_Relation__c where Id =: eventId];
            now = DateTIme.now().format(formatStr);
            startDate = eventRel.Time_Slot_Start__c == null ? '':eventRel.Time_Slot_Start__c.format(formatStr);
            endDate = eventRel.Time_Slot_End__c==null? '' : eventRel.Time_Slot_End__c.format(formatStr);
            String eventTimeZone = (eventRel.Speaker_Request__r.TimeZone__c == null) ? 'EST' : eventRel.Speaker_Request__r.TimeZone__c.subString(1,10).replace('UTC','GMT');
            System.debug('eventTimeZone'+eventTimeZone);
            localStartTime = eventRel.Time_Slot_Start__c == null ? '':eventRel.Time_Slot_Start__c.format('MM/dd/yyyy hh:mm a',eventTimeZone);
            mStartDate = eventRel.Time_Slot_Start__c == null ? '':eventRel.Time_Slot_Start__c.format('MM/dd/yyyy hh:mm a',UserInfo.getTimeZone().getId());
            mendDate = eventRel.Time_Slot_End__c == null ? '':eventRel.Time_Slot_End__c.format('MM/dd/yyyy hh:mm a',UserInfo.getTimeZone().getId());
            event = new Event();
            event = [Select IsAllDayEvent from Event where Activity_Detail__c =:eventRel.Speaker_Request__r.Call_Note__c Limit 1];
            
            List<Event_Relation_Portfolio_Junction__c> portfList = new List<Event_Relation_Portfolio_Junction__c>([select Portfolio__r.Name, Portfolio__r.Vehicle__c from Event_Relation_Portfolio_Junction__c where Event_Relation__c = :eventId]);
            portfolios = '';
            for(Event_Relation_Portfolio_Junction__c erpj : portfList)
            {
                if(String.isempty(portfolios))
                    portfolios = erpj.Portfolio__r.Name;
                else
                    portfolios += ', '+erpj.Portfolio__r.Name;
                if(String.isEmpty(vehicleTypes))
                    vehicleTypes = erpj.Portfolio__r.Vehicle__c;
                else
                    vehicleTypes += ', '+erpj.Portfolio__r.Vehicle__c;
            }
            User usr = [select RC_Code__c from User where Id = :eventRel.Speaker_Request__r.Requester__c];
            rcCode = usr.RC_Code__c;
            if(eventRel != null && !String.isEmpty(eventRel.activity_Detail__c)){
                Event ev = [select id, recordtype.DeveloperName, WhatId from Event where activity_Detail__c = :eventRel.activity_Detail__c ORDER BY createddate ASC LIMIT 1 ];
                if(ev != null && !String.isEmpty(ev.recordtype.DeveloperName)){
                    linkText = Label.Outlook_Click_Here;
                    detailURL = baseURl+'/apex/MFS_A360MeetingDetails?id='+eventRel.Activity_Detail__c+'&nooverride=1&returnID='+ev.whatId+'&event=true';
                }
            }
        }
        Catch(Exception ex){
            System.debug(ex.getMessage()+ex.getLineNUmber());
        }    
    }    
}