src/objects/Event_Relation__c.object
<CustomObject>
    <description>Junction object between Event Requests and requested speakers.</description>
    <fields>
        <fullName>Speaker_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker Request</label>
        <referenceTo>Event_Request__c</referenceTo>
        <relationshipLabel>Requested Speaker</relationshipLabel>
        <relationshipName>Event_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Slot_End__c</fullName>
        <label>Time Slot End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Slot_Start__c</fullName>
        <label>Time Slot Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event Relation</label>
    <nameField>
        <displayFormat>Speaker-{00000}</displayFormat>
        <label>Requested Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Request__c.object
<CustomObject>
    <description>To be used to track Speaker Request, looks up to Activity Details</description>
    <label>Event Request</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Id__c</fullName>
        <label>Field Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>StoreFieldIds</label>
</CustomObject>

src/classes/MFS_NewRequestedSpeakerExt_Test.cls
@isTest
public class MFS_NewRequestedSpeakerExt_Test {
  static testmethod void newrequestedSpeakerButtonTest()
  {
      Test.startTest();
      User usr = MFS_TestDataUtility.createUser('System Administrator');
      insert usr;
      Event_Request__c eReq = MFS_TestDataUtility.createEventRequest(usr.Id);
      insert eReq;
      Event_Relation__c reqSpkr = new Event_Relation__c(Speaker_Request__c = eReq.Id);
      List<Event_Relation__c> reqSpkrList = new List<Event_Relation__c>();
      reqSpkrList.add(reqSpkr);
      StoreFieldIds__c sfId = new StoreFieldIds__c(name='979820338',Field_API_Name__c='Speaker_Request__c',Field_Id__c='CF00NP0000000zoLz',Object_Name__c='Event_Relation__c',Field_Label__c='Speaker Request');
        insert sfId;
        
        StoreFieldIds__c sfId1 = new StoreFieldIds__c(name='979820339',Field_API_Name__c='Time_Slot_Start__c',Field_Id__c='00NP0000000zoOP',Object_Name__c='Event_Relation__c',Field_Label__c='Time Slot Start');
        insert sfId1;
        
        StoreFieldIds__c sfId2 = new StoreFieldIds__c(name='979820340',Field_API_Name__c='Time_Slot_End__c',Field_Id__c='00NP0000000zoOU',Object_Name__c='Event_Relation__c',Field_Label__c='Time Slot End');
        insert sfId2;
 
      MFS_NewRequestedSpeakerExt spkrExt = new MFS_NewRequestedSpeakerExt(new ApexPages.StandardSetController(reqSpkrList));
      PageReference pr =  new PageReference('/'+eReq.id);
      pr.getParameters().put('Id',eReq.id); 
      test.setCurrentPage(pr);
      PageReference result = spkrExt.redirect();
      //SONAR Fix
      System.assertNotEquals(null,result.getUrl());
      Test.StopTest();
  }
}