src/objects/ExceptionLog__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>ClassName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDetails__c</fullName>
        <label>ErrorDetails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorLine__c</fullName>
        <label>ErrorLine</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorType__c</fullName>
        <label>ErrorType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>MethodName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectValues__c</fullName>
        <label>ObjectValues</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ExceptionLog</label>
    <nameField>
        <label>ExceptionLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExceptionLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HandleException.cls
public class HandleException extends Exception
{
private static list<ExceptionLog__c> lstException = new list<ExceptionLog__c>();

public static void addException (sObject Obj, Exception ex, String message, String className, String methodName, String errorLine, String errorMessage, String errorDetails, String errorStackTrace, String errorType, String name, String id)
{
    ExceptionLog__c log = new ExceptionLog__c(
        ClassName__c = className,
        MethodName__c = methodName,
        ErrorLine__c = errorLine,
        ErrorMessage__c = errorMessage,
        ErrorDetails__c = errorStackTrace,
        ErrorType__c = errorType,
        ObjectValues__c = String.valueOf(Obj),
        Name = name,
        Id = id
    );
    lstException.add(log); 
}

public static void saveExceptionLog()
{
    if(!lstException.isEmpty())
    {
        Database.insert(lstException,false); 
    }
  }
 }