src/objects/Goal__c.object
<CustomObject>
    <description>To be used to capture Global Standard Goals.</description>
    <fields>
        <fullName>Analyst_Meeting__c</fullName>
        <label>Analyst Meeting</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement__c</fullName>
        <label>Client Engagement</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meetings__c</fullName>
        <label>Client Review Meetings</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant_Meetings__c</fullName>
        <label>Consultant Meetings</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institutional_Portfolio_Manager__c</fullName>
        <label>Institutional Portfolio Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager__c</fullName>
        <label>Portfolio Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting__c</fullName>
        <label>Sr. Executive Meeting</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Client_Events__c</fullName>
        <label>Sr. Investment Speaker @ Client Events</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portfolio_Manager__c.object
<CustomObject>
    <description>Junction Object between Users and Products</description>
    <fields>
        <fullName>Portfolio_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portfolio_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portfolio Manager</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Portfolio Manager ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Manager</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategy_Plan__c.object
<CustomObject>
    <description>To be used to capture Client and Prospect strategy plans</description>
    <fields>
        <fullName>Analyst_Meeting_Goal__c</fullName>
        <label>Analyst Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Goal__c</fullName>
        <description>Field is populated based on goal, can be edited</description>
        <label>Client Engagement Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meeting_Goal__c</fullName>
        <label>Client Review Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant_Meeting_Goal__c</fullName>
        <label>Consultant Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Strategy Plans</relationshipLabel>
        <relationshipName>Strategy_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institutional__c</fullName>
        <label>Institutional Portfolio Manager Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager_Meeting_Goal__c</fullName>
        <label>Portfolio Manager Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting_Goal__c</fullName>
        <label>Sr. Executive Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Goal__c</fullName>
        <label>Sr. Investment Speaker Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Strategy Plan</label>
    <nameField>
        <label>Strategy Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_StrategyPlanUtilities.cls
/**
Apex Class Name    : MFS_StrategyPlanUtilities
Version            : 1.0 
Created Date       : 11 MAY 2016
Function           : Utility class that gets called by Strategy Plan Triggers 
when Strategy plans are created,updated and deleted
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Jata Dubey              21/04/2016              Original Version
**/
public class MFS_StrategyPlanUtilities {
    //Populate fields of Strategy plan from Goal object
    public static void populateGoalDetailsInStrategyPlan(List<Strategy_Plan__c> planList){
        try{
            Set<Id> goalIdSet = new Set <Id> ();
            Map <Id, Goal__c> goalMap ;
            for (Strategy_Plan__c plan : planList ){ 
                if(plan.Goal__c != null)
                    goalIdSet.add(plan.Goal__c);
            }
            
            if(goalIdSet.size() > 0){
                goalMap = new Map<Id,Goal__c> ([select Client_Engagement__c,Institutional_Portfolio_Manager__c,Consultant_Meetings__c,
                                                Client_Review_Meetings__c,Portfolio_Manager__c,Analyst_Meeting__c,Sr_Executive_Meeting__c,
                                                Sr_Investment_Speaker_Client_Events__c from Goal__c where Id in : goalIdSet]);
                
                if(goalMap != null && goalMap.size() > 0){
                    for(Strategy_Plan__c plan : planList){
                        if(goalMap.containsKey(plan.Goal__c)){
                            Goal__c goal = goalMap.get(plan.Goal__c);
                            plan.Client_Engagement_Goal__c = goal.Client_Engagement__c;
                            plan.Institutional__c = goal.Institutional_Portfolio_Manager__c;
                            plan.Consultant_Meeting_Goal__c = goal.Consultant_Meetings__c;
                            plan.Client_Review_Meeting_Goal__c = goal.Client_Review_Meetings__c;
                            plan.Portfolio_Manager_Meeting_Goal__c =  goal.Portfolio_Manager__c;
                            plan.Analyst_Meeting_Goal__c = goal.Analyst_Meeting__c;
                            plan.Sr_Executive_Meeting_Goal__c = goal.Sr_Executive_Meeting__c;
                            plan.Sr_Investment_Speaker_Goal__c = goal.Sr_Investment_Speaker_Client_Events__c;
                        }
                    }
                }
            }
        } catch(Exception exe) {
            System.debug('Execption occured:'+exe.getMessage());
        }
    }
}