src/objects/Goal__c.object
<CustomObject>
    <description>To be used to capture Global Standard Goals.</description>
    <fields>
        <fullName>Analyst_Meeting__c</fullName>
        <label>Analyst Meeting</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement__c</fullName>
        <label>Client Engagement</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meetings__c</fullName>
        <label>Client Review Meetings</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant_Meetings__c</fullName>
        <label>Consultant Meetings</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institutional_Portfolio_Manager__c</fullName>
        <label>Institutional Portfolio Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager__c</fullName>
        <label>Portfolio Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting__c</fullName>
        <label>Sr. Executive Meeting</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Client_Events__c</fullName>
        <label>Sr. Investment Speaker @ Client Events</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portfolio_Manager__c.object
<CustomObject>
    <description>Junction Object between Users and Products</description>
    <fields>
        <fullName>Portfolio_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portfolio_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portfolio Manager</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Portfolio Manager ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Manager</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategy_Plan__c.object
<CustomObject>
    <description>To be used to capture Client and Prospect strategy plans</description>
    <fields>
        <fullName>Analyst_Meeting_Goal__c</fullName>
        <label>Analyst Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Goal__c</fullName>
        <description>Field is populated based on goal, can be edited</description>
        <label>Client Engagement Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meeting_Goal__c</fullName>
        <label>Client Review Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant_Meeting_Goal__c</fullName>
        <label>Consultant Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Strategy Plans</relationshipLabel>
        <relationshipName>Strategy_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institutional__c</fullName>
        <label>Institutional Portfolio Manager Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager_Meeting_Goal__c</fullName>
        <label>Portfolio Manager Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting_Goal__c</fullName>
        <label>Sr. Executive Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Goal__c</fullName>
        <label>Sr. Investment Speaker Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Strategy Plan</label>
    <nameField>
        <label>Strategy Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_StrategyPlanUtilitiesTest.cls
@isTest
private class MFS_StrategyPlanUtilitiesTest {
    static testmethod void populateGoalDetailsInStrategyPlanTest(){
        List<Account> accRec = new List<Account>();
        accRec = MFS_TestDataUtility.createBulkAccounts(3);
        Test.startTest();
        insert accRec;
        List<Goal__c> goalRec = new List<Goal__c>();
        goalRec = MFS_TestDataUtility.createBulkGoal(3);
        insert goalRec;
        List<Strategy_Plan__c> spRec = new List<Strategy_Plan__c>();
        spRec = MFS_TestDataUtility.createBulkSplan(accRec, 2);
        for(Strategy_Plan__c addRec : spRec)
        {
            for(Integer j=0; j<goalRec.size(); j++)
            {
                Goal__c gol = goalRec[j];
                for(Integer k=0; k<spRec.size(); k++)
                {
                    addRec.Goal__c = gol.Id; 
                }
            }
        }
        insert spRec;
        Test.stopTest();
        spRec = [select Client_Engagement_Goal__c,Institutional__c,Consultant_Meeting_Goal__c,Client_Review_Meeting_Goal__c,Portfolio_Manager_Meeting_Goal__c,Analyst_Meeting_Goal__c,Sr_Executive_Meeting_Goal__c,
                 Sr_Investment_Speaker_Goal__c from Strategy_Plan__c where id in : spRec];
        goalRec = [select Client_Engagement__c,Institutional_Portfolio_Manager__c,Consultant_Meetings__c,Client_Review_Meetings__c,Portfolio_Manager__c,Analyst_Meeting__c,
                   Sr_Executive_Meeting__c,Sr_Investment_Speaker_Client_Events__c from Goal__c where Id in : goalRec ];
        for(Strategy_Plan__c sp : spRec)
        {
            for(Goal__c go : goalRec)
            {
                 System.assertEquals(go.Client_Engagement__c,sp.Client_Engagement_Goal__c);
                 System.assertEquals(go.Institutional_Portfolio_Manager__c,sp.Institutional__c);
                 System.assertEquals(go.Consultant_Meetings__c,sp.Consultant_Meeting_Goal__c);
                 System.assertEquals(go.Client_Review_Meetings__c,sp.Client_Review_Meeting_Goal__c);
                 System.assertEquals(go.Portfolio_Manager__c,sp.Portfolio_Manager_Meeting_Goal__c);
                 System.assertEquals(go.Analyst_Meeting__c,sp.Analyst_Meeting_Goal__c);
                 System.assertEquals(go.Sr_Executive_Meeting__c,sp.Sr_Executive_Meeting_Goal__c);
                 System.assertEquals(go.Sr_Investment_Speaker_Client_Events__c,sp.Sr_Investment_Speaker_Goal__c);
            }
        }
       
        
    }
}