src/objects/Notify_User__c.object
<CustomObject>
    <fields>
        <fullName>Termination_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Termination Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Notify Users</relationshipLabel>
        <relationshipName>Notify_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_email__c</fullName>
        <formula>User__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User email</label>
        <type>Text</type>
    </fields>
    <label>Notify User</label>
    <nameField>
        <displayFormat>NU-{000}</displayFormat>
        <label>NotifyUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notify Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_CustomButtonUtilities.cls
/***************************************************************************************************
Apex Class Name    : MFS_CustomButtonUtilities
Version            : 1.0 
Created Date       : 17 Oct 2016
Function           : This is a Controller for custom button to create a new team member from Contact
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* MAhesh Selvaraj            10/17/2016              Original Version
***************************************************************************************************/
global class MFS_CustomButtonUtilities{
    webService static String getNotifyUserEmails (String caseid) {
        String sEmails = '';
        for(Notify_User__c  nu:[select User_email__c from Notify_User__c where Termination_Case__c =: caseid]) {
            sEmails += nu.User_email__c  + ';' ;
        }
        return sEmails;	
    }
}