src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>Results are pre-filtered for this Organization, click &quot;Show All Results&quot; to expand search results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Client Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/classes/MFS_NewRESOpportunityTest.cls
@isTest(SeeAllData=false)
public class MFS_NewRESOpportunityTest {
    
    static testmethod void testRedirect(){
        Test.startTest();
        Id accRecordType=Schema.SObjectType.Account.getRecordTypeInfosByName().get(MFS_AllConstants.ACC_CLIENT_RECTYPE).getRecordTypeId();
        Account accRec=MFS_TestDataUtility.createAccount();
        accRec.RecordTypeId=accRecordType;
        insert accRec;
        Contact con = MFS_TestDataUtility.createContact(accRec.Id);
        insert con;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.Id);
        insert oppRec;
        List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Opportunity','Client Contact','Client_Contact__c'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Opportunity','Name','Name'));
        insert fieldIds;
        List<Opportunity> oppList = new List<Opportunity>{oppRec};
        PageReference pageRef = Page.MFS_NewRESOpp;
        pageRef.getParameters().put('Id',con.Id);
        Test.setCurrentPage(pageRef);
        MFS_NewRESOpportunity newOpp=new MFS_NewRESOpportunity(new ApexPages.StandardSetController(oppList));   
        PageReference pageURL=newOpp.redirect();    
        System.assert(pageURL != null);  
        //Exception Case
        pageRef.getParameters().put('Id',accRec.Id);
        Test.setCurrentPage(pageRef);
        MFS_NewRESOpportunity newOpp1=new MFS_NewRESOpportunity(new ApexPages.StandardSetController(oppList));   
        PageReference pageURL1=newOpp1.redirect();
        Test.stopTest();
    }

}