src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <label>Asset Class-Geography</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee_Structure__c</fullName>
        <description>If Fee Structure = &apos;Custom&apos; an approval will be required when added</description>
        <label>Fee Structure</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_First_Strategy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is First Strategy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Vehicle__c</fullName>
        <label>Vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seperate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <formula>(TEXT((Product2.Geography__c)))&amp;&quot; &quot;&amp;(TEXT(Product2.Asset_Class__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Class-Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <formula>Product2.Is_Unknown__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Vehicle__c</fullName>
        <formula>TEXT( Product2.Vehicle__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <formula>Product2.Restricted__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <description>Do not delete..Used for Product search</description>
        <label>Asset Class-Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global ex US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Country - Non US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Fixed Income</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to track unknown strategy</description>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the product can be seen but cannot be sold yet.

OLD: &quot;Portfolio Active Status: Indicates whether a portfolio is Active or Inactive. The status of the portfolio is Active when the fund has assets or is being prepared for funding. The status of the portfolio is Inactive after the termination date. and/or
Portfolio Open Ended Flag: A flag on the portfolio that indicates if it is open or closed ended. When the fund is open ended, shares are created for investor purchase and taken out of circulation for redemption. When the fund is closed ended, a specified number of shares are available for investor purchase.&quot;</description>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/MFS_ProductSearchController_Test.cls
/***************************************************************************************************
Apex Class Name    : MFS_ProductSearchController_Test 
Version            : 1.0 
Created Date       : 16 MAY 2016
Function           : Test class for MFS_ProductSearchController
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Priya Gupta               16/05/2016              Original Version
***************************************************************************************************/
@isTest
public class MFS_ProductSearchController_Test {  
    static testmethod void testUnknownStrategy()
    {
       Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;       
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        prodRec.Is_Unknown__c=true;
        insert prodRec;  
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry; 		
        Test.setCurrentPage(Page.MFS_ProductSearch);        
        MFS_ProductSearchController prdSCtrl = new MFS_ProductSearchController(new ApexPages.StandardController(oppRec)); 
        PricebookEntry pbEnt = [select Product2.Name,Product_Vehicle__c,Restricted__c,Asset_Class_Geography__c from PricebookEntry where Id =:pbEntry.Id];
        System.debug('pbEntry:'+pbEnt);        
        prdSCtrl.selectedAssetGeography=pbEnt.Asset_Class_Geography__c; 
        prdSCtrl.addUnknownStrategy();
        //SONAR Fix
        System.assert((prdSCtrl.oppLineItems).size()>0);
        Test.stopTest();
    }
   
     static testmethod void testAddWithFirstStrategy(){
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;       
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec;  
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry; 		
        Test.setCurrentPage(Page.MFS_ProductSearch);        
        MFS_ProductSearchController prdSCtrl = new MFS_ProductSearchController(new ApexPages.StandardController(oppRec)); 
        PricebookEntry pbEnt = [select Product2.Name,Product_Vehicle__c,Restricted__c,Asset_Class_Geography__c from PricebookEntry where Id =:pbEntry.Id];
        System.debug('pbEntry:'+pbEnt);
        prdSCtrl.searchOpt=pbEnt.Product2.Name; 
        prdSCtrl.selectedAssetGeography=pbEnt.Asset_Class_Geography__c;
        prdSCtrl.selectedVehicle=pbEnt.Product_Vehicle__c;
        prdSCtrl.searchProduct();
        prdSCtrl.toSelect=pbEnt.Product2.Name; 
        prdSCtrl.addToLineItem(); 
        System.assert((prdSCtrl.oppLineItems).size()>0);
        prdSCtrl.oppLineItems[0].Fee_Structure__c='Custom';       
        prdSCtrl.onSave();
        prdSCtrl.onCancel();  
        Test.stopTest();
     }
      
    static testmethod void testRemoveWithFirststrategy()
    {
          Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;       
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec;  
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry; 		
        Test.setCurrentPage(Page.MFS_ProductSearch);        
        MFS_ProductSearchController prdSCtrl = new MFS_ProductSearchController(new ApexPages.StandardController(oppRec)); 
        PricebookEntry pbEnt = [select Product2.Name,Product_Vehicle__c,Restricted__c,Asset_Class_Geography__c from PricebookEntry where Id =:pbEntry.Id];
        System.debug('pbEntry:'+pbEnt);
        prdSCtrl.searchOpt=pbEnt.Product2.Name; 
        prdSCtrl.selectedAssetGeography=pbEnt.Asset_Class_Geography__c;
        prdSCtrl.selectedVehicle=pbEnt.Product_Vehicle__c;
        prdSCtrl.searchProduct();
        prdSCtrl.toSelect=pbEnt.Product2.Name; 
        prdSCtrl.addToLineItem();
        prdSCtrl.toUnselect=pbEntry.Id;   
        prdSCtrl.removeFromLineItem();
        System.assert((prdSCtrl.oppLineItems).size()==0);
        Test.stopTest();
    }
    
    static testmethod void testAddRemoveWithMultiStrategy(){
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;       
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        insert prodRec;  
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry; 
        OpportunityLineItem oppLi=MFS_TestDataUtility.createOpportunityLineItem(oppRec.id, pbEntry.id);
        oppLi.Is_First_Strategy__c=true;
        insert oppLi;
        Product2 prodRec1=MFS_TestDataUtility.createProduct();
        prodRec1.Name='TestProduct2';
        insert prodRec1;  
        PricebookEntry pbEntry1=MFS_TestDataUtility.createPriceBEntry(prodRec1);       
        insert pbEntry1;
        Test.setCurrentPage(Page.MFS_ProductSearch);        
        MFS_ProductSearchController prdSCtrl = new MFS_ProductSearchController(new ApexPages.StandardController(oppRec)); 
        PricebookEntry pbEnt = [select Product2.Name,Product_Vehicle__c,Restricted__c,Asset_Class_Geography__c from PricebookEntry where Id =:pbEntry1.Id];
        System.debug('pbEntry:'+pbEnt);
        prdSCtrl.searchOpt=pbEnt.Product2.Name; 
        prdSCtrl.searchProduct();
        prdSCtrl.toSelect=pbEnt.Product2.Name; 
        prdSCtrl.addToLineItem(); 
        System.assert((prdSCtrl.oppLineItems).size()>0);
        prdSCtrl.toUnselect=pbEntry.Id;   
        prdSCtrl.removeFromLineItem();
        prdSCtrl.oppLineItems[0].Fee_Structure__c='Standard';
        prdSCtrl.onSave();
        prdSCtrl.onCancel();   
        List<Selectoption> vehicleOpt=prdSCtrl.getVehicleOptions();
        System.assert(vehicleOpt.size()>0);
         List<Selectoption> assetClOpt=prdSCtrl.getGeograhpyOptions();
        System.assert(assetClOpt.size()>0);
        Test.stopTest();
        
     }
    static testmethod void testException(){
        Test.startTest();
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Opportunity oppRec=MFS_TestDataUtility.createOpportunity(accRec.id);
        insert oppRec;       
        Product2 prodRec=MFS_TestDataUtility.createProduct();
        prodRec.Is_Unknown__c=true;
        insert prodRec;  
        PricebookEntry pbEntry=MFS_TestDataUtility.createPriceBEntry(prodRec);       
        insert pbEntry; 
        delete oppRec;
        Test.setCurrentPage(Page.MFS_ProductSearch);        
        MFS_ProductSearchController prdSCtrl = new MFS_ProductSearchController(new ApexPages.StandardController(oppRec)); 
        prdSCtrl.addUnknownStrategy();
        prdSCtrl.onSave();
        prdSCtrl.addToLineItem();
        prdSCtrl.searchProduct();
        //SONAR Fix
        System.assert((prdSCtrl.oppLineItems) == null);
        Test.stopTest();
    }

}