src/objects/Plan_Association__c.object
<CustomObject>
    <description>To be used to capture relationships between contacts and Plans</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related third party primary contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Plan_Account_Relationships_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>$Organization.Country</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <label>Association</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Related Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Id__c</fullName>
        <label>Field Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>StoreFieldIds</label>
</CustomObject>

src/classes/MFS_NewPlanAssociationExtnTest.cls
@isTest
public class MFS_NewPlanAssociationExtnTest {

    static testMethod void testRedirect(){
        Test.startTest();
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Contact cont = MFS_TestDataUtility.createContact(acc.Id);
        insert cont;
        Plan_Association__c planAsn = new Plan_Association__c(Contact__c=cont.Id);
        List<Plan_Association__c> plnList = new List<Plan_Association__c>();
        plnList.add(planAsn);
        StoreFieldIds__c sfId = new StoreFieldIds__c(name='-1914A728123',Field_API_Name__c='Contact__c',Field_Id__c='CF00NP0000000smyR',Object_Name__c='Plan_Association__c',Field_Label__c='Contact');
        insert sfId;
        
        StoreFieldIds__c sfId1 = new StoreFieldIds__c(name='-1914A7B28127',Field_API_Name__c='Organization__c',Field_Id__c='CF00NP0000000smyR',Object_Name__c='Plan_Association__c',Field_Label__c='Organization__c');
        insert sfId1;
        
        
        MFS_NewPlanAssociationExtn hhExtn = new MFS_NewPlanAssociationExtn(new ApexPages.StandardSetController(plnList));   
        PageReference pr =  new PageReference('/'+cont.id);
        pr.getParameters().put('Id',cont.id); 
        test.setCurrentPage(pr);
        PageReference pageURL = hhExtn.redirect();
        System.assert(pageURL!=null);
        Test.stopTest();
        
    }
}