src/objects/PMAPS__c.object
<CustomObject>
    <description>Used to track and manage external correspondences including, but not limited to: RFP, RFI, 15C.  Integrates with PMAPS WebPro.</description>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <picklist>
            <picklistValues>
                <fullName>Consultant Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>PMAPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RFPs (Org Name)</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Relationship_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person/Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PMAPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_MFS_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary MFS Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RFPs</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFP</label>
    <nameField>
        <displayFormat>RFP-{0000}</displayFormat>
        <label>RFP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MFS_NewRFPExtn.cls
/***************************************************************************************************
Apex Class Name    : MFS_NewRFPExtn
Version            : 1.0 
Created Date       : 8 Sep 2016
Function           : This is a Controller for the custom button to create new RFP from opportunity
Modification Log   :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Manoj Parida           8/9/2016              Original Version
***************************************************************************************************/
public with sharing class MFS_NewRFPExtn {
    
    public MFS_NewRFPExtn(ApexPages.StandardSetController stdCtrl){
        
    }
    
    public PageReference redirect(){ 
        PageReference pageRef;
        Opportunity opp;
        Case cse;
        String id = ApexPages.currentPage().getParameters().get('id');
        try {
            if(id!=null && id.startsWith('006')){
                opp = [select id, name, account.id, account.name, owner.id, owner.name from opportunity where id=:ApexPages.currentPage().getParameters().get('id')];
            }else{
                cse = [select id, caseNumber, accountid, account.name, owner.id, owner.name from Case where id=:ApexPages.currentPage().getParameters().get('id')];
            }
            
            
            List<String> listOfFields=new List<String>{'Service_Request__c','Org_Name__c','Sales_Person_Relationship_Manager__c',
                'Business_Type__c','Secondary_MFS_Contact__c','Opportunity__c'};
                Map<String,String> fieldMap=MFS_Utilities.getFieldId('PMAPS__c',listOfFields);
            system.debug('fieldMap====='+fieldMap);
            Schema.DescribeSObjectResult r = PMAPS__c.sObjectType.getDescribe();
            String keyPrefix = r.getKeyPrefix();			
            pageRef=new PageReference('/'+keyPrefix+'/e');
            if(opp != null && id!=null && id.startsWith('006')){
                pageRef.getParameters().put('retURL',opp.Id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(5)),opp.Name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(5))+'_lkid',opp.Id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1)),opp.account.name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1))+'_lkid',opp.accountid);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(2)),opp.owner.name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(3)),'New Business');
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(4)),UserInfo.getName());
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(4))+'_lkid',UserInfo.getUserId()); 
            }else{
                pageRef.getParameters().put('retURL',cse.Id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0)),cse.caseNumber);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0))+'_lkid',cse.Id);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1)),cse.account.name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1))+'_lkid',cse.accountid);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(2)),cse.owner.name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(3)),'New Business');
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(4)),UserInfo.getName());
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(4))+'_lkid',UserInfo.getUserId()); 
            }
            
        } catch(Exception e){
            system.debug('Exception in redirect : MFS_NewRFPExtn  '+e.getMessage()+e.getLineNumber()+e.getStackTraceString());
        }
        return pageRef;
    }
    
}