src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset_Class_Geography__c</fullName>
        <description>Do not delete..Used for Product search</description>
        <label>Asset Class-Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets (diversified) Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerging Markets Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global ex US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Fixed Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Country - Non US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Alternatives/Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Balanced/Multi-Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Fixed Income</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Class_by_Geography__c</fullName>
        <formula>(TEXT((Geography__c)))&amp;&quot; &quot;&amp;(TEXT(Asset_Class__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Class - Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to track unknown strategy</description>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Record_Type__c</fullName>
        <formula>IF(  RecordType.DeveloperName =&apos;Portfolio&apos;, &apos;2.Portfolio&apos;,&apos;1.Strategy&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the product can be seen but cannot be sold yet.

OLD: &quot;Portfolio Active Status: Indicates whether a portfolio is Active or Inactive. The status of the portfolio is Active when the fund has assets or is being prepared for funding. The status of the portfolio is Inactive after the termination date. and/or
Portfolio Open Ended Flag: A flag on the portfolio that indicates if it is open or closed ended. When the fund is open ended, shares are created for investor purchase and taken out of circulation for redemption. When the fund is closed ended, a specified number of shares are available for investor purchase.&quot;</description>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategy</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Strategies</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman CFC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Portfolio</fullName>
        <active>true</active>
        <label>Portfolio</label>
    </recordTypes>
</CustomObject>

src/objects/Strategy_Rating_Process__c.object
<CustomObject>
    <description>Used to track and manage the rating process, looks up to Accounts and Products</description>
    <fields>
        <fullName>Consultant__c</fullName>
        <label>Consultant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pending Ratings</relationshipLabel>
        <relationshipName>New_Consultant_Rating</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategy</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>New_Consultant_Rating</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategy Rating Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Rating Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Australia Unit Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collective Investment Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Family of Funds (US)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFS Investment Funds (FCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separate Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subadvised Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIT III</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MFS_StrategyRatingController.cls
global class MFS_StrategyRatingController {
    public string searchString{get;set;} // search keyword
    public List<SearchWrapper> wraplist{get;set;} 
    public String selectedProductName { get; set; }
    public String selectedConsultantName { get; set; }
    public Boolean isInConsole { get; set; }
    public String searchOpt{
        set{searchOpt=value;}
        get{return searchOpt;}
    }
    public String selectedAssetGeography{
        get{return selectedAssetGeography;}
        set{selectedAssetGeography=value;}
    }
    public String selectedVehicle{
        get{return selectedVehicle;}
        set{selectedVehicle=value;}
    } 
    public MFS_StrategyRatingController() {
        // get the current search string
        searchString = System.currentPageReference().getParameters().get('lksrch');
        String url = ApexPages.CurrentPage().getURL();
        if(url!= null && url.containsIgnoreCase('isInConsole')){
            isInConsole = true;
        }
        User usr = [select Vehicle__c from User where id = :UserInfo.getUserId()];
        selectedVehicle = usr.Vehicle__c;
        wraplist = new List<SearchWrapper>();
        searchProduct();
    }
    public MFS_StrategyRatingController(ApexPages.StandardController controller){
        if(controller.getId() != null && UserInfo.getUiThemeDisplayed() != 'Theme3'){
            Strategy_Rating_Process__c srp = [select Product__r.Name, Consultant__r.Name from Strategy_Rating_Process__c where Id = :controller.getId()];
            selectedProductName = srp.Product__r.Name;
            selectedConsultantName = srp.Consultant__r.Name;
        }
    }
    
    // performs the keyword search
   
    // used by the visualforce page to send the link to the right dom element
    public string getFormTag() {
        return System.currentPageReference().getParameters().get('frm');
    }
    
    // used by the visualforce page to send the link to the right dom element for the text box
    public string getTextBox() {
        return System.currentPageReference().getParameters().get('txt');
    }
    
    //search product fro the modal
    public void searchProduct(){
        try{
            wraplist = new List<SearchWrapper>();            
            String query=constructQuery(searchOpt,selectedAssetGeography,selectedVehicle);
            List<Product2> pList = Database.query(query);                
            for(Product2 pbRec : pList){  
                wraplist.add( new SearchWrapper(false, pbRec, pbRec.ID, MFS_AllConstants.PRODUCT_ASSET_CLASS_GEOHRAPHY_VALUES.get(pbRec.Asset_Class_by_Geography__c))); 
            }
        }catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,Label.A360_Error_Message_1 + ex.getMessage() +' - '+ ex.getLineNumber()));
        }
    }
    
    //Construct query for product search depending on user's entry
    @TestVisible
    private  String constructQuery(String productName,String productGeography,String productVehicle)
    {
        String query='Select Id,Strategy__r.Name,Name,Asset_Class_by_Geography__c,Vehicle__c,Restricted__c, Product_Record_Type__c from Product2 where IsActive=true and Is_Unknown__c =false and Restricted__c=false  '; //Asset_Class_Geography__c field is replace by Asset_Class_by_Geography__c on 01/Feb/2017
        if(productName!='' && productName!=null){
            //query=query+' AND Name like '+'\'%'+String.escapeSingleQuotes(productName)+ '%\' ';
            query=query+' AND (Strategy__r.Name like '+'\'%'+String.escapeSingleQuotes(productName)+ '%\''+' OR Name like '+'\'%'+String.escapeSingleQuotes(productName)+ '%\''+')';
        }
        if(productGeography!='None' && productGeography!=null && productGeography!=''){
            query=query+' AND Asset_Class_by_Geography__c ='+'\''+String.escapeSingleQuotes(productGeography)+'\' ';
        }
        if(productVehicle!='None' && productVehicle!=null && productVehicle!='')
        {
            query=query+' AND Vehicle__c='+'\''+String.escapeSingleQuotes(productVehicle)+'\' ';
            
        }
        if(query.EndsWith('AND ')) {
            query = query.removeEnd('AND ');
        }
        query=query+' ORDER BY Product_Record_Type__c,Strategy__r.Name,Name, Vehicle__c ASC Limit 25'; //Limit is changed on 01/Feb/2017
        return query;
    }
    
    //Method is used to get Asset Class-Geography picklist from Product2 object
    public List<Selectoption> getGeograhpyOptions(){
        List<Selectoption>  prodGeograhpy=new List<Selectoption> ();
        prodGeograhpy.add(new SelectOption(MFS_AllConstants.PICKLIST_DEFAULT,'---'+MFS_AllConstants.PICKLIST_DEFAULT+'---'));        
        map<String, Schema.SObjectField> fieldMap = Product2.getSObjectType().getDescribe().fields.getMap();
        list<Schema.PicklistEntry> values = fieldMap.get(MFS_AllConstants.PRODUCT_GEOGRAPHY).getDescribe().getPickListValues();
        for (Schema.PicklistEntry a : values)
        { 
            prodGeograhpy.add(new SelectOption(a.getValue(),a.getLabel())); 
        }
        return prodGeograhpy;
    }
    
    //Method is used to get Vehicle picklist from Product2 object  
    public List<Selectoption> getVehicleOptions(){
        List<Selectoption>  prodVehicleList=new List<Selectoption> ();
        prodVehicleList.add(new SelectOption(MFS_AllConstants.PICKLIST_DEFAULT,'---'+MFS_AllConstants.PICKLIST_DEFAULT+'---'));
        Schema.sObjectType objType = Product2.getSObjectType(); 
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        list<Schema.PicklistEntry> values =     fieldMap.get(MFS_AllConstants.PRODUCT_VEHICLE).getDescribe().getPickListValues();
        for (Schema.PicklistEntry a : values)
        { 
            prodVehicleList.add(new SelectOption(a.getValue(),a.getLabel())); 
        }
        return prodVehicleList; 
    }
    
    //Set the variable when "add portfolio" is clicked from invitee section
    public void loadProducts(){
        User usr = [select Vehicle__c from User where id = :UserInfo.getUserId()];
        selectedVehicle = usr.Vehicle__c;
        selectedAssetGeography ='';
        searchOpt = '';
        searchProduct();
    }
    
    //Wrapper for Product Search and Competitor Product Search
    public class SearchWrapper{
        public Product2 prg {get;set;}
        public Id prodId{get;set;}
        public Boolean isSelected { get; set; }
        public String assetClassGeoName{get; set; }
        
        //Used for products
        public SearchWrapper( Boolean slct, Product2 pr, Id prId, String assetClassGeoName) {
            this.prg = pr;
            this.prodId = prId;
            this.isSelected = slct;
            this.assetClassGeoName = assetClassGeoName;
        }
    }
    
    //This method is usind in SLDS to populate lookup field
    @RemoteAction
    global static List<Account> queryAccounts(String keyword) {
        List<Account> accountList = new List<Account>();
        if (keyword != null && keyword.trim() != '') {
            keyword = '%' + keyword + '%';
            accountList = [Select Id, Name from Account where Name like :keyword limit 5];
        }
        return accountList;
    }
}