src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Is_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to track unknown strategy</description>
        <label>Is Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the product can be seen but cannot be sold yet.

OLD: &quot;Portfolio Active Status: Indicates whether a portfolio is Active or Inactive. The status of the portfolio is Active when the fund has assets or is being prepared for funding. The status of the portfolio is Inactive after the termination date. and/or
Portfolio Open Ended Flag: A flag on the portfolio that indicates if it is open or closed ended. When the fund is open ended, shares are created for investor purchase and taken out of circulation for redemption. When the fund is closed ended, a specified number of shares are available for investor purchase.&quot;</description>
        <label>Restricted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Strategy_Rating_Process__c.object
<CustomObject>
    <description>Used to track and manage the rating process, looks up to Accounts and Products</description>
    <label>Strategy Rating Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Rating Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_StrategyRatingControllerTest.cls
@isTest(seeAllData = false)
public class MFS_StrategyRatingControllerTest {
    public static testMethod void testStrategyProcess(){
        Pagereference prf = Page.MFS_StrategyRating;
        Test.setCurrentPage(prf);
        ApexPages.currentPage().getParameters().put('isInConsole', 'true');
        MFS_StrategyRatingController srCtrl = new MFS_StrategyRatingController();
        Account acc = MFS_TestDataUtility.createAccount();
        insert acc;
        Product2 prod = MFS_TestDataUtility.createProduct();
        prod.Restricted__c = false;
        prod.Is_Unknown__c = false;
        insert prod;
        Strategy_Rating_Process__c srp = MFS_testDataUtility.createStrategyRatingProcess(acc.Id, prod.Id);
        insert srp;
        srCtrl.getFormTag();
        srCTrl.getTextBox();
        srCtrl.constructQuery('test','test','test');
		
        MFS_StrategyRatingController exCtrl = new MFS_StrategyRatingController(new ApexPages.StandardController(srp));
        exCtrl.getGeograhpyOptions();
        exCtrl.getVehicleOptions();
        exCtrl.loadProducts();
        exCtrl.searchOpt = 'testProduct';
        exCtrl.selectedAssetGeography = 'Emerging Markets (diversified) Equity';
        exCtrl.selectedVehicle = 'Domestic Mutual Fund';
        exCtrl.searchproduct();
        System.assertEquals(0, exCtrl.wraplist.size());
        exCtrl.searchOpt = '';
        exCtrl.selectedAssetGeography = '';
        exCtrl.selectedVehicle = '';
        exCtrl.searchproduct();
        MFS_StrategyRatingController.queryAccounts('Test');
        System.assertEquals(1, exCtrl.wraplist.size());
    }
}