src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/objects/Strategy_Rating_Process__c.object
<CustomObject>
    <description>Used to track and manage the rating process, looks up to Accounts and Products</description>
    <fields>
        <fullName>Consultant__c</fullName>
        <label>Consultant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pending Ratings</relationshipLabel>
        <relationshipName>New_Consultant_Rating</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy Rating Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Rating Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_OrgNewConsultantStrategyRating_Test.cls
@isTest(SeeAllData=false)
public class MFS_OrgNewConsultantStrategyRating_Test {
     static testmethod void testRedirect()
    {
        Test.startTest();
       
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Strategy_Rating_Process__c strrate = new Strategy_Rating_Process__c(Consultant__c = accRec.Id);
        insert strrate;
        List<Strategy_Rating_Process__c> srList = new List<Strategy_Rating_Process__c>();
        srList.add(strrate);
        List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Strategy_Rating_Process__c','Consultant','Consultant__c'));
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Strategy_Rating_Process__c','Name','Name'));
        insert fieldIds;
        
        MFS_OrgNewConsultantStrategyRating consultantRating=new MFS_OrgNewConsultantStrategyRating(new ApexPages.StandardSetController(srList));   
        PageReference pageURL=new PageReference('/'+accRec.id);    
        pageURL.getParameters().put('Id',accRec.id); 
        test.setCurrentPage(pageURL);
        PageReference result = consultantRating.redirect();
        //SONAR Fix
        System.assertNotEquals(null,result.getUrl());
        Test.StopTest();
    }
    

}