src/objects/StoreFieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StoreFieldIds</label>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <description>This will serve as the junction object to tie Contacts with Teams.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup relationship to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Team</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_AddTeamMember_Test.cls
@isTest(SeeAllData=false)
public class MFS_AddTeamMember_Test {

     static testmethod void testRedirect(){
        Test.startTest();
       
        Account accRec=MFS_TestDataUtility.createAccount();
        insert accRec;
        Contact contactRec=MFS_TestDataUtility.createContact(accRec.Id);
        insert contactRec;
        List<StoreFieldIds__c> fieldIds=new List<StoreFieldIds__c>();
        fieldIds.add(MFS_TestDataUtility.createFieldIDData('Team_Member__c','Contact','Contact__c'));       
        insert fieldIds;
        List<Team_Member__c> memberList = new List<Team_Member__c>{new Team_Member__c()};
        PageReference pageRef = Page.MFS_AddContactTeamMember;
        pageRef.getParameters().put('Id',contactRec.Id);
        Test.setCurrentPage(pageRef);
        MFS_AddTeamMember addMember=new MFS_AddTeamMember(new ApexPages.StandardSetController(memberList));   
        PageReference pageURL=addMember.redirect();    
        System.assert(pageURL!=null);             
        Test.stopTest();
    }
    
}