src/objects/Strategy_Plan__c.object
<CustomObject>
    <description>To be used to capture Client and Prospect strategy plans</description>
    <fields>
        <fullName>Analyst_Meeting_Goal_Counter__c</fullName>
        <label>Analyst Meeting Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Analyst_Meeting_Goal__c</fullName>
        <label>Analyst Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Counter__c</fullName>
        <label>Client Engagement Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Goal__c</fullName>
        <description>Field is populated based on goal, can be edited</description>
        <label>Client Engagement Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meeting_Goal_Counter__c</fullName>
        <label>Client Review Meeting Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Review_Meeting_Goal__c</fullName>
        <label>Client Review Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant_Meeting_Goal_Counter__c</fullName>
        <label>Consultant Meeting Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Meeting_Goal__c</fullName>
        <label>Consultant Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institutional_Portfolio_Manager_Goal_Cou__c</fullName>
        <label>Institutional Portfolio Mgr Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Institutional__c</fullName>
        <label>Institutional Portfolio Manager Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager_Meeting_Goal_Counter__c</fullName>
        <label>Portfolio Manager Meeting Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portfolio_Manager_Meeting_Goal__c</fullName>
        <label>Portfolio Manager Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting_Goal_Counter__c</fullName>
        <label>Sr. Executive Meeting Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sr_Executive_Meeting_Goal__c</fullName>
        <label>Sr. Executive Meeting Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Goal_Counter__c</fullName>
        <label>Sr. Investment Speaker Goal Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sr_Investment_Speaker_Goal__c</fullName>
        <label>Sr. Investment Speaker Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Strategy Plan</label>
    <nameField>
        <label>Strategy Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_StrategyPlanGoalsProgressBarExtTest.cls
@isTest
public class MFS_StrategyPlanGoalsProgressBarExtTest {

    public static testmethod void progressBar()
    {
        Test.startTest();
        Account recAcc = MFS_TestDataUtility.createAccount();
        insert recAcc;
        Account recLimitAcc = [Select Id from Account where Id = : recAcc.Id];
        System.debug('test account' + recLimitAcc);
        Strategy_Plan__c recSp = MFS_TestDataUtility.createStrategyPlan(recLimitAcc.Id);
        recSp.Institutional__c = '12';
        recSp.Institutional_Portfolio_Manager_Goal_Cou__c = 5;  
        recSp.Consultant_Meeting_Goal__c = '3';
        recSp.Consultant_Meeting_Goal_Counter__c = 7;
        recSp.Portfolio_Manager_Meeting_Goal__c = '5';
        recSp.Portfolio_Manager_Meeting_Goal_Counter__c = 2;
        recSp.Sr_Executive_Meeting_Goal__c = '14';
        recSp.Sr_Executive_Meeting_Goal_Counter__c = 7;
        recSp.Client_Engagement_Goal__c = '25';
        recSp.Client_Engagement_Counter__c = 23; 
        recSp.Client_Review_Meeting_Goal__c = '10';
        recSp.Client_Review_Meeting_Goal_Counter__c =  1; 
        recSp.Analyst_Meeting_Goal__c = '16';
        recSp.Analyst_Meeting_Goal_Counter__c = 9; 
        recSp.Sr_Investment_Speaker_Goal__c = '9';
        recSp.Sr_Investment_Speaker_Goal_Counter__c = 8;
        insert recSp;
        Strategy_Plan__c recLimitSp = [Select id from Strategy_Plan__c where Id = : recSp.Id];
        MFS_SPlanGoalsProgressBarExtension spbe = new MFS_SPlanGoalsProgressBarExtension(new ApexPages.StandardController(recLimitSp));
        spbe.init();
        //SONAR Fix
        System.assert(spbe.lstOutput.size() > 0);
        
        //Exception Test
        recSp.Client_Review_Meeting_Goal__c = '0';
        recSp.Client_Review_Meeting_Goal_Counter__c =  0; 
        recSp.Analyst_Meeting_Goal__c = '0';
        recSp.Analyst_Meeting_Goal_Counter__c = 0; 
        recSp.Sr_Investment_Speaker_Goal__c = '0';
        recSp.Sr_Investment_Speaker_Goal_Counter__c = 0;
        update recSp;
        MFS_SPlanGoalsProgressBarExtension spbe1 = new MFS_SPlanGoalsProgressBarExtension(new ApexPages.StandardController(recLimitSp));
        spbe1.init();
        //SONAR Fix
        System.assert(spbe1.lstOutput.size() > 0);
        
        recSp.Client_Review_Meeting_Goal__c = '0';
        recSp.Client_Review_Meeting_Goal_Counter__c =  0; 
        recSp.Analyst_Meeting_Goal__c = '0';
        recSp.Analyst_Meeting_Goal_Counter__c = 0; 
        recSp.Sr_Investment_Speaker_Goal__c = '1asd';
        recSp.Sr_Investment_Speaker_Goal_Counter__c = 0;
        update recSp;
        MFS_SPlanGoalsProgressBarExtension spbe2 = new MFS_SPlanGoalsProgressBarExtension(new ApexPages.StandardController(recLimitSp));
        spbe2.init();
        //SONAR Fix
        System.assert(spbe2.lstOutput == null);
        Test.stopTest();
    }
}