src/objects/Team__c.object
<CustomObject>
    <description>This object will contain all sales data for teams.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <description>This will serve as the junction object to tie Contacts with Teams.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup relationship to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Team</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MFS_AddTeamMember.cls
/***************************************************************************************************
Apex Class Name    : MFS_AddTeamMember 
Version            : 1.0 
Created Date       : 10 August 2016
Function           : Class is used to prepopulate fields on creation of new team member from Contact related list button.
Modification Log   :
***************************************************************************************************/

public with sharing class MFS_AddTeamMember {
    
    //Standard Controller
    public MFS_AddTeamMember(ApexPages.StandardSetController stdCtrl){
    }
    
    /**
    * @Description : Method is used to construct URL for redirection
    * @Param : N/A
    * @return: PageReference
    **/     
    public PageReference redirect(){
        Schema.DescribeSObjectResult r = Team_Member__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();            
        PageReference pageRef=new PageReference('/'+keyPrefix+'/e');
        try {
            Id recId = ApexPages.currentPage().getParameters().get('id');
                String objName = recId.getSObjectType().getDescribe().getName();
            List<String> listOfFields=new List<String>{'Contact__c','Team__c'};
                Map<String,String> fieldMap=MFS_Utilities.getFieldId('Team_Member__c',listOfFields);   
            if(objName == 'Contact'){
                Contact contactRec=[Select id,Name from Contact where id=:ApexPages.currentPage().getParameters().get('id')];
                pageRef.getParameters().put(MFS_AllConstants.RETURN_URL,contactRec.Id);          
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0)),contactRec.Name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(0))+MFS_AllConstants.LK_ID,contactRec.Id);
            }
            else{
                Team__c team = [select id, Name from Team__c where id =:ApexPages.currentPage().getParameters().get('id')];
                pageRef.getParameters().put(MFS_AllConstants.RETURN_URL,team.Id);          
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1)),team.Name);
                pageRef.getParameters().put(fieldMap.get(listOfFields.get(1))+MFS_AllConstants.LK_ID,team.Id);
            }
        } catch(Exception exe) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,exe.getmessage()));
            system.debug('Exception');
        }
        return pageRef;
    } 
}